services:
  db:
    image: mariadb:11
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: db
      PMA_PASSWORD: db
    ports:
      - '3300:80'

volumes:
  db_data:
