#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Tiket 09: maintenance window, salin data final, lalu pindahkan domain.
#
# Jalankan HANYA setelah wizard-07 selesai dan seluruh smoke test di hostname
# validasi hijau. Wizard ini menghentikan trafik tulis production.
#
# Batas rollback: sampai stage 10 (flip domain), pembatalan cukup mengembalikan
# Host rule ke Application lama — database dan RustFS lama tidak pernah
# disentuh migrasi. SETELAH trafik tulis dibuka, stack lama bukan lagi jalur
# rollback.

TOTAL_STAGES=12

# Digest kandidat yang sedang berjalan di candidate.production.kammi.id
# (tag sha-7bd5305, lihat provisioning-record.local.md § "Update kandidat
# 2026-08-30"). sha-b0e5ee6 lama sudah tidak dipakai sejak digest dipindah;
# memakainya lagi akan menjalankan migrasi tanpa 20260829210747_huge_lockjaw
# (kolom article.gallery_images) yang sudah diasumsikan Application kandidat.
CANDIDATE_DIGEST="sha256:385e8caae8641fb09e83b328ab88174d907c413e81240b3ad6cc766b54af4cf9"
CANDIDATE_IMAGE="ghcr.io/kammi-id/kammi-id@${CANDIDATE_DIGEST}"

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.env.cutover}"
RECORD_FILE="${RECORD_FILE:-$SCRIPT_DIR/.env.cutover-record.md}"

dokploy_get() { curl -sS --max-time 30 -H "x-api-key: $2" "${1%/}/api/$3"; }
jq_err() { printf '%s' "$1" | jq -r '.message // empty' 2>/dev/null; }
ssh_prod() { ssh "${SSH_OPTS[@]}" "$SSH_HOST" "$@"; }

# mark "label" — catat waktu UTC sebuah tonggak ke catatan rilis dan layar.
mark() {
  local stamp; stamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  printf -- '- %s — %s\n' "$stamp" "$1" >> "$RECORD_FILE"
  note "⏱  $stamp — $1"
}

cd "$REPO_ROOT"
banner "Cutover production — maintenance window"

# ── 1 ───────────────────────────────────────────────────────────────────────
stage "Prasyarat dan deadline abort"
warn "Wizard ini MENGHENTIKAN trafik tulis production."
say "Dua peran harus hadir sampai pengawasan aktif selesai:"
say "  · deployment lead  — menjalankan checklist"
say "  · product/data owner — memutuskan go/no-go dan rollback"
for c in jq ssh curl; do
  command -v "$c" >/dev/null 2>&1 || { warn "'$c' tidak ditemukan"; exit 1; }
done
if [[ ! -f "$ENV_FILE" ]]; then
  warn "$ENV_FILE tidak ada — jalankan wizard-07 dulu"; exit 1
fi
umask 077
ask WINDOW_MINUTES "Anggaran maintenance window dalam menit (target 30-60):"
: "${WINDOW_MINUTES:=60}"
START_EPOCH=$(date -u +%s)
ABORT_EPOCH=$((START_EPOCH + WINDOW_MINUTES * 60))
ABORT_AT=$(date -u -r "$ABORT_EPOCH" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null \
  || date -u -d "@$ABORT_EPOCH" +%Y-%m-%dT%H:%M:%SZ)
printf '\n# Cutover %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$RECORD_FILE"
mark "window dimulai; deadline abort $ABORT_AT"
warn "Lewat $ABORT_AT tanpa smoke test hijau: BATALKAN dan kembalikan domain"
warn "ke Application lama. Jangan memperbaiki data secara improvisasi."
if ! confirm "Kedua peran hadir dan sepakat memulai window?"; then
  warn "tidak disepakati; berhenti"; exit 1
fi

# ── 2 ───────────────────────────────────────────────────────────────────────
stage "Muat keadaan dan gate kesiapan"
ask PROD_URL "URL panel Dokploy production:"
ask_secret PROD_API_KEY "API key Dokploy production:"
health=$(dokploy_get "$PROD_URL" "$PROD_API_KEY" "settings.health")
[[ "$health" == '{"status":"ok"}' ]] || { warn "settings.health: $health"; exit 1; }
ask SSH_HOST "SSH target host production (user@host):"
ask SSH_KEY "Identity file SSH:"
SSH_OPTS=(-o ServerAliveInterval=15 -o ServerAliveCountMax=10)
if [[ -n "$SSH_KEY" ]]; then
  SSH_OPTS+=(-i "${SSH_KEY/#\~/$HOME}")
fi
ask DOCKER_NETWORK "Docker network:"
ask OLD_PG_CONTAINER "Container Postgres LAMA:"
ask NEW_PG_CONTAINER "Container Postgres BARU:"
ask OLD_DB_NAME "Database LAMA:"
ask OLD_DB_USER "User database LAMA:"
ask NEW_DB_NAME "Database BARU:"
ask NEW_DB_USER "User database BARU:"
ask UPLOAD_VOLUME "Named volume upload BARU:"
ask VALIDATION_HOST "Hostname validasi:"
ask RUSTFS_BUCKET "Bucket RustFS:"
ask RUSTFS_ENDPOINT "Endpoint RustFS:"
say ""
say "Gate kesiapan — semuanya harus sudah benar SEBELUM trafik disentuh:"
step "wizard-07 selesai; restore, migrasi, dan mirror aset sudah lulus."
step "Smoke test di $VALIDATION_HOST hijau seluruhnya."
step "Backup Postgres dan kedua volume project baru aktif dan terbukti."
step "Uptime monitor dan jalur notifikasi insiden sudah teruji."
step "Application maintenance sudah dideploy dan siap menerima Host rule."
if ! confirm "Seluruh gate di atas terpenuhi?"; then
  warn "gate belum terpenuhi — batalkan tanpa menyentuh trafik"; exit 1
fi

# ── 3 ───────────────────────────────────────────────────────────────────────
stage "Maintenance page mengambil domain"
warn "Satu Host rule tidak boleh dimiliki dua Application sekaligus."
say "Urutannya WAJIB: lepas dari Application lama DULU, baru pasang ke"
say "maintenance. Jangan pernah terbalik."
open_url "${PROD_URL%/}/dashboard"
step "Application LAMA → Domains → hapus apex, www, dan wildcard *.kammi.id."
pause "Ketiga Host rule sudah LEPAS dari Application lama — tekan Enter."
step "Application MAINTENANCE → Domains → tambahkan apex, www, dan wildcard."
step "Pastikan TLS untuk ketiganya valid."
step "JANGAN sentuh exact route assets.kammi.id — ia tetap milik RustFS lama."
pause "Maintenance sudah memegang ketiga Host rule — tekan Enter."
mark "maintenance page aktif; write freeze dimulai"
ask APEX_HOST "Hostname apex production (mis. kammi.id):"
write_env APEX_HOST "$APEX_HOST"
APEX_CODE=$(curl -sS -o /dev/null -w '%{http_code}' "https://${APEX_HOST}/" || echo "000")
note "apex sekarang menjawab HTTP $APEX_CODE"
say "Periksa dengan mata bahwa halaman maintenance yang tampil, bukan aplikasi."
open_url "https://${APEX_HOST}/"
if ! confirm "Halaman maintenance tampil di apex dan satu subdomain tenant?"; then
  warn "routing maintenance salah — kembalikan domain ke Application lama dan berhenti"
  exit 1
fi

# ── 4 ───────────────────────────────────────────────────────────────────────
stage "Buktikan write sudah berhenti"
say "Application lama tidak lagi punya domain. Sekarang buktikan tidak ada"
say "sesi yang masih menulis — dibaca, bukan dimatikan paksa."
WRITERS=$(ssh_prod "docker exec -i '$OLD_PG_CONTAINER' psql -t -A -U '$OLD_DB_USER' -d '$OLD_DB_NAME' -c \"select count(*) from pg_stat_activity where datname='$OLD_DB_NAME' and state='active' and backend_type='client backend' and pid <> pg_backend_pid();\"" | tr -d '[:space:]')
note "sesi client aktif di database lama: ${WRITERS:-?}"
if [[ "${WRITERS:-1}" != "0" ]]; then
  warn "masih ada sesi aktif. Tunggu sampai nol; JANGAN pg_terminate_backend."
  step "Pastikan Application lama benar-benar tidak menerima request."
  pause "Tekan Enter untuk memeriksa ulang setelah menunggu."
  WRITERS=$(ssh_prod "docker exec -i '$OLD_PG_CONTAINER' psql -t -A -U '$OLD_DB_USER' -d '$OLD_DB_NAME' -c \"select count(*) from pg_stat_activity where datname='$OLD_DB_NAME' and state='active' and backend_type='client backend' and pid <> pg_backend_pid();\"" | tr -d '[:space:]')
  note "pemeriksaan ulang: ${WRITERS:-?}"
fi
mark "write freeze terverifikasi (sesi aktif: ${WRITERS:-?})"
say "Inilah checkpoint RPO 0 — semua yang sesudah ini menyalin keadaan final."

# ── 5 ───────────────────────────────────────────────────────────────────────
stage "Final dump dan restore"
FINAL_DUMP="/tmp/kammi-cutover-final-$(date -u +%Y%m%dT%H%M%SZ).dump"
say "Mengambil pg_dump -Fc final dari database lama..."
ssh_prod "docker exec '$OLD_PG_CONTAINER' pg_dump -Fc -U '$OLD_DB_USER' -d '$OLD_DB_NAME' > '$FINAL_DUMP'"
FINAL_BYTES=$(ssh_prod "wc -c < '$FINAL_DUMP'" | tr -d ' ')
[[ "${FINAL_BYTES:-0}" -gt 0 ]] || { warn "dump final kosong; BATALKAN"; exit 1; }
mark "final dump selesai: $FINAL_BYTES byte"
warn "DESTRUKTIF terhadap database BARU — menimpa hasil pre-copy wizard-07."
if ! confirm "Restore final $FINAL_BYTES byte ke '$NEW_DB_NAME'?"; then
  warn "dibatalkan — kembalikan domain ke Application lama"; exit 1
fi
ssh_prod "docker exec -i '$NEW_PG_CONTAINER' pg_restore --clean --if-exists --no-owner --no-privileges -U '$NEW_DB_USER' -d '$NEW_DB_NAME' < '$FINAL_DUMP'" \
  || warn "pg_restore melaporkan galat — 'does not exist' normal untuk --if-exists, baca sisanya"
mark "final restore selesai"

# ── 6 ───────────────────────────────────────────────────────────────────────
stage "Rekonsiliasi ledger, preflight, dan migrasi"
warn "Restore final menimpa ledger migrasi LAGI dengan punya production lama."
say "Verifikasi ulang satu per satu — jawabannya bisa berbeda dari wizard-07"
say "kalau ada migrasi yang sempat dijalankan di antaranya."
DB_MIGRATIONS=$(cat <<'SQLEOF' | ssh_prod "docker exec -i '$NEW_PG_CONTAINER' psql -t -A -U '$NEW_DB_USER' -d '$NEW_DB_NAME'"
select name from drizzle.__drizzle_migrations order by id;
SQLEOF
)
MISSING=()
for dir in src/db/__migrations/*/; do
  name=$(basename "$dir")
  [[ -f "${dir}migration.sql" ]] || continue
  grep -qxF "$name" <<< "$DB_MIGRATIONS" || MISSING+=("$name")
done
if (( ${#MISSING[@]} == 0 )); then
  note "ledger lengkap — tidak ada rekonsiliasi"
else
  warn "${#MISSING[@]} migrasi belum tercatat:"
  printf '  - %s\n' "${MISSING[@]}"
  for name in "${MISSING[@]}"; do
    printf '\n  %s%s%s\n' "$BOLD" "$name" "$RESET"
    sed 's/^/    /' "src/db/__migrations/${name}/migration.sql"
    if confirm "Diverifikasi ke DB baru — efek SQL di atas SUDAH ada?"; then
      HASH=$(shasum -a 256 "src/db/__migrations/${name}/migration.sql" | cut -d' ' -f1)
      DATEPART="${name:0:14}"
      MILLIS=$(date -u -j -f "%Y%m%d%H%M%S" "$DATEPART" "+%s000" 2>/dev/null \
        || date -u -d "${DATEPART:0:4}-${DATEPART:4:2}-${DATEPART:6:2} ${DATEPART:8:2}:${DATEPART:10:2}:${DATEPART:12:2}" "+%s000")
      ssh_prod "docker exec -i '$NEW_PG_CONTAINER' psql -U '$NEW_DB_USER' -d '$NEW_DB_NAME' -c \"insert into drizzle.__drizzle_migrations (hash, created_at, name) values ('$HASH', $MILLIS, '$name');\""
      note "dicatat sebagai sudah diterapkan"
    else
      warn "akan benar-benar dijalankan migrator"
    fi
  done
fi
ask_secret NEW_DATABASE_URL "DATABASE_URL Postgres BARU (untuk one-shot; tidak disimpan):"
say "Menjalankan preflight duplikat + migrasi dari digest kandidat..."
if ssh_prod "docker run --rm --network '$DOCKER_NETWORK' \
    -e DATABASE_URL='$NEW_DATABASE_URL' \
    -e RUN_MIGRATIONS=1 -e MIGRATIONS_ONLY=1 -e DB_GUARD_ACK=1 \
    '$CANDIDATE_IMAGE'"; then
  mark "preflight + migrasi lulus"
else
  warn "GAGAL. Duplikat organization.code berarti insiden data, bukan tambalan."
  warn "Kembalikan domain ke Application lama dan tutup window."
  exit 1
fi

# ── 7 ───────────────────────────────────────────────────────────────────────
stage "Final delta aset"
say "Mirror persis: objek yang sudah tidak ada di RustFS ikut dibuang dari"
say "volume, supaya tujuan benar-benar mencerminkan sumber."
ask RUSTFS_ACCESS_KEY "Access key RustFS:"
ask_secret RUSTFS_SECRET_KEY "Secret key RustFS:"
RUSTFS_SCHEME="${RUSTFS_ENDPOINT%%://*}"
RUSTFS_HOSTPART="${RUSTFS_ENDPOINT#*://}"
MC_HOST_VALUE="${RUSTFS_SCHEME}://${RUSTFS_ACCESS_KEY}:${RUSTFS_SECRET_KEY}@${RUSTFS_HOSTPART}"
if ! ssh_prod "docker run --rm --network '$DOCKER_NETWORK' \
    -v '$UPLOAD_VOLUME':/out \
    -e MC_HOST_src='$MC_HOST_VALUE' \
    minio/mc:latest mirror --overwrite --remove --quiet 'src/$RUSTFS_BUCKET' /out"; then
  warn "mc mirror final gagal"; exit 1
fi
ssh_prod "docker run --rm -v '$UPLOAD_VOLUME':/d alpine chown -R 1001:1001 /d"
SRC_STATS=$(ssh_prod "docker run --rm --network '$DOCKER_NETWORK' \
  -e MC_HOST_src='$MC_HOST_VALUE' minio/mc:latest ls --recursive --json 'src/$RUSTFS_BUCKET'" \
  | jq -s '{count: length, bytes: (map(.size) | add // 0)}')
SRC_COUNT=$(printf '%s' "$SRC_STATS" | jq -r '.count')
SRC_BYTES=$(printf '%s' "$SRC_STATS" | jq -r '.bytes')
DST_STATS=$(ssh_prod "docker run --rm -v '$UPLOAD_VOLUME':/d alpine sh -c \"find /d -type f | wc -l; find /d -type f -exec cat {} + 2>/dev/null | wc -c\"")
DST_COUNT=$(printf '%s\n' "$DST_STATS" | sed -n '1p' | tr -d ' ')
DST_BYTES=$(printf '%s\n' "$DST_STATS" | sed -n '2p' | tr -d ' ')
printf '  %-28s %8s berkas %14s byte\n' "RustFS (sumber)" "$SRC_COUNT" "$SRC_BYTES"
printf '  %-28s %8s berkas %14s byte\n' "volume baru (tujuan)" "$DST_COUNT" "$DST_BYTES"
if [[ "$SRC_COUNT" == "$DST_COUNT" && "$SRC_BYTES" == "$DST_BYTES" ]]; then
  mark "aset cocok persis: $SRC_COUNT berkas / $SRC_BYTES byte"
else
  warn "TIDAK COCOK — jangan buka trafik. Investigasi atau batalkan."
  if ! confirm "Tetap lanjut? (hanya kalau sudah dijelaskan dan disetujui)"; then
    exit 1
  fi
fi

# ── 8 ───────────────────────────────────────────────────────────────────────
stage "Smoke test kandidat sebelum domain pindah"
say "Kandidat masih di hostname validasi. Ini gate terakhir yang rollback-nya"
say "masih murah — stack lama utuh dan belum tersentuh migrasi."
open_url "${PROD_URL%/}/dashboard"
step "Redeploy Application baru agar memuat data final (image tetap digest kandidat)."
pause "Application baru sudah dideploy ulang — tekan Enter."
LIVE=$(curl -sS -o /dev/null -w '%{http_code}' "https://${VALIDATION_HOST}/api/health/live" || echo "000")
READY=$(curl -sS -o /dev/null -w '%{http_code}' "https://${VALIDATION_HOST}/api/health/ready" || echo "000")
printf '  %-12s %s\n' "live" "HTTP $LIVE"
printf '  %-12s %s\n' "ready" "HTTP $READY"
if [[ "$LIVE" != "200" || "$READY" != "200" ]]; then
  warn "health tidak hijau — BATALKAN: kembalikan domain ke Application lama"
  exit 1
fi
say ""
step "Login/logout Akun Kepengurusan smoke test; cookie sesi benar."
step "Dasbor terbaca sesuai Cakupan akun."
step "Foto Kader, logo Struktur, dan Artikel bergambar lama tampil — cek MIME/byte."
step "Unggah gambar sintetis, baca ulang, lalu bersihkan lewat aplikasi."
step "Satu mutasi reversibel; cache invalidation dan audit benar."
step "Tenant diuji dari network internal dengan header Host: <slug>.kammi.id."
step "Log aplikasi dan Postgres bersih; tidak ada 5xx; credential teredaksi."
NOW_EPOCH=$(date -u +%s)
if (( NOW_EPOCH > ABORT_EPOCH )); then
  warn "DEADLINE ABORT ($ABORT_AT) SUDAH TERLEWAT."
  warn "Rekomendasi: batalkan, kembalikan domain ke Application lama, ulangi lain hari."
fi
if ! confirm "SELURUH smoke test lulus dan product/data owner menyatakan GO?"; then
  warn "tidak GO — kembalikan apex, www, wildcard ke Application LAMA."
  warn "Jangan down-migrate database baru. Stack lama memakai DB dan RustFS-nya sendiri."
  mark "ABORT setelah smoke test"
  exit 1
fi
mark "smoke test lulus; go diberikan"

# ── 9 ───────────────────────────────────────────────────────────────────────
stage "Checkpoint project baru"
say "Titik pemulihan untuk insiden SESUDAH trafik dibuka — sesudah ini, stack"
say "lama bukan lagi jalur rollback."
open_url "${PROD_URL%/}/dashboard"
step "Postgres BARU → Backups → jalankan satu backup manual sekarang."
step "Volume upload dan cache BARU → jalankan backup manual."
step "Catat ID/nama setiap backup."
ask CHECKPOINT_REF "Referensi checkpoint (ID backup, tanpa credential):"
mark "checkpoint project baru: $CHECKPOINT_REF"
if ! confirm "Ketiga backup selesai dan tercatat?"; then
  warn "tanpa checkpoint, insiden sesudah cutover tidak punya titik pulih. Berhenti."
  exit 1
fi

# ── 10 ──────────────────────────────────────────────────────────────────────
stage "Flip domain ke Application baru"
warn "TITIK TIDAK BISA KEMBALI mendekat. Urutan tetap: lepas dulu, baru pasang."
step "Application MAINTENANCE → Domains → hapus apex, www, dan wildcard."
pause "Ketiga Host rule sudah LEPAS dari maintenance — tekan Enter."
step "Application BARU → Domains → tambahkan apex, www, dan wildcard *.kammi.id."
step "Pastikan TLS ketiganya terbit dan valid."
step "Verifikasi exact route assets.kammi.id MASIH menunjuk RustFS lama dan"
step "  menang atas wildcard — kalau kalah, gambar legacy putus."
pause "Application baru memegang ketiga Host rule — tekan Enter."
mark "domain berpindah ke Application baru"
say "Karena servernya sama, DNS tidak perlu diubah. Ubah DNS hanya bila"
say "preflight membuktikan record-nya memang salah."

# ── 11 ──────────────────────────────────────────────────────────────────────
stage "Verifikasi eksternal dan buka trafik"
for h in "$APEX_HOST" "www.$APEX_HOST"; do
  code=$(curl -sS -o /dev/null -w '%{http_code}' "https://${h}/" || echo "000")
  printf '  %-28s HTTP %s\n' "$h" "$code"
done
READY=$(curl -sS -o /dev/null -w '%{http_code}' "https://${APEX_HOST}/api/health/ready" || echo "000")
printf '  %-28s HTTP %s\n' "readiness via apex" "$READY"
ask ASSETS_HOST "Hostname aset legacy (mis. assets.kammi.id):"
ACODE=$(curl -sS -o /dev/null -w '%{http_code}' "https://${ASSETS_HOST}/" || echo "000")
printf '  %-28s HTTP %s\n' "$ASSETS_HOST" "$ACODE"
say ""
step "Buka satu Situs Struktur tenant dari jaringan luar dan periksa gambarnya."
step "Buka satu Berita dan satu permalink lama."
if ! confirm "Routing, TLS, dan gambar benar dari jaringan luar?"; then
  warn "kembalikan Host rule ke Application LAMA sekarang juga."
  mark "ABORT pada verifikasi eksternal"
  exit 1
fi
mark "TRAFIK TULIS DIBUKA — batas rollback ke stack lama ditutup"
warn "Mulai detik ini stack lama BUKAN rollback langsung. Pemulihan berikutnya"
warn "berada di project baru: image kompatibel-volume, roll-forward, atau"
warn "restore backup baru ($CHECKPOINT_REF)."

# ── 12 ──────────────────────────────────────────────────────────────────────
stage "Catat bukti dan mulai pengawasan"
say "Catatan rilis ada di $RECORD_FILE (berkas ini kena pola .gitignore)."
{
  printf -- '- release SHA: b0e5ee6\n'
  printf -- '- image digest: %s\n' "$CANDIDATE_DIGEST"
  printf -- '- final dump: %s byte\n' "${FINAL_BYTES:-?}"
  printf -- '- aset sumber: %s berkas / %s byte\n' "${SRC_COUNT:-?}" "${SRC_BYTES:-?}"
  printf -- '- aset tujuan: %s berkas / %s byte\n' "${DST_COUNT:-?}" "${DST_BYTES:-?}"
  printf -- '- checkpoint: %s\n' "${CHECKPOINT_REF:-?}"
  printf -- '- nilai secret sengaja tidak dicatat.\n'
} >> "$RECORD_FILE"
note "bukti ditambahkan ke $RECORD_FILE"
say ""
say "Pengawasan aktif minimal 60 menit, kedua peran tetap hadir:"
step "readiness, uptime monitor, 5xx, login, latency DB, disk, upload, gambar."
step "Pantauan diperketat 24 jam sesudahnya."
say ""
say "Belum boleh dilakukan sekarang:"
step "Hentikan Application lama dan cabut sisa Host rule-nya — setelah stabil."
step "Pertahankan Postgres lama TANPA writer minimal 30 hari."
step "Pertahankan RustFS dan $ASSETS_HOST selama URL legacy masih hidup."
warn "Penghapusan stack lama BUKAN bagian runbook ini dan butuh konfirmasi"
warn "serta pekerjaan tersendiri."

finish
