#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Ticket 04: provision the new Dokploy production project. This script does
# not deploy, migrate, take production Host rules, or modify the legacy stack.
# It never records a production credential. Resource evidence is appended to a
# local scratch record for tickets 05 and 07.

TOTAL_STAGES=10
TOTAL_MINUTES=60

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
RECORD_FILE="${RECORD_FILE:-$SCRIPT_DIR/provisioning-record.local.md}"
ENV_FILE="/dev/null"

record_provisioning() {
  umask 077
  mkdir -p "$(dirname "$RECORD_FILE")"
  {
    printf '\n## Provisioning %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf -- '- Dokploy console: %s\n' "$PRODUCTION_CONSOLE_URL"
    printf -- '- Project: %s (`%s`)\n' "$PROJECT_NAME" "$PROJECT_ID"
    printf -- '- Environment: %s (`%s`)\n' "$ENVIRONMENT_NAME" "$ENVIRONMENT_ID"
    printf -- '- PostgreSQL: %s (`%s`); appName `%s`; database `%s`; user `%s`\n' \
      "$POSTGRES_NAME" "$POSTGRES_ID" "$POSTGRES_APP_NAME" "$DATABASE_NAME" "$DATABASE_USER"
    printf -- '- Application: %s (`%s`); appName `%s`; image `%s`; replicas: 1\n' \
      "$APPLICATION_NAME" "$APPLICATION_ID" "$APPLICATION_APP_NAME" "$IMAGE_REFERENCE"
    printf -- '- Upload volume: `%s` → `/data/uploads`; ownership evidence: %s\n' \
      "$UPLOAD_VOLUME" "$UPLOAD_OWNERSHIP_EVIDENCE"
    printf -- '- Cache volume: `%s` → `/app/.next/cache`; ownership evidence: %s\n' \
      "$CACHE_VOLUME" "$CACHE_OWNERSHIP_EVIDENCE"
    printf -- '- Validation hostname: `%s`\n' "$VALIDATION_HOST"
    printf -- '- PostgreSQL backup: %s; retention: %s; destination: %s\n' \
      "$POSTGRES_BACKUP_SCHEDULE" "$POSTGRES_BACKUP_RETENTION" "$BACKUP_DESTINATION"
    printf -- '- Volume backups: %s; retention: %s; destination: %s\n' \
      "$VOLUME_BACKUP_SCHEDULE" "$VOLUME_BACKUP_RETENTION" "$BACKUP_DESTINATION"
    printf -- '- Secret values, DSNs, API keys, and passwords intentionally omitted.\n'
  } >> "$RECORD_FILE"
  note "evidence appended to $RECORD_FILE"
}

cd "$REPO_ROOT"
banner "Provision project Dokploy production baru"

stage "Akses dan inventory host" 5
say "This wizard only prepares an isolated project. Do not edit, stop, or add Host rules to the legacy production project."
ask PRODUCTION_CONSOLE_URL "Dokploy production console URL:"
open_url "${PRODUCTION_CONSOLE_URL%/}/dashboard"
step "Sign in with an account authorized to create projects, databases, applications, volumes, and backups."
step "In the dashboard, identify the agreed production server/Swarm; do not select a different server."
step "Use the host inventory already approved for this release to check existing named volumes. Reserve two names absent from that inventory."
ask UPLOAD_VOLUME "Unique upload named-volume name (must be absent from host inventory):"
ask CACHE_VOLUME "Unique cache named-volume name (must be absent from host inventory):"
pause "Inventory checked and two unique names reserved — press Enter."

stage "Project dan environment baru" 5
open_url "${PRODUCTION_CONSOLE_URL%/}/dashboard"
ask PROJECT_NAME "New production project display name:"
ask ENVIRONMENT_NAME "New production environment name:"
step "Dashboard → Projects → Create Project. Create '$PROJECT_NAME' on the agreed production server."
if ! confirm "Create this new project now?"; then warn "project creation not confirmed; stopping"; exit 1; fi
pause "After Dokploy confirms creation, press Enter."
step "Open the project, create/select its environment '$ENVIRONMENT_NAME', then copy both non-secret IDs from the dashboard URL or details panel."
ask PROJECT_ID "Project ID:"
ask ENVIRONMENT_ID "Environment ID:"

stage "PostgreSQL terisolasi" 8
open_url "${PRODUCTION_CONSOLE_URL%/}/dashboard/project/$PROJECT_ID/environment/$ENVIRONMENT_ID"
ask POSTGRES_NAME "PostgreSQL display name:"
ask DATABASE_NAME "New database name:"
ask DATABASE_USER "New database user:"
step "Environment → Add Service → PostgreSQL. Use '$POSTGRES_NAME', '$DATABASE_NAME', and '$DATABASE_USER'."
step "Generate a new database password in Dokploy's secret field. Do not paste it into this wizard, the ticket, or a repo file."
step "Use the PostgreSQL version and capacity approved for production; do not attach a database from the legacy project."
if ! confirm "Create the new PostgreSQL instance now?"; then warn "PostgreSQL creation not confirmed; stopping"; exit 1; fi
pause "After creation, copy only the PostgreSQL ID and appName; never copy its password or connection URL."
ask POSTGRES_ID "PostgreSQL ID:"
ask POSTGRES_APP_NAME "PostgreSQL appName/service name:"

stage "Application dan registry" 8
open_url "${PRODUCTION_CONSOLE_URL%/}/dashboard/project/$PROJECT_ID/environment/$ENVIRONMENT_ID"
ask APPLICATION_NAME "Application display name:"
ask APPLICATION_APP_NAME "Application appName/service name:"
say "Kandidat rilis sudah dibekukan dan diuji di staging:"
say "  ghcr.io/kammi-id/kammi-id@sha256:27a43de67c6e66301c2d2d65126f94f6c629fc3ec149d00cc67b9934a6744f85"
say "(sama dengan tag sha-b0e5ee6; production dipatok ke digest, bukan tag)"
ask IMAGE_REFERENCE "Immutable image digest/reference:"
step "Environment → Add Service → Application. Create '$APPLICATION_NAME' with source type Docker on the agreed server."
step "Configure the existing approved GHCR registry credential in Dokploy. Do not enter the registry token into this wizard."
step "Set the image to '$IMAGE_REFERENCE' if a frozen candidate exists; otherwise leave the Application undeployed until ticket 06 supplies one."
step "Set replicas to exactly 1. Do not add apex, www, wildcard, or assets.kammi.id Host rules."
if ! confirm "Create the new Application now?"; then warn "Application creation not confirmed; stopping"; exit 1; fi
pause "After creation, copy only the Application ID."
ask APPLICATION_ID "Application ID:"

stage "Mount volume unik" 7
open_url "${PRODUCTION_CONSOLE_URL%/}/dashboard/project/$PROJECT_ID/environment/$ENVIRONMENT_ID/services/application/$APPLICATION_ID"
step "Application → Advanced → Mounts → Create Mount. Select a Docker named volume, not a bind mount."
step "Create/select '$UPLOAD_VOLUME' and mount it at /data/uploads."
step "Create/select '$CACHE_VOLUME' and mount it at /app/.next/cache."
step "Verify neither mount refers to a legacy project volume."
if ! confirm "Save these two volume mounts now?"; then warn "mount creation not confirmed; stopping"; exit 1; fi
pause "After both mounts are visible, press Enter."

stage "Ownership volume" 5
say "A root init/helper may write the volumes, but the Application runs as UID/GID 1001:1001."
step "Using the approved host procedure, run chown -R 1001:1001 on '$UPLOAD_VOLUME' and '$CACHE_VOLUME'."
step "Inspect the mount paths from the Application context and retain a command output or screenshot proving owner/group 1001:1001."
ask UPLOAD_OWNERSHIP_EVIDENCE "Upload ownership evidence reference (command/screenshot ID, no secret):"
ask CACHE_OWNERSHIP_EVIDENCE "Cache ownership evidence reference (command/screenshot ID, no secret):"
pause "Ownership for both named volumes verified — press Enter."

stage "Environment production" 7
open_url "${PRODUCTION_CONSOLE_URL%/}/dashboard/project/$PROJECT_ID/environment/$ENVIRONMENT_ID/services/application/$APPLICATION_ID"
step "Application → Environment. Enter DATABASE_URL using the new PostgreSQL instance; keep its password in Dokploy only."
step "Set UPLOADS_DIR=/data/uploads, NODE_ENV=production, PORT=3000, and HOSTNAME=0.0.0.0."
step "Create/enter API_CO_ID_TOKEN and CACHE_REVALIDATE_SECRET as production-specific secrets in Dokploy. Do not reuse staging values."
step "Confirm RUN_MIGRATIONS and DB_GUARD_ACK are absent. They are allowed only on a later one-shot migration container."
if ! confirm "Save the Application environment now?"; then warn "environment save not confirmed; stopping"; exit 1; fi
pause "Environment saved and forbidden persistent flags absent — press Enter."

stage "Hostname validasi dan health" 5
ask VALIDATION_HOST "Validation hostname (must not claim apex, www, or *.kammi.id):"
open_url "${PRODUCTION_CONSOLE_URL%/}/dashboard/project/$PROJECT_ID/environment/$ENVIRONMENT_ID/services/application/$APPLICATION_ID"
step "Application → Domains. Add only '$VALIDATION_HOST'; verify no apex, www, wildcard, or assets.kammi.id rule is present."
step "Application → Advanced/Health. Configure liveness at /api/health/live and readiness at /api/health/ready according to the Dokploy health policy."
step "Keep the Application off production traffic. Ticket 05 verifies monitor, routing, TLS, and log access before rehearsal."
if ! confirm "Save the validation hostname and health policy now?"; then warn "validation configuration not confirmed; stopping"; exit 1; fi
pause "Validation-only routing and health policy saved — press Enter."

stage "Backup PostgreSQL dan volume" 5
open_url "${PRODUCTION_CONSOLE_URL%/}/dashboard"
ask BACKUP_DESTINATION "Configured backup destination name (no credential):"
ask POSTGRES_BACKUP_SCHEDULE "PostgreSQL backup schedule/cron:"
ask POSTGRES_BACKUP_RETENTION "PostgreSQL retention:"
ask VOLUME_BACKUP_SCHEDULE "Upload/cache volume backup schedule/cron:"
ask VOLUME_BACKUP_RETENTION "Upload/cache volume retention:"
step "Configure PostgreSQL backup in the PostgreSQL Backup section to '$BACKUP_DESTINATION'."
step "Configure one named-volume backup for '$UPLOAD_VOLUME' and one for '$CACHE_VOLUME'; named volumes are required for Dokploy volume backups."
step "Verify each schedule is enabled and record its destination, schedule, and retention without recording credentials."
if ! confirm "Create or save these backup schedules now?"; then warn "backup configuration not confirmed; stopping"; exit 1; fi
pause "All three backup schedules are visible and enabled — press Enter."

stage "Catat bukti handoff" 5
say "The following local record intentionally contains IDs, names, mounts, and backup policy only—never secrets."
record_provisioning
say "Ticket 04 is complete only after you attach the record's non-secret facts to its ticket and retain permission evidence."
say "Next: ticket 05 validates observability/routing; ticket 06 supplies a frozen image digest."
finish
