#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Ticket 05: prove observability and production routing before cutover.
# All Dokploy, SSH, DNS, TLS, log, and backup operations are read-only. The
# only created resources are Uptime Kuma monitors configured by the operator.
# No notification credential or production secret is copied into this script,
# its state file, or its evidence record.

TOTAL_STAGES=10

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
[[ "$ENV_FILE" == ".env" ]] && ENV_FILE="$SCRIPT_DIR/preflight.local.env"
RECORD_FILE="${RECORD_FILE:-$SCRIPT_DIR/preflight-record.local.md}"
PROVISION_ENV_FILE="${PROVISION_ENV_FILE:-$SCRIPT_DIR/provisioning.local.env}"
ROOT_ENV_FILE="$REPO_ROOT/.env"
TMP_DIR=$(mktemp -d)
trap 'rm -rf -- "$TMP_DIR"' EXIT

umask 077
touch "$ENV_FILE"
chmod 600 "$ENV_FILE"

value_from_file() {
  local file="$1" key="$2" line=""
  [[ -f "$file" ]] || return 1
  line=$(grep -E "^${key}=" "$file" | tail -n 1) || return 1
  printf '%s' "${line#*=}"
}

load_value() {
  local target="$1"
  shift
  local key value="" file
  value=$(_existing "$target" || true)
  if [[ -z "$value" ]]; then
    for file in "$PROVISION_ENV_FILE" "$ROOT_ENV_FILE"; do
      for key in "$target" "$@"; do
        value=$(value_from_file "$file" "$key" || true)
        [[ -n "$value" ]] && break 2
      done
    done
  fi
  printf -v "$target" '%s' "$value"
}

api_get() {
  local procedure="$1"
  shift
  curl -sS -G "${DOKPLOY_PROD_URL%/}/api/$procedure" "$@" \
    -H "x-api-key: $DOKPLOY_PROD_API_KEY" --max-time 60
}

api_check() {
  local response="$1" label="$2" error=""
  error=$(printf '%s' "$response" | jq -r \
    'if type == "object" and .code then (.message // .code) else empty end' \
    2>/dev/null || true)
  [[ -z "$error" ]] || { warn "$label gagal: $error"; exit 1; }
}

http_code() {
  local url="$1" code=""
  code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 30 "$url") || code="000"
  printf '%s' "$code"
}

ssh_prod() {
  local options=(-o BatchMode=yes -o ConnectTimeout=15 -o ServerAliveInterval=15)
  [[ -z "${SSH_KEY:-}" ]] || options+=(-i "$SSH_KEY")
  ssh "${options[@]}" "$SSH_HOST" "$1"
}

sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

dns_addresses() {
  local host="$1" addresses=""
  addresses=$(dig +short A "$host"; dig +short AAAA "$host")
  printf '%s' "$addresses" | paste -sd ',' -
}

tls_expiry() {
  local host="$1" pem="" expiry=""
  curl -sS -o /dev/null --max-time 30 "https://${host}/" || return 1
  pem=$(printf '' | openssl s_client -connect "${host}:443" -servername "$host" \
    2>/dev/null) || return 1
  expiry=$(printf '%s' "$pem" | openssl x509 -noout -enddate 2>/dev/null) || return 1
  printf '%s' "$pem" | openssl x509 -checkend 604800 -noout >/dev/null 2>&1 || return 1
  printf '%s' "${expiry#notAfter=}"
}

collect_routes() {
  local projects="$1" kind id project environment resource domains
  : > "$ROUTES_FILE"
  while IFS=$'\t' read -r kind id project environment resource; do
    if [[ "$kind" == "application" ]]; then
      domains=$(api_get "domain.byApplicationId" --data-urlencode "applicationId=$id")
    else
      domains=$(api_get "domain.byComposeId" --data-urlencode "composeId=$id")
    fi
    api_check "$domains" "domain inventory untuk $resource"
    printf '%s' "$domains" | jq -c \
      --arg kind "$kind" --arg id "$id" --arg project "$project" \
      --arg environment "$environment" --arg resource "$resource" \
      '.[] | {kind:$kind,id:$id,project:$project,environment:$environment,
        resource:$resource,host,https,certificateType,serviceName,port,path}' \
      >> "$ROUTES_FILE"
  done < <(printf '%s' "$projects" | jq -r \
    '.[] as $project | $project.environments[] as $environment |
      (($environment.applications[]? |
        ["application",.applicationId,$project.name,$environment.name,.name]),
       ($environment.compose[]? |
        ["compose",.composeId,$project.name,$environment.name,.name])) | @tsv')
}

route_count() {
  jq -s --arg host "$1" \
    '[.[] | select(.host == $host)] | unique_by([.kind,.id]) | length' \
    "$ROUTES_FILE"
}

route_summary() {
  jq -s -r --arg host "$1" \
    '[.[] | select(.host == $host) |
      "\(.kind):\(.project)/\(.environment)/\(.resource)" +
      (if .serviceName then "/" + .serviceName else "" end)] | join(", ")' \
    "$ROUTES_FILE"
}

record_preflight() {
  {
    printf '\n## Observability/routing preflight %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf -- '- Dokploy: `%s`; Application `%s`; PostgreSQL `%s`\n' \
      "$DOKPLOY_VERSION" "$APPLICATION_ID" "$POSTGRES_ID"
    printf -- '- Health policy: `%s`; live HTTP %s; ready HTTP %s; PostgreSQL `%s`\n' \
      "$HEALTH_PATH" "$LIVE_CODE" "$READY_CODE" "$POSTGRES_STATUS"
    printf -- '- Preflight result: **%s**\n' "$PREFLIGHT_STATUS"
    printf -- '- Uptime Kuma status: **%s**; monitor `%s` (%s); notification `%s` (%s); test `%s`\n' \
      "$UPTIME_STATUS" "$UPTIME_MONITOR_NAME" "$UPTIME_MONITOR_REF" \
      "$UPTIME_NOTIFICATION_NAME" "$UPTIME_NOTIFICATION_TYPE" "$ALERT_TEST_REF"
    printf -- '- Incident recipient: %s; responder role: %s\n' \
      "$INCIDENT_RECIPIENT" "$INCIDENT_RESPONDER_ROLE"
    printf -- '- Log access: Application + PostgreSQL readable; secret scan: %s\n' "$LOG_SCAN_STATUS"
    printf -- '- DNS: `%s`=%s; `%s`=%s; `%s`=%s; `%s`=%s\n' \
      "$APEX_HOST" "$APEX_DNS" "$WWW_HOST" "$WWW_DNS" \
      "$TENANT_HOST" "$TENANT_DNS" "$ASSETS_HOST" "$ASSETS_DNS"
    printf -- '- TLS expiry: apex `%s`; www `%s`; tenant `%s`; assets `%s`\n' \
      "$APEX_TLS" "$WWW_TLS" "$TENANT_TLS" "$ASSETS_TLS"
    printf -- '- Host preservation: apex HTTP %s → `%s` hash `%s`; tenant HTTP %s → `%s` hash `%s`\n' \
      "$APEX_PAGE_CODE" "$APEX_EFFECTIVE_URL" "$APEX_BODY_HASH" \
      "$TENANT_PAGE_CODE" "$TENANT_EFFECTIVE_URL" "$TENANT_BODY_HASH"
    printf -- '- Route owner apex: %s; www: %s; wildcard: %s; assets: %s\n' \
      "$APEX_ROUTE_OWNER" "$WWW_ROUTE_OWNER" "$WILDCARD_ROUTE_OWNER" "$ASSETS_ROUTE_OWNER"
    printf -- '- Host free disk: %s GiB (minimum approved %s GiB); network: `%s`\n' \
      "$FREE_DISK_GB" "$MIN_FREE_DISK_GB" "$DOCKER_NETWORK"
    printf -- '- Container networks: Application `%s`; PostgreSQL baru `%s`\n' \
      "$APP_NETWORKS" "$NEW_PG_NETWORKS"
    printf -- '- PostgreSQL sessions: old=%s; new=%s\n' "$OLD_DB_SESSIONS" "$NEW_DB_SESSIONS"
    printf -- '- Backups configured: PostgreSQL=%s; volumes=%s; restore viability remains ticket 07 gate\n' \
      "$POSTGRES_BACKUP_COUNT" "$VOLUME_BACKUP_COUNT"
    printf -- '- Backup destination: %s (`%s`)\n' \
      "$BACKUP_DESTINATION_NAME" "$POSTGRES_BACKUP_DESTINATION_ID"
    printf -- '- Decision/reference: %s\n' "$PREFLIGHT_DECISION_REF"
    printf -- '- Secret values, credentials, raw logs, and DSNs intentionally omitted.\n'
  } >> "$RECORD_FILE"
  chmod 600 "$RECORD_FILE"
  note "bukti non-secret ditambahkan ke $RECORD_FILE"
}

cd "$REPO_ROOT"
banner "Observability dan routing preflight production"

# ── 1. State, tools, and read-only operator access ─────────────────────────
stage "Muat state dan akses operator"
say "Semua pemeriksaan Dokploy/SSH/DNS/TLS bersifat read-only."
say "Wizard tidak memindahkan domain, menghentikan service, atau menjalankan backup."
for tool in curl dig jq openssl ssh; do
  command -v "$tool" >/dev/null 2>&1 || { warn "$tool tidak ditemukan — pasang dulu"; exit 1; }
done

load_value DOKPLOY_PROD_URL DOKPLOY_PROD_URL PROD_URL
load_value DOKPLOY_PROD_API_KEY DOKPLOY_PROD_API_KEY PROD_API_KEY
load_value APPLICATION_ID APPLICATION_ID NEW_APPLICATION_ID
load_value POSTGRES_ID POSTGRES_ID NEW_POSTGRES_ID
load_value VALIDATION_HOST VALIDATION_HOST

if [[ -z "$DOKPLOY_PROD_URL" ]]; then
  ask DOKPLOY_PROD_URL "URL console Dokploy production:"
  write_env DOKPLOY_PROD_URL "$DOKPLOY_PROD_URL"
fi
if [[ -z "$DOKPLOY_PROD_API_KEY" ]]; then
  ask_secret DOKPLOY_PROD_API_KEY "API key Dokploy production:"
  write_env DOKPLOY_PROD_API_KEY "$DOKPLOY_PROD_API_KEY"
fi
if [[ -z "$APPLICATION_ID" ]]; then ask APPLICATION_ID "Application ID kandidat:"; write_env APPLICATION_ID "$APPLICATION_ID"; fi
if [[ -z "$POSTGRES_ID" ]]; then ask POSTGRES_ID "PostgreSQL ID baru:"; write_env POSTGRES_ID "$POSTGRES_ID"; fi
if [[ -z "$VALIDATION_HOST" ]]; then ask VALIDATION_HOST "Hostname validasi kandidat:"; write_env VALIDATION_HOST "$VALIDATION_HOST"; fi

settings_health=$(api_get "settings.health")
api_check "$settings_health" "settings.health"
[[ "$(printf '%s' "$settings_health" | jq -r '.status')" == "ok" ]] || {
  warn "Dokploy tidak sehat atau credential tidak valid"; exit 1;
}
DOKPLOY_VERSION=$(api_get "settings.getDokployVersion" | jq -r '.')
note "akses API read-only berhasil; Dokploy $DOKPLOY_VERSION"

# ── 2. Application and dependency-aware health ─────────────────────────────
stage "Health Application dan dependency"
application=$(api_get "application.one" --data-urlencode "applicationId=$APPLICATION_ID")
api_check "$application" "application.one"
application_status=$(printf '%s' "$application" | jq -r '.applicationStatus // "unknown"')
[[ "$application_status" == "done" ]] || {
  warn "Application kandidat belum selesai dideploy (status: $application_status)"
  warn "Jalankan deployment kandidat pada hostname validasi, lalu ulangi wizard ini."
  exit 1
}
HEALTH_PATH="/api/health/ready"
health_command=$(printf '%s' "$application" | jq -r '.healthCheckSwarm.Test // [] | join(" ")')
[[ "$health_command" == *"$HEALTH_PATH"* ]] || {
  warn "healthCheckSwarm tidak menunjuk $HEALTH_PATH"; exit 1;
}
postgres=$(api_get "postgres.one" --data-urlencode "postgresId=$POSTGRES_ID")
api_check "$postgres" "postgres.one"
POSTGRES_STATUS=$(printf '%s' "$postgres" | jq -r '.applicationStatus // "unknown"')
[[ "$POSTGRES_STATUS" == "done" ]] || { warn "PostgreSQL baru tidak sehat: $POSTGRES_STATUS"; exit 1; }
LIVE_CODE=$(http_code "https://${VALIDATION_HOST}/api/health/live")
READY_CODE=$(http_code "https://${VALIDATION_HOST}/api/health/ready")
note "Application=$application_status; PostgreSQL=$POSTGRES_STATUS; live=$LIVE_CODE; ready=$READY_CODE"
[[ "$LIVE_CODE" == "200" && "$READY_CODE" == "200" ]] || {
  warn "health belum hijau; readiness memeriksa PostgreSQL dan permission volume upload"
  exit 1
}

# ── 3. Uptime Kuma notification path ───────────────────────────────────────
stage "Uptime Kuma — jalur notifikasi"
UPTIME_STATUS="pending"
UPTIME_KUMA_URL="pending"
UPTIME_NOTIFICATION_NAME="pending"
UPTIME_NOTIFICATION_TYPE="pending"
INCIDENT_RECIPIENT="pending"
UPTIME_MONITOR_NAME="pending"
UPTIME_MONITOR_REF="pending"
ALERT_TEST_REF="pending"
if confirm "Uptime Kuma sudah tersedia dan ingin dikonfigurasi sekarang?"; then
  ask UPTIME_KUMA_URL "URL dashboard Uptime Kuma:"
  [[ -n "$UPTIME_KUMA_URL" ]] || { warn "URL Uptime Kuma wajib diisi"; exit 1; }
  write_env UPTIME_KUMA_URL "$UPTIME_KUMA_URL"
  open_url "${UPTIME_KUMA_URL%/}/settings/notifications"
  step "Masuk ke Settings → Notifications → Set Up Notification."
  step "Pilih Notification Type yang memang diterima incident responder."
  step "Isi credential langsung di Uptime Kuma; jangan tempel token atau password ke wizard ini."
  step "Klik Test dan buktikan pesan benar-benar sampai ke penerima, lalu klik Save."
  ask UPTIME_NOTIFICATION_NAME "Friendly Name notifikasi di Kuma:"
  ask UPTIME_NOTIFICATION_TYPE "Notification Type (mis. Telegram/SMTP/Discord):"
  ask INCIDENT_RECIPIENT "Label penerima/tim insiden (tanpa alamat/token rahasia):"
  [[ -n "$UPTIME_NOTIFICATION_NAME" && -n "$UPTIME_NOTIFICATION_TYPE" && -n "$INCIDENT_RECIPIENT" ]] || {
    warn "nama, tipe notifikasi, dan label penerima wajib diisi"; exit 1;
  }
  confirm "Penerima benar-benar menerima pesan Test dari Uptime Kuma?" || {
    warn "jalur notifikasi belum terbukti"; exit 1;
  }
  UPTIME_STATUS="notification-ready"
  write_env UPTIME_NOTIFICATION_NAME "$UPTIME_NOTIFICATION_NAME"
  write_env UPTIME_NOTIFICATION_TYPE "$UPTIME_NOTIFICATION_TYPE"
  write_env INCIDENT_RECIPIENT "$INCIDENT_RECIPIENT"
else
  warn "Uptime Kuma dilewati sementara; release preflight akan tetap NO-GO."
  confirm "Lanjutkan pemeriksaan lain dan catat Uptime Kuma sebagai pending?" || {
    warn "preflight dibatalkan"; exit 1;
  }
  write_env UPTIME_STATUS "$UPTIME_STATUS"
fi

# ── 4. Persistent liveness monitor and safe failure/recovery test ──────────
stage "Uptime Kuma — monitor dan alert end-to-end"
if [[ "$UPTIME_STATUS" == "pending" ]]; then
  say "Stage ini dilewati karena Uptime Kuma belum tersedia."
  warn "Monitor liveness dan alert Down/Recovery tetap menjadi release blocker."
else
  open_url "${UPTIME_KUMA_URL%/}"
  UPTIME_MONITOR_NAME=$(_existing UPTIME_MONITOR_NAME || true)
  : "${UPTIME_MONITOR_NAME:=KAMMI ID production candidate liveness}"
  step "Klik Add New Monitor dan pilih Monitor Type: HTTP(s)."
  step "Friendly Name: $UPTIME_MONITOR_NAME"
  step "URL: https://${VALIDATION_HOST}/api/health/live"
  step "Set Heartbeat Interval 60 detik, Retries 2, dan Accepted Status Codes hanya 200-299."
  step "Aktifkan notifikasi '$UPTIME_NOTIFICATION_NAME', lalu Save."
  pause "Monitor liveness sudah Up — tekan Enter."
  say "Sekarang buat monitor sementara untuk membuktikan alert Down dan Recovery"
  say "tanpa menghentikan kandidat atau dependency production."
  failure_url="https://${VALIDATION_HOST}/api/health/preflight-alert-test"
  step "Add New Monitor → HTTP(s), URL: $failure_url"
  step "Set interval 20 detik, Retries 0, dan pasang notifikasi '$UPTIME_NOTIFICATION_NAME'."
  step "Save; tunggu status Down dan pastikan penerima menerima alert."
  step "Edit URL monitor sementara menjadi https://${VALIDATION_HOST}/api/health/live."
  step "Save; tunggu status Up dan pastikan penerima menerima recovery."
  confirm "Alert Down dan Recovery keduanya diterima?" || { warn "alert end-to-end gagal"; exit 1; }
  ask UPTIME_MONITOR_REF "Referensi/ID monitor liveness permanen:"
  ask ALERT_TEST_REF "Referensi bukti test Down + Recovery (tanpa secret):"
  [[ -n "$UPTIME_MONITOR_REF" && -n "$ALERT_TEST_REF" ]] || {
    warn "referensi monitor dan alert test wajib diisi"; exit 1;
  }
  if confirm "Hapus monitor sementara setelah bukti tersimpan?"; then
    step "Buka monitor sementara → Delete → konfirmasi penghapusan."
    pause "Monitor sementara sudah dihapus — tekan Enter."
  else
    step "Pause monitor sementara agar tidak mengirim alert palsu berulang."
    pause "Monitor sementara sudah dipause — tekan Enter."
  fi
  UPTIME_STATUS="ready"
  write_env UPTIME_STATUS "$UPTIME_STATUS"
  write_env UPTIME_MONITOR_NAME "$UPTIME_MONITOR_NAME"
  write_env UPTIME_MONITOR_REF "$UPTIME_MONITOR_REF"
  write_env ALERT_TEST_REF "$ALERT_TEST_REF"
fi

# ── 5. Application/PostgreSQL logs and secret-redaction scan ───────────────
stage "Akses log dan redaksi credential"
open_url "${DOKPLOY_PROD_URL%/}/dashboard/project"
step "Application kandidat → Logs: pastikan incident responder dapat membaca runtime log."
step "PostgreSQL baru → Logs: pastikan responder yang sama dapat membaca log database."
http_code "https://${VALIDATION_HOST}/api/health/live" >/dev/null
app_logs_json=$(api_get "application.readLogs" \
  --data-urlencode "applicationId=$APPLICATION_ID" --data-urlencode "tail=200")
pg_logs_json=$(api_get "postgres.readLogs" \
  --data-urlencode "postgresId=$POSTGRES_ID" --data-urlencode "tail=200")
api_check "$app_logs_json" "application.readLogs"
api_check "$pg_logs_json" "postgres.readLogs"
app_logs=$(printf '%s' "$app_logs_json" | jq -r 'if type == "string" then . else tostring end')
pg_logs=$(printf '%s' "$pg_logs_json" | jq -r 'if type == "string" then . else tostring end')
all_logs="$app_logs
$pg_logs"
leak_count=0
for secret_key in DATABASE_PASSWORD DOKPLOY_PROD_API_KEY GHCR_PAT API_CO_ID_TOKEN \
  CACHE_REVALIDATE_SECRET RUSTFS_SECRET_KEY; do
  secret_value=$(value_from_file "$PROVISION_ENV_FILE" "$secret_key" || \
    value_from_file "$ROOT_ENV_FILE" "$secret_key" || true)
  if [[ ${#secret_value} -ge 8 ]] && grep -Fq -- "$secret_value" <<< "$all_logs"; then
    leak_count=$((leak_count + 1))
  fi
done
if grep -Eqi 'postgres(ql)?://[^[:space:]]+:[^@[:space:]]+@|authorization:[[:space:]]*bearer[[:space:]]+[^[:space:]]+' \
  <<< "$all_logs"; then
  leak_count=$((leak_count + 1))
fi
unset app_logs pg_logs all_logs secret_value
if (( leak_count > 0 )); then
  warn "$leak_count pola credential ditemukan pada log; isi sengaja tidak ditampilkan"
  warn "STOP: batasi akses, redaksi sumber log, dan rotasi credential bila benar-benar bocor."
  exit 1
fi
LOG_SCAN_STATUS="pass (200 baris terakhir masing-masing, tanpa credential dikenal)"
note "log Application dan PostgreSQL terbaca; scan credential lulus"
ask INCIDENT_RESPONDER_ROLE "Peran/akun responder yang berhasil membuka kedua log:"
[[ -n "$INCIDENT_RESPONDER_ROLE" ]] || { warn "peran responder wajib diisi"; exit 1; }
confirm "Responder dapat mendiagnosis log tanpa akses credential mentah?" || {
  warn "akses incident responder belum siap"; exit 1;
}
write_env INCIDENT_RESPONDER_ROLE "$INCIDENT_RESPONDER_ROLE"

# ── 6. Public DNS and TLS ──────────────────────────────────────────────────
stage "DNS dan TLS production"
ask APEX_HOST "Hostname apex (default kammi.id):"; : "${APEX_HOST:=kammi.id}"
ask WWW_HOST "Hostname www (default www.kammi.id):"; : "${WWW_HOST:=www.kammi.id}"
ask TENANT_HOST "Satu hostname tenant nyata (bukan candidate/assets):"
ask ASSETS_HOST "Hostname aset legacy (default assets.kammi.id):"; : "${ASSETS_HOST:=assets.kammi.id}"
[[ -n "$TENANT_HOST" && "$TENANT_HOST" != "$VALIDATION_HOST" && "$TENANT_HOST" != "$ASSETS_HOST" ]] || {
  warn "tenant host harus hostname Struktur nyata"; exit 1;
}
for key in APEX_HOST WWW_HOST TENANT_HOST ASSETS_HOST; do write_env "$key" "${!key}"; done

APEX_DNS=$(dns_addresses "$APEX_HOST")
WWW_DNS=$(dns_addresses "$WWW_HOST")
TENANT_DNS=$(dns_addresses "$TENANT_HOST")
ASSETS_DNS=$(dns_addresses "$ASSETS_HOST")
for item in "apex:$APEX_DNS" "www:$WWW_DNS" "tenant:$TENANT_DNS" "assets:$ASSETS_DNS"; do
  [[ -n "${item#*:}" ]] || { warn "DNS ${item%%:*} kosong"; exit 1; }
  note "$item"
done
APEX_TLS=$(tls_expiry "$APEX_HOST") || { warn "TLS apex tidak valid atau kedaluwarsa <7 hari"; exit 1; }
WWW_TLS=$(tls_expiry "$WWW_HOST") || { warn "TLS www tidak valid atau kedaluwarsa <7 hari"; exit 1; }
TENANT_TLS=$(tls_expiry "$TENANT_HOST") || { warn "TLS tenant/wildcard tidak valid atau kedaluwarsa <7 hari"; exit 1; }
ASSETS_TLS=$(tls_expiry "$ASSETS_HOST") || { warn "TLS assets tidak valid atau kedaluwarsa <7 hari"; exit 1; }
note "TLS valid ≥7 hari: apex, www, tenant, assets"

# ── 7. End-to-end Host preservation ────────────────────────────────────────
stage "Reverse proxy mempertahankan header Host"
APEX_BODY="$TMP_DIR/apex.body"
TENANT_BODY="$TMP_DIR/tenant.body"
APEX_META="$TMP_DIR/apex.meta"
TENANT_META="$TMP_DIR/tenant.meta"
curl -sS -L --max-time 30 -o "$APEX_BODY" -w '%{http_code}\n%{url_effective}\n' \
  "https://${APEX_HOST}/" > "$APEX_META"
curl -sS -L --max-time 30 -o "$TENANT_BODY" -w '%{http_code}\n%{url_effective}\n' \
  "https://${TENANT_HOST}/" > "$TENANT_META"
APEX_PAGE_CODE=$(sed -n '1p' "$APEX_META")
APEX_EFFECTIVE_URL=$(sed -n '2p' "$APEX_META")
TENANT_PAGE_CODE=$(sed -n '1p' "$TENANT_META")
TENANT_EFFECTIVE_URL=$(sed -n '2p' "$TENANT_META")
APEX_BODY_HASH=$(sha256_file "$APEX_BODY")
TENANT_BODY_HASH=$(sha256_file "$TENANT_BODY")
note "apex: HTTP $APEX_PAGE_CODE → $APEX_EFFECTIVE_URL"
note "tenant: HTTP $TENANT_PAGE_CODE → $TENANT_EFFECTIVE_URL"
if [[ "$APEX_BODY_HASH" == "$TENANT_BODY_HASH" ]]; then
  warn "body apex dan tenant identik; pemeriksaan visual wajib menjelaskan hasil ini"
fi
open_url "https://${APEX_HOST}/"
open_url "https://${TENANT_HOST}/"
confirm "Apex menampilkan situs apex dan tenant menampilkan Struktur yang tepat?" || {
  warn "Host tidak terbukti dipertahankan oleh reverse proxy"; exit 1;
}

# ── 8. Host ownership, duplicates, and exact RustFS precedence ──────────────
stage "Ownership router dan exact route RustFS"
projects=$(api_get "project.all")
api_check "$projects" "project.all"
ROUTES_FILE="$TMP_DIR/routes.jsonl"
collect_routes "$projects"
WILDCARD_HOST="*.${APEX_HOST}"
for required_host in "$APEX_HOST" "$WWW_HOST" "$WILDCARD_HOST" "$ASSETS_HOST"; do
  count=$(route_count "$required_host")
  if [[ "$count" != "1" ]]; then
    warn "Host rule '$required_host' harus punya tepat satu owner; ditemukan $count"
    warn "Perbaiki di Dokploy tanpa memasang rule yang sama pada dua Application, lalu ulangi."
    exit 1
  fi
done
candidate_production_routes=$(jq -s --arg id "$APPLICATION_ID" \
  --arg apex "$APEX_HOST" --arg www "$WWW_HOST" --arg wildcard "$WILDCARD_HOST" \
  '[.[] | select(.id == $id and (.host == $apex or .host == $www or .host == $wildcard))] | length' \
  "$ROUTES_FILE")
[[ "$candidate_production_routes" == "0" ]] || {
  warn "Application kandidat sudah mengambil Host production sebelum cutover"; exit 1;
}
duplicate_hosts=$(jq -s -r \
  'sort_by(.host) | group_by(.host) |
    map(select((unique_by([.kind,.id]) | length) > 1) | .[0].host) | join(",")' \
  "$ROUTES_FILE")
[[ -z "$duplicate_hosts" ]] || { warn "duplicate Host rule: $duplicate_hosts"; exit 1; }
assets_is_rustfs=$(jq -s --arg host "$ASSETS_HOST" \
  '[.[] | select(.host == $host and .kind == "compose" and
    ((.serviceName // "") | ascii_downcase) == "rustfs")] | length' \
  "$ROUTES_FILE")
[[ "$assets_is_rustfs" == "1" ]] || {
  warn "$ASSETS_HOST tidak terbukti menuju Compose service rustfs"; exit 1;
}
APEX_ROUTE_OWNER=$(route_summary "$APEX_HOST")
WWW_ROUTE_OWNER=$(route_summary "$WWW_HOST")
WILDCARD_ROUTE_OWNER=$(route_summary "$WILDCARD_HOST")
ASSETS_ROUTE_OWNER=$(route_summary "$ASSETS_HOST")
note "assets exact owner: $ASSETS_ROUTE_OWNER"
ASSETS_CODE=$(http_code "https://${ASSETS_HOST}/")
[[ "$ASSETS_CODE" != "000" ]] || { warn "exact route assets tidak dapat dijangkau"; exit 1; }
note "exact route assets menjawab HTTP $ASSETS_CODE dan tidak dimiliki wildcard Application"

# ── 9. Host capacity, networks, DB sessions, and backup schedules ──────────
stage "Kapasitas, network, sesi PostgreSQL, dan backup"
load_value SSH_HOST SSH_HOST
load_value SSH_KEY SSH_KEY
load_value DOCKER_NETWORK DOCKER_NETWORK
load_value OLD_PG_CONTAINER OLD_PG_CONTAINER
load_value NEW_PG_CONTAINER NEW_PG_CONTAINER
load_value OLD_DB_NAME OLD_DB_NAME
load_value OLD_DB_USER OLD_DB_USER
load_value NEW_DB_NAME NEW_DB_NAME DATABASE_NAME
load_value NEW_DB_USER NEW_DB_USER DATABASE_USER
load_value POSTGRES_APP_NAME POSTGRES_APP_NAME
APPLICATION_APP_NAME=$(printf '%s' "$application" | jq -r '.appName // ""')
if [[ -z "$SSH_HOST" ]]; then ask SSH_HOST "SSH host production (user@host):"; fi
if [[ -z "$SSH_KEY" ]]; then ask SSH_KEY "Path absolut identity file SSH (kosong bila ssh-agent):"; fi
if [[ -z "$DOCKER_NETWORK" ]]; then ask DOCKER_NETWORK "Docker network (default dokploy-network):"; : "${DOCKER_NETWORK:=dokploy-network}"; fi
for key in SSH_HOST SSH_KEY DOCKER_NETWORK; do write_env "$key" "${!key}"; done
ssh_prod "true" >/dev/null || { warn "akses SSH production gagal"; exit 1; }
ask MIN_FREE_DISK_GB "Minimum free disk yang disetujui untuk release, GiB:"
[[ "$MIN_FREE_DISK_GB" =~ ^[0-9]+$ ]] || { warn "minimum disk harus bilangan bulat GiB"; exit 1; }
write_env MIN_FREE_DISK_GB "$MIN_FREE_DISK_GB"
free_disk_kb=$(ssh_prod "df -Pk /var/lib/docker | awk 'NR==2 {print \$4}'")
[[ "$free_disk_kb" =~ ^[0-9]+$ ]] || { warn "kapasitas /var/lib/docker tidak terbaca"; exit 1; }
FREE_DISK_GB=$((free_disk_kb / 1024 / 1024))
(( FREE_DISK_GB >= MIN_FREE_DISK_GB )) || {
  warn "free disk ${FREE_DISK_GB} GiB di bawah minimum ${MIN_FREE_DISK_GB} GiB"; exit 1;
}
network_exists=$(ssh_prod "docker network inspect '$DOCKER_NETWORK' --format '{{.Name}}'" 2>/dev/null || true)
[[ "$network_exists" == "$DOCKER_NETWORK" ]] || { warn "network '$DOCKER_NETWORK' tidak ditemukan"; exit 1; }
if [[ -z "$NEW_PG_CONTAINER" && -n "$POSTGRES_APP_NAME" ]]; then
  NEW_PG_CONTAINER=$(ssh_prod "docker ps --filter name='$POSTGRES_APP_NAME' --format '{{.Names}}' | head -n 1")
fi
for key in OLD_PG_CONTAINER NEW_PG_CONTAINER OLD_DB_NAME OLD_DB_USER NEW_DB_NAME NEW_DB_USER; do
  if [[ -z "${!key:-}" ]]; then ask "$key" "$key:"; fi
  [[ "${!key}" =~ ^[A-Za-z0-9_.-]+$ ]] || { warn "$key berisi karakter tak aman"; exit 1; }
  write_env "$key" "${!key}"
done
[[ "$APPLICATION_APP_NAME" =~ ^[A-Za-z0-9_.-]+$ ]] || {
  warn "appName Application tidak valid: '$APPLICATION_APP_NAME'"; exit 1;
}
APP_CONTAINER=$(ssh_prod "docker ps --filter name='$APPLICATION_APP_NAME' --format '{{.Names}}' | head -n 1")
[[ -n "$APP_CONTAINER" ]] || { warn "container Application kandidat tidak ditemukan"; exit 1; }
APP_NETWORKS=$(ssh_prod "docker inspect '$APP_CONTAINER' --format '{{range \$key, \$value := .NetworkSettings.Networks}}{{\$key}} {{end}}'")
NEW_PG_NETWORKS=$(ssh_prod "docker inspect '$NEW_PG_CONTAINER' --format '{{range \$key, \$value := .NetworkSettings.Networks}}{{\$key}} {{end}}'")
[[ " $APP_NETWORKS " == *" $DOCKER_NETWORK "* ]] || {
  warn "Application tidak terpasang ke network '$DOCKER_NETWORK': $APP_NETWORKS"; exit 1;
}
[[ " $NEW_PG_NETWORKS " == *" $DOCKER_NETWORK "* ]] || {
  warn "PostgreSQL baru tidak terpasang ke network '$DOCKER_NETWORK': $NEW_PG_NETWORKS"; exit 1;
}
OLD_DB_SESSIONS=$(ssh_prod "docker exec '$OLD_PG_CONTAINER' psql -t -A -U '$OLD_DB_USER' -d '$OLD_DB_NAME' -c \"select count(*) from pg_stat_activity where datname=current_database() and backend_type='client backend';\"" | tr -d '[:space:]')
NEW_DB_SESSIONS=$(ssh_prod "docker exec '$NEW_PG_CONTAINER' psql -t -A -U '$NEW_DB_USER' -d '$NEW_DB_NAME' -c \"select count(*) from pg_stat_activity where datname=current_database() and backend_type='client backend';\"" | tr -d '[:space:]')
[[ "$OLD_DB_SESSIONS" =~ ^[0-9]+$ && "$NEW_DB_SESSIONS" =~ ^[0-9]+$ ]] || {
  warn "sesi PostgreSQL tidak dapat dibaca"; exit 1;
}
note "free disk: $FREE_DISK_GB GiB; network: $DOCKER_NETWORK; sessions old/new: $OLD_DB_SESSIONS/$NEW_DB_SESSIONS"
POSTGRES_BACKUP_COUNT=$(printf '%s' "$postgres" | jq '[.backups[]? | select(.enabled == true)] | length')
POSTGRES_BACKUP_DESTINATION_ID=$(printf '%s' "$postgres" | jq -r \
  '[.backups[]? | select(.enabled == true) | .destinationId] | unique | .[0] // ""')
BACKUP_DESTINATION_NAME=$(printf '%s' "$postgres" | jq -r \
  '[.backups[]? | select(.enabled == true) | .destination.name] | unique | .[0] // "unknown"')
volume_backups=$(api_get "volumeBackups.list" --data-urlencode "id=$APPLICATION_ID" \
  --data-urlencode "volumeBackupType=application")
api_check "$volume_backups" "volumeBackups.list"
VOLUME_BACKUP_COUNT=$(printf '%s' "$volume_backups" | jq '[.[] | select(.enabled == true and .turnOff != true)] | length')
VOLUME_BACKUP_DESTINATION_IDS=$(printf '%s' "$volume_backups" | jq -r \
  '[.[] | select(.enabled == true and .turnOff != true) | .destinationId] | unique | join(",")')
[[ "$POSTGRES_BACKUP_COUNT" -ge 1 && "$VOLUME_BACKUP_COUNT" -ge 2 ]] || {
  warn "jadwal backup aktif kurang: PostgreSQL=$POSTGRES_BACKUP_COUNT volume=$VOLUME_BACKUP_COUNT"; exit 1;
}
[[ -n "$POSTGRES_BACKUP_DESTINATION_ID" && "$VOLUME_BACKUP_DESTINATION_IDS" == "$POSTGRES_BACKUP_DESTINATION_ID" ]] || {
  warn "PostgreSQL dan volume tidak memakai satu backup destination yang sama"; exit 1;
}
printf '%s' "$postgres" | jq -r '.backups[]? | "  PostgreSQL: cron=\(.schedule) keep=\(.keepLatestCount) destination=\(.destination.name)"'
printf '%s' "$volume_backups" | jq -r '.[] | "  volume \(.volumeName): cron=\(.cronExpression) keep=\(.keepLatestCount) destinationId=\(.destinationId)"'
warn "Status schedule bukan bukti restore. Restore viability tetap acceptance gate wizard-07."
step "Dokploy → PostgreSQL/Volumes → Backups: periksa riwayat job terbaru dan error."
confirm "Jadwal/retensi/destination backup sesuai dan tidak ada job gagal?" || {
  warn "backup schedule belum sehat"; exit 1;
}

# ── 10. Evidence and go/no-go record ───────────────────────────────────────
stage "Catat bukti dan keputusan preflight"
say "Record hanya memuat hostname, resource ID, status, count, dan referensi bukti."
say "Raw log, DSN, token, password, dan notification credential tidak pernah ditulis."
ask PREFLIGHT_DECISION_REF "Referensi keputusan/gate preflight (mis. nama catatan + timestamp):"
[[ -n "$PREFLIGHT_DECISION_REF" ]] || { warn "referensi keputusan wajib diisi"; exit 1; }
if [[ "$UPTIME_STATUS" != "ready" ]]; then
  PREFLIGHT_STATUS="NO-GO — Uptime Kuma pending"
  PREFLIGHT_DECISION_REF="$PREFLIGHT_STATUS; $PREFLIGHT_DECISION_REF"
  write_env PREFLIGHT_DECISION_REF "$PREFLIGHT_DECISION_REF"
  record_preflight
  warn "Preflight belum lengkap: Uptime Kuma dan alert end-to-end masih pending."
  say "Pemeriksaan lain sudah dicatat. Deploy Uptime Kuma lalu jalankan ulang wizard ini."
  exit 2
fi
confirm "Semua bukti di atas akurat dan preflight dinyatakan GO?" || {
  warn "keputusan NO-GO; record sukses tidak ditulis"; exit 1;
}
PREFLIGHT_STATUS="GO"
write_env PREFLIGHT_DECISION_REF "$PREFLIGHT_DECISION_REF"
record_preflight
say "Tiket 05 dapat ditutup setelah record ini ditinjau deployment lead dan product/data owner."
say "Jangan commit preflight.local.env atau preflight-record.local.md."

finish
