#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Ticket 04: provision the new Dokploy production project — driven by the
# Dokploy API (v0.30.x), not by clicking the panel. Procedure names and body
# schemas were read off the official source at tag v0.30.2 and verified
# against a live instance; they are not guesses.
#
# This script does NOT deploy the Application, does not migrate, does not take
# production Host rules, and does not touch the legacy stack. It DOES deploy
# the new PostgreSQL container, because ticket 07 restores into a running one.
#
# State lives in provisioning.local.env (gitignored via *.local.env, mode 600)
# so re-runs are idempotent and ticket 07 can read the new DSN. The handoff
# record (provisioning-record.local.md) stays free of secrets.

TOTAL_STAGES=13
TOTAL_MINUTES=70

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
RECORD_FILE="${RECORD_FILE:-$SCRIPT_DIR/provisioning-record.local.md}"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/provisioning.local.env}"

umask 077
touch "$ENV_FILE" && chmod 600 "$ENV_FILE"

# ── Thin HTTP client for the Dokploy API ────────────────────────────────────
# Base URL & auth: <host>/api/<router>.<procedure>, header x-api-key.
api_get() {
  local proc="$1"; shift
  curl -sS -G "${DOKPLOY_PROD_URL%/}/api/$proc" "$@" \
    -H "x-api-key: $DOKPLOY_PROD_API_KEY" --max-time 60
}
api_post() {
  curl -sS -X POST "${DOKPLOY_PROD_URL%/}/api/$1" \
    -H "x-api-key: $DOKPLOY_PROD_API_KEY" -H 'Content-Type: application/json' \
    -d "$2" --max-time 180
}

# api_check RESPONSE "label" — abort on a tRPC error payload.
api_check() {
  local err; err=$(printf '%s' "$1" | jq -r 'if type=="object" and .code then (.message // .code) else empty end' 2>/dev/null || true)
  if [[ -n "$err" ]]; then warn "$2 gagal: $err"; exit 1; fi
}

# state KEY — value already saved in ENV_FILE, empty when absent.
state() { _existing "$1" || true; }

# poll_status PROC ID_FIELD ID — wait for applicationStatus to settle (5 min).
poll_status() {
  local proc="$1" id_field="$2" id_value="$3" waited=0 status=""
  while (( waited < 300 )); do
    status=$(api_get "$proc" --data-urlencode "$id_field=$id_value" | jq -r '.applicationStatus // "unknown"')
    case "$status" in
      done)  printf '\n'; note "status: done"; return 0 ;;
      error) printf '\n'; warn "status: error"; return 1 ;;
      *)     printf '.'; sleep 5; waited=$((waited + 5)) ;;
    esac
  done
  printf '\n'; warn "timeout menunggu status (terakhir: $status)"; return 1
}

# server_arg — jq fragment adding serverId when a remote server was chosen.
server_json() {
  if [[ -n "${SERVER_ID:-}" ]]; then jq -n --arg s "$SERVER_ID" '{serverId:$s}'; else echo '{}'; fi
}

record_provisioning() {
  {
    printf '\n## Provisioning %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf -- '- Dokploy console: %s\n' "$DOKPLOY_PROD_URL"
    printf -- '- Target server: %s\n' "${SERVER_LABEL:-host Dokploy itu sendiri}"
    printf -- '- Project: %s (`%s`)\n' "$PROJECT_NAME" "$PROJECT_ID"
    printf -- '- Environment: %s (`%s`)\n' "$ENVIRONMENT_NAME" "$ENVIRONMENT_ID"
    printf -- '- PostgreSQL: %s (`%s`); appName `%s`; image `%s`; database `%s`; user `%s`\n' \
      "$POSTGRES_NAME" "$POSTGRES_ID" "$POSTGRES_APP_NAME" "$POSTGRES_IMAGE" "$DATABASE_NAME" "$DATABASE_USER"
    printf -- '- Application: %s (`%s`); appName `%s`; image `%s`; replicas: %s; undeployed\n' \
      "$APPLICATION_NAME" "$APPLICATION_ID" "$APPLICATION_APP_NAME" "$IMAGE_REFERENCE" "$APPLICATION_REPLICAS"
    printf -- '- Upload volume: `%s` → `/data/uploads`; ownership evidence: %s\n' \
      "$UPLOAD_VOLUME" "$UPLOAD_OWNERSHIP_EVIDENCE"
    printf -- '- Cache volume: `%s` → `/app/.next/cache`; ownership evidence: %s\n' \
      "$CACHE_VOLUME" "$CACHE_OWNERSHIP_EVIDENCE"
    printf -- '- Validation hostname: `%s` (port 3000, https, letsencrypt)\n' "$VALIDATION_HOST"
    printf -- '- Health check: `%s` via healthCheckSwarm\n' "/api/health/ready"
    printf -- '- PostgreSQL backup: %s; retention: %s; destination: %s\n' \
      "$POSTGRES_BACKUP_SCHEDULE" "$POSTGRES_BACKUP_RETENTION" "$BACKUP_DESTINATION"
    printf -- '- Volume backups: %s; retention: %s; destination: %s\n' \
      "$VOLUME_BACKUP_SCHEDULE" "$VOLUME_BACKUP_RETENTION" "$BACKUP_DESTINATION"
    printf -- '- Secret values, DSNs, API keys, and passwords intentionally omitted.\n'
  } >> "$RECORD_FILE"
  note "evidence appended to $RECORD_FILE"
}

cd "$REPO_ROOT"
banner "Provision project Dokploy production baru (via API)"

# ── 1. Prasyarat & koneksi ──────────────────────────────────────────────────
stage "Prasyarat dan koneksi API" 4
warn "Wizard ini hanya menyiapkan project terisolasi. Jangan mengubah, menghentikan,"
warn "atau menambah Host rule pada project production lama."
for tool in curl jq openssl; do
  command -v "$tool" >/dev/null 2>&1 || { warn "$tool tidak ditemukan — pasang dulu"; exit 1; }
done
ask DOKPLOY_PROD_URL "Dokploy production console URL:"
[[ -n "$DOKPLOY_PROD_URL" ]] || { warn "URL wajib diisi"; exit 1; }
ask_secret DOKPLOY_PROD_API_KEY "Dokploy production API key (x-api-key):"
[[ -n "$DOKPLOY_PROD_API_KEY" ]] || { warn "API key wajib diisi"; exit 1; }
health=$(api_get "settings.health" | jq -r '.status // "unreachable"')
[[ "$health" == "ok" ]] || { warn "settings.health tidak sehat: $health — cek URL, API key, dan jaringan"; exit 1; }
note "terhubung ke $DOKPLOY_PROD_URL (Dokploy $(api_get settings.getDokployVersion | jq -r '.'))"
write_env DOKPLOY_PROD_URL "$DOKPLOY_PROD_URL"
write_env DOKPLOY_PROD_API_KEY "$DOKPLOY_PROD_API_KEY"
note "state file: $ENV_FILE (mode 600, tercakup *.local.env di .gitignore)"

# ── 2. Server tujuan ────────────────────────────────────────────────────────
stage "Server production tujuan" 3
servers=$(api_get "server.all")
api_check "$servers" "server.all"
if [[ "$(printf '%s' "$servers" | jq 'length')" == "0" ]]; then
  note "tidak ada remote server terdaftar — resource dibuat di host Dokploy ini sendiri"
  SERVER_ID=""
  SERVER_LABEL="host Dokploy itu sendiri"
else
  printf '%s' "$servers" | jq -r '.[] | "  - \(.name)  ip=\(.ipAddress)  serverId=\(.serverId)"'
  say "Kosongkan untuk memakai host Dokploy itu sendiri."
  ask SERVER_ID "serverId production yang disepakati:"
  if [[ -n "$SERVER_ID" ]]; then
    SERVER_LABEL=$(printf '%s' "$servers" | jq -r --arg s "$SERVER_ID" '.[] | select(.serverId==$s) | .name')
    [[ -n "$SERVER_LABEL" ]] || { warn "serverId tidak ada di daftar di atas"; exit 1; }
  else
    SERVER_LABEL="host Dokploy itu sendiri"
  fi
fi
write_env SERVER_ID "$SERVER_ID"
note "target: $SERVER_LABEL"

# ── 3. Inventory volume & nama unik ─────────────────────────────────────────
stage "Inventory volume host dan nama unik" 5
say "Named volume tidak dinamespace per-project (ADR 0015) — nama harus unik di host."
volumes=$(api_get "dockerVolume.getVolumes" ${SERVER_ID:+--data-urlencode "serverId=$SERVER_ID"})
api_check "$volumes" "dockerVolume.getVolumes"
vol_names=$(printf '%s' "$volumes" | jq -r '.[].Name')
note "$(printf '%s' "$vol_names" | grep -c . || true) named volume terdeteksi di host"
pick_unique_volume() {
  local key="$1" prompt="$2" value="" reserved
  # Nama yang sudah direservasi run sebelumnya dikecualikan dari cek keunikan:
  # stage 9 menyuruh operator `docker volume create`, jadi pada re-run nama itu
  # memang sudah ada di host — dan itu milik kita, bukan volume project lama.
  reserved=$(state "$key")
  while :; do
    ask "$key" "$prompt"
    value="${!key}"
    if [[ -z "$value" ]]; then warn "nama volume wajib diisi"; continue; fi
    if [[ -n "$reserved" && "$value" == "$reserved" ]]; then
      note "'$value' direservasi wizard ini di run sebelumnya — cek keunikan dilewati"
      break
    fi
    if grep -qxF "$value" <<<"$vol_names"; then
      warn "'$value' SUDAH ADA di host — pilih nama lain, jangan pakai volume project lama"
      continue
    fi
    break
  done
  write_env "$key" "$value"
}
pick_unique_volume UPLOAD_VOLUME "Nama named-volume upload (harus belum ada di host):"
pick_unique_volume CACHE_VOLUME "Nama named-volume cache Next.js (harus belum ada di host):"

# ── 4. Project & environment ────────────────────────────────────────────────
stage "Project dan environment baru" 5
PROJECT_ID=$(state PROJECT_ID)
ENVIRONMENT_ID=$(state ENVIRONMENT_ID)
PROJECT_NAME=$(state PROJECT_NAME)
ENVIRONMENT_NAME=$(state ENVIRONMENT_NAME)
if [[ -n "$PROJECT_ID" && -n "$ENVIRONMENT_ID" ]]; then
  note "sudah ada dari run sebelumnya: project=$PROJECT_ID environment=$ENVIRONMENT_ID"
else
  ask PROJECT_NAME "Nama project production baru:"
  [[ -n "$PROJECT_NAME" ]] || { warn "nama project wajib diisi"; exit 1; }
  say "project.create otomatis membuat satu environment 'production' sekaligus."
  confirm "Buat project '$PROJECT_NAME' sekarang?" || { warn "dibatalkan"; exit 1; }
  resp=$(api_post "project.create" "$(jq -n --arg name "$PROJECT_NAME" '{name:$name}')")
  api_check "$resp" "project.create"
  PROJECT_ID=$(printf '%s' "$resp" | jq -r '.project.projectId')
  ENVIRONMENT_ID=$(printf '%s' "$resp" | jq -r '.environment.environmentId')
  ENVIRONMENT_NAME="production"
  say "Kosongkan untuk memakai environment 'production' bawaan."
  ask ENVIRONMENT_NAME_INPUT "Nama environment lain (opsional):"
  if [[ -n "${ENVIRONMENT_NAME_INPUT:-}" && "$ENVIRONMENT_NAME_INPUT" != "production" ]]; then
    resp=$(api_post "environment.create" "$(jq -n --arg n "$ENVIRONMENT_NAME_INPUT" --arg p "$PROJECT_ID" \
      '{name:$n, projectId:$p}')")
    api_check "$resp" "environment.create"
    ENVIRONMENT_ID=$(printf '%s' "$resp" | jq -r '.environmentId')
    ENVIRONMENT_NAME="$ENVIRONMENT_NAME_INPUT"
  fi
  write_env PROJECT_NAME "$PROJECT_NAME"
  write_env PROJECT_ID "$PROJECT_ID"
  write_env ENVIRONMENT_NAME "$ENVIRONMENT_NAME"
  write_env ENVIRONMENT_ID "$ENVIRONMENT_ID"
fi
note "project=$PROJECT_ID environment=$ENVIRONMENT_ID"

# ── 5. Kredensial registry GHCR ─────────────────────────────────────────────
stage "Kredensial registry GHCR" 4
REGISTRY_ID=$(state REGISTRY_ID)
GHCR_USERNAME=$(state GHCR_USERNAME)
if [[ -n "$REGISTRY_ID" ]]; then
  note "sudah ada: registry=$REGISTRY_ID"
else
  registries=$(api_get "registry.all")
  api_check "$registries" "registry.all"
  existing=$(printf '%s' "$registries" | jq -r '[.[] | select(.registryUrl=="ghcr.io")][0] // empty')
  if [[ -n "$existing" ]]; then
    REGISTRY_ID=$(printf '%s' "$existing" | jq -r '.registryId')
    GHCR_USERNAME=$(printf '%s' "$existing" | jq -r '.username')
    note "memakai kredensial GHCR yang sudah ada: $(printf '%s' "$existing" | jq -r '.registryName') ($GHCR_USERNAME)"
  fi
fi
[[ -n "$GHCR_USERNAME" ]] || ask GHCR_USERNAME "Username GitHub pemilik PAT GHCR:"
[[ -n "$GHCR_USERNAME" ]] || { warn "username GHCR wajib diisi"; exit 1; }
note "saveDockerProvider selalu butuh PAT-nya lagi — wizard tidak membaca balik password dari registry.all."
ask_secret GHCR_PAT "PAT GHCR (read:packages) untuk menarik image production:"
[[ -n "$GHCR_PAT" ]] || { warn "PAT wajib diisi"; exit 1; }
write_env GHCR_USERNAME "$GHCR_USERNAME"
write_env GHCR_PAT "$GHCR_PAT"
if [[ -z "$REGISTRY_ID" ]]; then
  resp=$(api_post "registry.create" "$(jq -n --arg u "$GHCR_USERNAME" --arg p "$GHCR_PAT" \
    '{registryName:"ghcr", username:$u, password:$p, registryUrl:"ghcr.io", registryType:"cloud", imagePrefix:null}')")
  api_check "$resp" "registry.create"
  REGISTRY_ID=$(printf '%s' "$resp" | jq -r '.registryId')
fi
write_env REGISTRY_ID "$REGISTRY_ID"
note "registry=$REGISTRY_ID"

# ── 6. PostgreSQL terisolasi ────────────────────────────────────────────────
stage "PostgreSQL production terisolasi" 8
POSTGRES_ID=$(state POSTGRES_ID)
POSTGRES_NAME=$(state POSTGRES_NAME)
POSTGRES_IMAGE=$(state POSTGRES_IMAGE)
DATABASE_NAME=$(state DATABASE_NAME)
DATABASE_USER=$(state DATABASE_USER)
DATABASE_PASSWORD=$(state DATABASE_PASSWORD)
if [[ -n "$POSTGRES_ID" ]]; then
  note "sudah ada: postgres=$POSTGRES_ID"
else
  ask POSTGRES_NAME "Nama PostgreSQL production:"
  ask DATABASE_NAME "Nama database baru:"
  ask DATABASE_USER "User database baru:"
  say "Versi harus sama dengan production lama supaya pg_dump -Fc bisa direstore (tiket 07)."
  ask POSTGRES_IMAGE "Image PostgreSQL (default postgres:18.3):"
  : "${POSTGRES_IMAGE:=postgres:18.3}"
  DATABASE_PASSWORD=$(openssl rand -hex 24)
  note "password database digenerate lokal (openssl rand) — tidak pernah masuk ke record atau tiket"
  confirm "Buat PostgreSQL '$POSTGRES_NAME' ($POSTGRES_IMAGE) di environment ini?" || { warn "dibatalkan"; exit 1; }
  resp=$(api_post "postgres.create" "$(server_json | jq \
    --arg n "$POSTGRES_NAME" --arg db "$DATABASE_NAME" --arg u "$DATABASE_USER" \
    --arg p "$DATABASE_PASSWORD" --arg img "$POSTGRES_IMAGE" --arg env "$ENVIRONMENT_ID" \
    '. + {name:$n, appName:$n, databaseName:$db, databaseUser:$u, databasePassword:$p, dockerImage:$img, environmentId:$env}')")
  api_check "$resp" "postgres.create"
  POSTGRES_ID=$(printf '%s' "$resp" | jq -r '.postgresId')
  write_env POSTGRES_NAME "$POSTGRES_NAME"
  write_env POSTGRES_IMAGE "$POSTGRES_IMAGE"
  write_env POSTGRES_ID "$POSTGRES_ID"
  write_env DATABASE_NAME "$DATABASE_NAME"
  write_env DATABASE_USER "$DATABASE_USER"
  write_env DATABASE_PASSWORD "$DATABASE_PASSWORD"
fi
# appName selalu dibaca balik: Dokploy menambahkan suffix acak sendiri, dan
# appName inilah hostname jaringan yang dipakai DATABASE_URL.
POSTGRES_APP_NAME=$(api_get "postgres.one" --data-urlencode "postgresId=$POSTGRES_ID" | jq -r '.appName')
[[ -n "$POSTGRES_APP_NAME" && "$POSTGRES_APP_NAME" != "null" ]] || { warn "gagal membaca appName Postgres"; exit 1; }
write_env POSTGRES_APP_NAME "$POSTGRES_APP_NAME"
note "appName Postgres sebenarnya: $POSTGRES_APP_NAME"
if [[ "$(state POSTGRES_DEPLOYED)" != "1" ]]; then
  confirm "Nyalakan container PostgreSQL sekarang (dibutuhkan tiket 07)?" || { warn "dibatalkan"; exit 1; }
  api_post "postgres.deploy" "$(jq -n --arg id "$POSTGRES_ID" '{postgresId:$id}')" >/dev/null
  poll_status "postgres.one" "postgresId" "$POSTGRES_ID" || { warn "cek panel Dokploy untuk detail galat"; exit 1; }
  write_env POSTGRES_DEPLOYED 1
fi

# ── 7. Application & image ──────────────────────────────────────────────────
stage "Application dan image production" 7
APPLICATION_ID=$(state APPLICATION_ID)
APPLICATION_NAME=$(state APPLICATION_NAME)
if [[ -n "$APPLICATION_ID" ]]; then
  note "sudah ada: application=$APPLICATION_ID"
else
  ask APPLICATION_NAME "Nama Application production:"
  confirm "Buat Application '$APPLICATION_NAME' (sourceType docker) di environment ini?" || { warn "dibatalkan"; exit 1; }
  resp=$(api_post "application.create" "$(server_json | jq \
    --arg n "$APPLICATION_NAME" --arg env "$ENVIRONMENT_ID" \
    '. + {name:$n, appName:$n, environmentId:$env, sourceType:"docker"}')")
  api_check "$resp" "application.create"
  APPLICATION_ID=$(printf '%s' "$resp" | jq -r '.applicationId')
  write_env APPLICATION_NAME "$APPLICATION_NAME"
  write_env APPLICATION_ID "$APPLICATION_ID"
fi
APPLICATION_APP_NAME=$(api_get "application.one" --data-urlencode "applicationId=$APPLICATION_ID" | jq -r '.appName')
write_env APPLICATION_APP_NAME "$APPLICATION_APP_NAME"
note "appName Application sebenarnya: $APPLICATION_APP_NAME"
say "Kandidat rilis yang sudah dibekukan dan diuji di staging:"
say "  ghcr.io/kammi-id/kammi-id@sha256:27a43de67c6e66301c2d2d65126f94f6c629fc3ec149d00cc67b9934a6744f85"
say "(sama dengan tag sha-b0e5ee6; production dipatok ke digest, bukan tag)"
ask IMAGE_REFERENCE "Referensi image immutable (digest lengkap):"
[[ -n "$IMAGE_REFERENCE" ]] || { warn "referensi image wajib diisi"; exit 1; }
[[ "$IMAGE_REFERENCE" == *"@sha256:"* ]] || warn "bukan digest — tag mengambang ditolak spec; lanjut hanya kalau memang disengaja"
write_env IMAGE_REFERENCE "$IMAGE_REFERENCE"
resp=$(api_post "application.saveDockerProvider" "$(jq -n --arg img "$IMAGE_REFERENCE" --arg id "$APPLICATION_ID" \
  --arg u "$GHCR_USERNAME" --arg p "$GHCR_PAT" \
  '{dockerImage:$img, applicationId:$id, username:$u, password:$p, registryUrl:"ghcr.io"}')")
api_check "$resp" "application.saveDockerProvider"
resp=$(api_post "application.update" "$(jq -n --arg id "$APPLICATION_ID" '{applicationId:$id, replicas:1}')")
api_check "$resp" "application.update (replicas)"
APPLICATION_REPLICAS=$(api_get "application.one" --data-urlencode "applicationId=$APPLICATION_ID" | jq -r '.replicas')
note "image=$IMAGE_REFERENCE replicas=$APPLICATION_REPLICAS"
warn "Application sengaja TIDAK di-deploy di tiket ini — deploy adalah urusan tiket 06/08."

# ── 8. Mount volume unik ────────────────────────────────────────────────────
stage "Mount named volume upload dan cache" 5
mounts=$(api_get "mounts.listByServiceId" --data-urlencode "serviceId=$APPLICATION_ID" --data-urlencode "serviceType=application")
api_check "$mounts" "mounts.listByServiceId"
create_mount() {
  local volume="$1" path="$2"
  if printf '%s' "$mounts" | jq -e --arg v "$volume" '.[] | select(.volumeName==$v)' >/dev/null 2>&1; then
    note "mount '$volume' sudah ada"
    return
  fi
  local resp
  resp=$(api_post "mounts.create" "$(jq -n --arg v "$volume" --arg p "$path" --arg id "$APPLICATION_ID" \
    '{type:"volume", volumeName:$v, mountPath:$p, serviceType:"application", serviceId:$id}')")
  api_check "$resp" "mounts.create ($volume)"
  note "volume '$volume' dipasang di $path"
}
create_mount "$UPLOAD_VOLUME" "/data/uploads"
create_mount "$CACHE_VOLUME" "/app/.next/cache"
api_get "mounts.listByServiceId" --data-urlencode "serviceId=$APPLICATION_ID" --data-urlencode "serviceType=application" \
  | jq -r '.[] | "  - \(.type) \(.volumeName // .hostPath) → \(.mountPath)"'
pause "Kedua mount di atas benar dan tidak menunjuk volume project lama — tekan Enter."

# ── 9. Ownership volume (SSH manual) ────────────────────────────────────────
stage "Ownership volume 1001:1001" 6
say "Aplikasi berjalan sebagai UID/GID 1001:1001 (Dockerfile: user 'nextjs')."
warn "Named volume baru dibuat Docker saat deploy pertama dan dimiliki root — jadi"
warn "volume-nya dibuat lebih dulu di sini supaya bisa di-chown sebelum ada trafik."
say "SSH ke host production, lalu jalankan:"
step "docker volume create $UPLOAD_VOLUME"
step "docker volume create $CACHE_VOLUME"
step "sudo chown -R 1001:1001 \$(docker volume inspect $UPLOAD_VOLUME --format '{{.Mountpoint}}')"
step "sudo chown -R 1001:1001 \$(docker volume inspect $CACHE_VOLUME --format '{{.Mountpoint}}')"
note "ssh-agent biasanya kosong — pakai identity file eksplisit (ssh -i <kunci>.pem <host>)."
pause "Sudah dijalankan lewat SSH?"
volumes=$(api_get "dockerVolume.getVolumes" ${SERVER_ID:+--data-urlencode "serverId=$SERVER_ID"})
for v in "$UPLOAD_VOLUME" "$CACHE_VOLUME"; do
  if printf '%s' "$volumes" | jq -e --arg v "$v" '.[] | select(.Name==$v)' >/dev/null 2>&1; then
    mp=$(api_get "dockerVolume.getVolumeConfig" --data-urlencode "volumeName=$v" ${SERVER_ID:+--data-urlencode "serverId=$SERVER_ID"} | jq -r '.Mountpoint')
    note "volume '$v' ada di host → $mp"
  else
    warn "volume '$v' belum terlihat di host — ulangi docker volume create"
  fi
done
say "API Dokploy tidak mengembalikan owner/group, jadi buktinya tetap output perintah kamu."
ask UPLOAD_OWNERSHIP_EVIDENCE "Referensi bukti ownership upload (ID output/screenshot, bukan secret):"
ask CACHE_OWNERSHIP_EVIDENCE "Referensi bukti ownership cache (ID output/screenshot, bukan secret):"
write_env UPLOAD_OWNERSHIP_EVIDENCE "$UPLOAD_OWNERSHIP_EVIDENCE"
write_env CACHE_OWNERSHIP_EVIDENCE "$CACHE_OWNERSHIP_EVIDENCE"

# ── 10. Environment aplikasi ────────────────────────────────────────────────
stage "Environment production Application" 6
say "DATABASE_URL memakai appName Postgres yang dibaca balik, bukan yang diminta."
API_CO_ID_TOKEN=$(state API_CO_ID_TOKEN)
CACHE_REVALIDATE_SECRET=$(state CACHE_REVALIDATE_SECRET)
ask_secret API_CO_ID_TOKEN "API_CO_ID_TOKEN khusus production (jangan pakai nilai staging):"
[[ -n "$API_CO_ID_TOKEN" ]] || { warn "API_CO_ID_TOKEN wajib diisi"; exit 1; }
if [[ -z "$CACHE_REVALIDATE_SECRET" ]]; then
  CACHE_REVALIDATE_SECRET=$(openssl rand -hex 32)
  note "CACHE_REVALIDATE_SECRET digenerate lokal (openssl rand)"
fi
write_env API_CO_ID_TOKEN "$API_CO_ID_TOKEN"
write_env CACHE_REVALIDATE_SECRET "$CACHE_REVALIDATE_SECRET"
DATABASE_URL="postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${POSTGRES_APP_NAME}:5432/${DATABASE_NAME}"
write_env DATABASE_URL "$DATABASE_URL"
ENV_BLOCK=$(printf 'DATABASE_URL=%s\nUPLOADS_DIR=/data/uploads\nNODE_ENV=production\nPORT=3000\nHOSTNAME=0.0.0.0\nAPI_CO_ID_TOKEN=%s\nCACHE_REVALIDATE_SECRET=%s\n' \
  "$DATABASE_URL" "$API_CO_ID_TOKEN" "$CACHE_REVALIDATE_SECRET")
resp=$(api_post "application.saveEnvironment" "$(jq -n --arg id "$APPLICATION_ID" --arg env "$ENV_BLOCK" \
  '{applicationId:$id, env:$env, buildArgs:null, buildSecrets:null, createEnvFile:false}')")
api_check "$resp" "application.saveEnvironment"
note "7 variabel tersimpan di Dokploy (DATABASE_URL, UPLOADS_DIR, NODE_ENV, PORT, HOSTNAME, API_CO_ID_TOKEN, CACHE_REVALIDATE_SECRET)"
saved_env=$(api_get "application.one" --data-urlencode "applicationId=$APPLICATION_ID" | jq -r '.env // ""')
if grep -qE '^(RUN_MIGRATIONS|DB_GUARD_ACK)=' <<<"$saved_env"; then
  warn "RUN_MIGRATIONS/DB_GUARD_ACK terpasang permanen — dilarang; hapus dari panel sekarang"
  exit 1
fi
note "terverifikasi: RUN_MIGRATIONS dan DB_GUARD_ACK tidak terpasang permanen"

# ── 11. Hostname validasi & health check ────────────────────────────────────
stage "Hostname validasi dan health check" 6
VALIDATION_HOST=$(state VALIDATION_HOST)
while :; do
  ask VALIDATION_HOST "Hostname validasi (tidak boleh apex, www, wildcard, atau assets.kammi.id):"
  case "$VALIDATION_HOST" in
    ""|kammi.id|www.kammi.id|assets.kammi.id|\*.*)
      warn "'$VALIDATION_HOST' merebut hostname production — pilih hostname validasi lain"; continue ;;
  esac
  break
done
write_env VALIDATION_HOST "$VALIDATION_HOST"
existing_domains=$(api_get "domain.byApplicationId" --data-urlencode "applicationId=$APPLICATION_ID")
if printf '%s' "$existing_domains" | jq -e --arg h "$VALIDATION_HOST" '.[] | select(.host==$h)' >/dev/null 2>&1; then
  note "domain '$VALIDATION_HOST' sudah terpasang"
else
  resp=$(api_post "domain.create" "$(jq -n --arg h "$VALIDATION_HOST" --arg id "$APPLICATION_ID" \
    '{host:$h, port:3000, https:true, certificateType:"letsencrypt", path:"/", applicationId:$id, domainType:"application"}')")
  api_check "$resp" "domain.create"
  note "domain '$VALIDATION_HOST' terpasang (TLS terbit setelah deploy pertama)"
fi
final_domains=$(api_get "domain.byApplicationId" --data-urlencode "applicationId=$APPLICATION_ID")
printf '%s' "$final_domains" | jq -r '.[] | "  - \(.host)"'
if printf '%s' "$final_domains" \
   | jq -e '.[] | select(.host=="kammi.id" or .host=="www.kammi.id" or .host=="assets.kammi.id" or (.host|startswith("*.")))' >/dev/null 2>&1; then
  warn "ada Host rule production pada Application baru — hapus sebelum lanjut"
  exit 1
fi
note "terverifikasi: tidak ada apex, www, wildcard, atau assets.kammi.id di Application ini"
HEALTH_CMD='bun -e '"'"'const r = await fetch("http://127.0.0.1:3000/api/health/ready"); process.exit(r.ok ? 0 : 1)'"'"''
resp=$(api_post "application.update" "$(jq -n --arg id "$APPLICATION_ID" --arg cmd "$HEALTH_CMD" \
  '{applicationId:$id, healthCheckSwarm:{Test:["CMD-SHELL",$cmd],Interval:30000000000,Timeout:5000000000,StartPeriod:60000000000,Retries:3}}')")
api_check "$resp" "application.update (healthCheckSwarm)"
note "healthCheckSwarm memakai /api/health/ready (image runner bun-slim tidak punya curl)"
note "/api/health/live dipakai monitor eksternal — itu cakupan tiket 05, bukan di sini"

# ── 12. Backup PostgreSQL dan volume ────────────────────────────────────────
stage "Backup PostgreSQL dan kedua named volume" 7
destinations=$(api_get "destination.all")
api_check "$destinations" "destination.all"
if [[ "$(printf '%s' "$destinations" | jq 'length')" == "0" ]]; then
  warn "belum ada backup destination di instance ini — buat dulu lewat panel (butuh kredensial S3)."
  open_url "${DOKPLOY_PROD_URL%/}/dashboard/settings/destinations"
  pause "Sudah dibuat? Tekan Enter untuk membaca ulang."
  destinations=$(api_get "destination.all")
fi
printf '%s' "$destinations" | jq -r '.[] | "  - \(.name)  bucket=\(.bucket)  destinationId=\(.destinationId)"'
ask DESTINATION_ID "destinationId yang dipakai:"
BACKUP_DESTINATION=$(printf '%s' "$destinations" | jq -r --arg d "$DESTINATION_ID" '.[] | select(.destinationId==$d) | .name')
[[ -n "$BACKUP_DESTINATION" ]] || { warn "destinationId tidak ada di daftar di atas"; exit 1; }
write_env DESTINATION_ID "$DESTINATION_ID"
write_env BACKUP_DESTINATION "$BACKUP_DESTINATION"
ask POSTGRES_BACKUP_SCHEDULE "Cron backup PostgreSQL (default '0 3 * * *'):"; : "${POSTGRES_BACKUP_SCHEDULE:=0 3 * * *}"
ask POSTGRES_BACKUP_RETENTION "Jumlah backup PostgreSQL yang disimpan (keepLatestCount, default 14):"; : "${POSTGRES_BACKUP_RETENTION:=14}"
ask VOLUME_BACKUP_SCHEDULE "Cron backup volume (default '0 4 * * *'):"; : "${VOLUME_BACKUP_SCHEDULE:=0 4 * * *}"
ask VOLUME_BACKUP_RETENTION "Jumlah backup volume yang disimpan (keepLatestCount, default 14):"; : "${VOLUME_BACKUP_RETENTION:=14}"
for k in POSTGRES_BACKUP_RETENTION VOLUME_BACKUP_RETENTION; do
  [[ "${!k}" =~ ^[0-9]+$ ]] || { warn "$k harus angka (keepLatestCount), bukan '${!k}'"; exit 1; }
done
for k in POSTGRES_BACKUP_SCHEDULE POSTGRES_BACKUP_RETENTION VOLUME_BACKUP_SCHEDULE VOLUME_BACKUP_RETENTION; do
  write_env "$k" "${!k}"
done
if [[ "$(state POSTGRES_BACKUP_CREATED)$(state UPLOAD_VOLUME_BACKUP_CREATED)$(state CACHE_VOLUME_BACKUP_CREATED)" == "111" ]]; then
  note "ketiga jadwal backup sudah dibuat di run sebelumnya — tidak ada yang perlu dikonfirmasi"
else
  confirm "Buat 1 backup PostgreSQL + 2 backup volume ke '$BACKUP_DESTINATION'?" || { warn "dibatalkan"; exit 1; }
fi
if [[ "$(state POSTGRES_BACKUP_CREATED)" != "1" ]]; then
  resp=$(api_post "backup.create" "$(jq -n --arg pg "$POSTGRES_ID" --arg db "$DATABASE_NAME" --arg d "$DESTINATION_ID" \
    --arg s "$POSTGRES_BACKUP_SCHEDULE" --argjson keep "$POSTGRES_BACKUP_RETENTION" --arg prefix "$PROJECT_NAME/postgres/" \
    '{postgresId:$pg, databaseType:"postgres", backupType:"database", database:$db, destinationId:$d, schedule:$s, prefix:$prefix, keepLatestCount:$keep, enabled:true}')")
  api_check "$resp" "backup.create (postgres)"
  write_env POSTGRES_BACKUP_CREATED 1
  note "backup PostgreSQL aktif: $POSTGRES_BACKUP_SCHEDULE, simpan $POSTGRES_BACKUP_RETENTION terakhir"
else
  note "backup PostgreSQL sudah dibuat di run sebelumnya"
fi
create_volume_backup() {
  local volume="$1" flag="$2"
  if [[ "$(state "$flag")" == "1" ]]; then note "backup volume '$volume' sudah dibuat"; return; fi
  local resp
  resp=$(api_post "volumeBackups.create" "$(jq -n --arg n "$volume" --arg v "$volume" --arg app "$APPLICATION_ID" \
    --arg d "$DESTINATION_ID" --arg cron "$VOLUME_BACKUP_SCHEDULE" --argjson keep "$VOLUME_BACKUP_RETENTION" \
    --arg prefix "$PROJECT_NAME/volumes/$volume/" \
    '{name:$n, volumeName:$v, prefix:$prefix, serviceType:"application", applicationId:$app, destinationId:$d, cronExpression:$cron, keepLatestCount:$keep, enabled:true, turnOff:false}')")
  api_check "$resp" "volumeBackups.create ($volume)"
  write_env "$flag" 1
  note "backup volume '$volume' aktif: $VOLUME_BACKUP_SCHEDULE"
}
create_volume_backup "$UPLOAD_VOLUME" UPLOAD_VOLUME_BACKUP_CREATED
create_volume_backup "$CACHE_VOLUME" CACHE_VOLUME_BACKUP_CREATED

# ── 13. Verifikasi akhir & catat bukti ──────────────────────────────────────
stage "Verifikasi akhir dan catat bukti handoff" 4
app=$(api_get "application.one" --data-urlencode "applicationId=$APPLICATION_ID")
pg=$(api_get "postgres.one" --data-urlencode "postgresId=$POSTGRES_ID")
printf '%s' "$app" | jq -r '"  Application: \(.name) appName=\(.appName) replicas=\(.replicas) status=\(.applicationStatus) image=\(.dockerImage)"'
printf '%s' "$pg"  | jq -r '"  PostgreSQL : \(.name) appName=\(.appName) status=\(.applicationStatus) image=\(.dockerImage)"'
printf '%s' "$app" | jq -r '"  Mounts     : " + ([.mounts[] | "\(.volumeName)→\(.mountPath)"] | join(", "))'
printf '%s' "$app" | jq -r '"  Domains    : " + ([.domains[].host] | join(", "))'
say "Record berikut sengaja hanya berisi ID, nama, mount, dan kebijakan backup — tanpa secret."
record_provisioning
warn "Secret production (password DB, PAT, token) ada di $ENV_FILE saja — jangan commit, jangan tempel ke tiket."
say "Tiket 04 selesai setelah fakta non-secret di record itu dilampirkan ke tiketnya."
say "Berikutnya: tiket 05 memvalidasi observability/routing; tiket 06 membekukan image digest."
finish
