#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Tiket 07, jalur tunggal: mengisi project production BARU dari stack lama
# tanpa menyentuh trafik.
#
# Stack lama hanya DIBACA — pg_dump read-only dan mc mirror read-only. Tidak
# ada Host rule yang dilepas, tidak ada service lama yang dihentikan, tidak
# ada tulisan ke database maupun RustFS lama. Semua operasi destruktif di
# wizard ini menargetkan project BARU.
#
# Domain TIDAK berpindah di sini. Itu wizard-09, di dalam maintenance window.
#
# Aman di-Ctrl-C: nilai non-secret tersimpan di $ENV_FILE dan re-run akan
# menawarkannya kembali. API key, password DB, dan kunci RustFS tidak pernah
# ditulis ke berkas.

TOTAL_STAGES=12

# Digest kandidat yang sudah diuji di staging (ghcr.io/kammi-id/kammi-id:sha-b0e5ee6).
# Production dipatok ke digest, bukan tag: tag bisa dipindah, digest tidak.
CANDIDATE_DIGEST="sha256:27a43de67c6e66301c2d2d65126f94f6c629fc3ec149d00cc67b9934a6744f85"
CANDIDATE_IMAGE="ghcr.io/kammi-id/kammi-id@${CANDIDATE_DIGEST}"

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
# Nama berkas sengaja diawali '.env' supaya kena pola '.env*' di .gitignore —
# .scratch/ sendiri ikut ter-commit di repo ini.
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.env.cutover}"

dokploy_get() { curl -sS --max-time 30 -H "x-api-key: $2" "${1%/}/api/$3"; }
jq_err() { printf '%s' "$1" | jq -r '.message // empty' 2>/dev/null; }
ssh_prod() { ssh "${SSH_OPTS[@]}" "$SSH_HOST" "$@"; }

# pick_container APPNAME VARNAME — Dokploy selalu menyuffix appName secara acak,
# jadi nama container tidak pernah boleh diasumsikan. Tampilkan kandidat nyata
# dari 'docker ps' lalu minta manusia memilih.
pick_container() {
  local appname="$1" varname="$2" candidates
  candidates=$(ssh_prod "docker ps --filter name=$appname --format '{{.Names}}'")
  if [[ -z "$candidates" ]]; then
    warn "tidak ada container berjalan yang cocok dengan '*$appname*' di $SSH_HOST"
    exit 1
  fi
  note "kandidat container untuk '$appname':"
  printf '%s\n' "$candidates" | sed 's/^/    /'
  if [[ $(printf '%s\n' "$candidates" | wc -l) -eq 1 ]]; then
    printf -v "$varname" '%s' "$(printf '%s' "$candidates" | tr -d '[:space:]')"
    note "dipilih otomatis: ${!varname}"
  else
    ask "$varname" "Nama container yang benar (salin dari daftar di atas):"
  fi
}

cd "$REPO_ROOT"
banner "Pre-copy data & aset ke project production baru"

# ── 1 ───────────────────────────────────────────────────────────────────────
stage "Prasyarat dan pagar"
say "Wizard ini MENGISI project production baru. Stack lama hanya dibaca:"
say "  · pg_dump read-only dari Postgres lama"
say "  · mc mirror read-only dari bucket RustFS lama"
say ""
say "Tidak ada Host rule yang dipindah. Tidak ada service lama yang berhenti."
say "Trafik production tetap dilayani stack lama sepanjang wizard ini."
warn "Yang destruktif hanya menimpa Postgres dan volume project BARU."
for c in jq ssh curl; do
  command -v "$c" >/dev/null 2>&1 || { warn "'$c' tidak ditemukan — pasang dulu"; exit 1; }
done
note "kandidat: $CANDIDATE_IMAGE"
say "Digest itu yang sudah diuji di staging. Kalau tidak cocok dengan catatan"
say "rilis, BERHENTI — jangan promosikan artefak yang belum lulus gate."
if ! confirm "Digest di atas cocok dengan catatan rilis?"; then
  warn "digest tidak dikonfirmasi; berhenti"; exit 1
fi

# ── 2 ───────────────────────────────────────────────────────────────────────
stage "Kredensial Dokploy production"
say "Dipakai untuk MEMBACA nama service lewat API. API key tidak ditulis ke"
say "berkas mana pun dan harus diketik ulang tiap run."
ask PROD_URL "URL panel Dokploy production:"
write_env PROD_URL "$PROD_URL"
ask_secret PROD_API_KEY "API key Dokploy production:"
health=$(dokploy_get "$PROD_URL" "$PROD_API_KEY" "settings.health")
if [[ "$health" != '{"status":"ok"}' ]]; then
  warn "settings.health tidak sehat: $health"; exit 1
fi
note "terhubung ke $PROD_URL"

# ── 3 ───────────────────────────────────────────────────────────────────────
stage "Sumber daya project baru"
say "Ambil dari catatan provisioning tiket 04. Semuanya non-secret."
ask NEW_POSTGRES_ID "postgresId Postgres BARU:"
write_env NEW_POSTGRES_ID "$NEW_POSTGRES_ID"
ask NEW_APPLICATION_ID "applicationId Application BARU:"
write_env NEW_APPLICATION_ID "$NEW_APPLICATION_ID"
ask UPLOAD_VOLUME "Nama named volume upload BARU:"
write_env UPLOAD_VOLUME "$UPLOAD_VOLUME"
ask VALIDATION_HOST "Hostname validasi Application baru (bukan apex/www/wildcard):"
write_env VALIDATION_HOST "$VALIDATION_HOST"

resp=$(dokploy_get "$PROD_URL" "$PROD_API_KEY" "postgres.one?postgresId=$NEW_POSTGRES_ID")
err=$(jq_err "$resp"); [[ -z "$err" ]] || { warn "postgres.one (baru) gagal: $err"; exit 1; }
NEW_PG_APPNAME=$(printf '%s' "$resp" | jq -r '.appName')
NEW_DB_NAME=$(printf '%s' "$resp" | jq -r '.databaseName // empty')
NEW_DB_USER=$(printf '%s' "$resp" | jq -r '.databaseUser // empty')
[[ -n "$NEW_PG_APPNAME" && "$NEW_PG_APPNAME" != "null" ]] || { warn "appName baru kosong"; exit 1; }
note "Postgres baru — appName: $NEW_PG_APPNAME · db: $NEW_DB_NAME · user: $NEW_DB_USER"
if [[ -z "$NEW_DB_NAME" ]]; then
  ask NEW_DB_NAME "Nama database BARU:"
  ask NEW_DB_USER "User database BARU:"
fi

# DATABASE_URL kandidat dibaca dari environment Application yang sudah disetel
# di panel (tiket 04), supaya password tidak perlu diketik ulang di sini.
appresp=$(dokploy_get "$PROD_URL" "$PROD_API_KEY" "application.one?applicationId=$NEW_APPLICATION_ID")
err=$(jq_err "$appresp"); [[ -z "$err" ]] || { warn "application.one gagal: $err"; exit 1; }
NEW_DATABASE_URL=$(printf '%s' "$appresp" | jq -r '.env // empty' \
  | grep -E '^DATABASE_URL=' | head -n1 | sed 's/^DATABASE_URL=//' | tr -d '"'"'"'')
if [[ -n "$NEW_DATABASE_URL" ]]; then
  note "DATABASE_URL kandidat terbaca dari environment Application (nilai tidak ditampilkan)"
else
  warn "DATABASE_URL tidak ditemukan di environment Application baru."
  warn "Selesaikan stage 'Environment production' di wizard-04 dulu, atau isi manual."
  ask_secret NEW_DATABASE_URL "DATABASE_URL Postgres BARU (tidak disimpan):"
fi
[[ -n "$NEW_DATABASE_URL" ]] || { warn "DATABASE_URL kosong; berhenti"; exit 1; }

# ── 4 ───────────────────────────────────────────────────────────────────────
stage "SSH ke host production"
say "ADR 0015: project lama dan baru berada di server yang sama, jadi satu"
say "target SSH melayani keduanya — dump dan mirror tidak perlu singgah ke"
say "mesin lokal sama sekali."
ask SSH_HOST "SSH target host production (user@host):"
write_env SSH_HOST "$SSH_HOST"
ask SSH_KEY "Identity file (mis. ~/.ssh/kammi-id.pem; kosongkan kalau tidak perlu -i):"
write_env SSH_KEY "$SSH_KEY"
SSH_OPTS=(-o ServerAliveInterval=15 -o ServerAliveCountMax=10)
if [[ -n "$SSH_KEY" ]]; then
  SSH_OPTS+=(-i "${SSH_KEY/#\~/$HOME}")
fi
if ! ssh_prod "docker version --format '{{.Server.Version}}'" >/dev/null 2>&1; then
  warn "tidak bisa menjalankan docker lewat SSH di $SSH_HOST — periksa host, kunci, dan izin"
  exit 1
fi
note "docker terjangkau di $SSH_HOST"
ask DOCKER_NETWORK "Docker network tempat Postgres/RustFS hidup (default dokploy-network):"
: "${DOCKER_NETWORK:=dokploy-network}"
write_env DOCKER_NETWORK "$DOCKER_NETWORK"

# ── 5 ───────────────────────────────────────────────────────────────────────
stage "Identifikasi Postgres lama dan baru"
say "Buka panel, masuk ke project production LAMA, klik service Postgres-nya."
say "URL-nya berbentuk .../services/postgres/<ID> — salin <ID>."
open_url "${PROD_URL%/}/dashboard"
ask OLD_POSTGRES_ID "postgresId Postgres LAMA:"
write_env OLD_POSTGRES_ID "$OLD_POSTGRES_ID"
resp=$(dokploy_get "$PROD_URL" "$PROD_API_KEY" "postgres.one?postgresId=$OLD_POSTGRES_ID")
err=$(jq_err "$resp"); [[ -z "$err" ]] || { warn "postgres.one (lama) gagal: $err"; exit 1; }
OLD_PG_APPNAME=$(printf '%s' "$resp" | jq -r '.appName')
OLD_DB_NAME=$(printf '%s' "$resp" | jq -r '.databaseName // empty')
OLD_DB_USER=$(printf '%s' "$resp" | jq -r '.databaseUser // empty')
note "Postgres lama — appName: $OLD_PG_APPNAME · db: $OLD_DB_NAME · user: $OLD_DB_USER"
if [[ -z "$OLD_DB_NAME" ]]; then
  ask OLD_DB_NAME "Nama database LAMA:"
  ask OLD_DB_USER "User database LAMA:"
fi
if [[ "$OLD_POSTGRES_ID" == "$NEW_POSTGRES_ID" ]]; then
  warn "postgresId lama dan baru IDENTIK — itu berarti restore akan menimpa"
  warn "database production yang sedang melayani trafik. Berhenti."
  exit 1
fi
pick_container "$OLD_PG_APPNAME" OLD_PG_CONTAINER
pick_container "$NEW_PG_APPNAME" NEW_PG_CONTAINER
if [[ "$OLD_PG_CONTAINER" == "$NEW_PG_CONTAINER" ]]; then
  warn "container lama dan baru identik — berhenti"; exit 1
fi
note "lama: $OLD_PG_CONTAINER → baru: $NEW_PG_CONTAINER"
# Disimpan supaya wizard-09 menawarkannya sebagai default: mengetik ulang nama
# container di tengah maintenance window adalah tempat yang buruk untuk salah
# ketik. Semuanya non-secret.
write_env OLD_PG_CONTAINER "$OLD_PG_CONTAINER"
write_env NEW_PG_CONTAINER "$NEW_PG_CONTAINER"
write_env OLD_DB_NAME "$OLD_DB_NAME"
write_env OLD_DB_USER "$OLD_DB_USER"
write_env NEW_DB_NAME "$NEW_DB_NAME"
write_env NEW_DB_USER "$NEW_DB_USER"

# ── 6 ───────────────────────────────────────────────────────────────────────
stage "pg_dump production lama (read-only)"
say "Dump ditulis ke disk host production, bukan ditarik ke mesin lokal —"
say "keduanya di server yang sama, jadi tidak ada gunanya lewat internet."
DUMP_REMOTE="/tmp/kammi-cutover-$(date -u +%Y%m%dT%H%M%SZ).dump"
write_env DUMP_REMOTE "$DUMP_REMOTE"
say "Menjalankan pg_dump -Fc di dalam $OLD_PG_CONTAINER..."
ssh_prod "docker exec '$OLD_PG_CONTAINER' pg_dump -Fc -U '$OLD_DB_USER' -d '$OLD_DB_NAME' > '$DUMP_REMOTE'"
DUMP_BYTES=$(ssh_prod "wc -c < '$DUMP_REMOTE'" | tr -d ' ')
if [[ "${DUMP_BYTES:-0}" -le 0 ]]; then
  warn "dump kosong (0 byte) — periksa nama database dan user"; exit 1
fi
note "dump selesai: $DUMP_BYTES byte di $SSH_HOST:$DUMP_REMOTE"
say "Catat angka ini di catatan rilis — ia juga anggaran waktu untuk window."

# ── 7 ───────────────────────────────────────────────────────────────────────
stage "Restore ke Postgres BARU"
warn "DESTRUKTIF terhadap database '$NEW_DB_NAME' di project BARU."
say "Database lama tidak disentuh sama sekali oleh perintah ini."
if ! confirm "Restore $DUMP_BYTES byte ke '$NEW_DB_NAME' ($NEW_PG_CONTAINER)?"; then
  warn "dibatalkan"; exit 1
fi
ssh_prod "docker exec -i '$NEW_PG_CONTAINER' pg_restore --clean --if-exists --no-owner --no-privileges -U '$NEW_DB_USER' -d '$NEW_DB_NAME' < '$DUMP_REMOTE'" \
  || warn "pg_restore melaporkan galat — baris 'does not exist' itu NORMAL untuk --if-exists, tapi baca sisanya"
note "restore selesai"

# ── 8 ───────────────────────────────────────────────────────────────────────
stage "Rekonsiliasi ledger migrasi drizzle"
say "pg_restore --clean menimpa drizzle.__drizzle_migrations project baru dengan"
say "punya production lama. Kalau ledger itu lebih pendek dari folder migrasi"
say "yang dibawa image kandidat, migrasi berikutnya akan mencoba menerapkan"
say "ulang migrasi yang 'belum tercatat'."
warn "Efeknya bisa SUDAH ada di skema (tinggal dicatat), atau BENAR belum ada"
warn "(harus dijalankan). Dua kasus itu WAJIB dibedakan satu per satu."
say "Kejadian nyata saat refresh staging: 3 dari 7 migrasi yang 'terlihat"
say "serupa' ternyata beda status, dan baru ketahuan lewat error runtime."
DB_MIGRATIONS=$(cat <<'SQLEOF' | ssh_prod "docker exec -i '$NEW_PG_CONTAINER' psql -t -A -U '$NEW_DB_USER' -d '$NEW_DB_NAME'"
select name from drizzle.__drizzle_migrations order by id;
SQLEOF
)
MISSING=()
for dir in src/db/__migrations/*/; do
  name=$(basename "$dir")
  [[ -f "${dir}migration.sql" ]] || continue
  grep -qxF "$name" <<< "$DB_MIGRATIONS" || MISSING+=("$name")
done
if (( ${#MISSING[@]} == 0 )); then
  note "ledger sudah lengkap — tidak ada yang perlu direkonsiliasi"
else
  warn "${#MISSING[@]} migrasi belum tercatat di ledger project baru:"
  printf '  - %s\n' "${MISSING[@]}"
  say ""
  say "Untuk TIAP SATU: baca SQL-nya, lalu VERIFIKASI LANGSUNG ke database baru"
  say "(mis. \\d nama_tabel, atau select dari information_schema) apakah efeknya"
  say "SUDAH ada. JANGAN menggeneralisasi dari migrasi lain yang mirip."
  for name in "${MISSING[@]}"; do
    printf '\n  %s%s%s\n' "$BOLD" "$name" "$RESET"
    sed 's/^/    /' "src/db/__migrations/${name}/migration.sql"
    if confirm "Sudah diverifikasi ke DB baru — efek SQL di atas SUDAH ada?"; then
      HASH=$(shasum -a 256 "src/db/__migrations/${name}/migration.sql" | cut -d' ' -f1)
      DATEPART="${name:0:14}"
      MILLIS=$(date -u -j -f "%Y%m%d%H%M%S" "$DATEPART" "+%s000" 2>/dev/null \
        || date -u -d "${DATEPART:0:4}-${DATEPART:4:2}-${DATEPART:6:2} ${DATEPART:8:2}:${DATEPART:10:2}:${DATEPART:12:2}" "+%s000")
      ssh_prod "docker exec -i '$NEW_PG_CONTAINER' psql -U '$NEW_DB_USER' -d '$NEW_DB_NAME' -c \"insert into drizzle.__drizzle_migrations (hash, created_at, name) values ('$HASH', $MILLIS, '$name');\""
      note "dicatat sebagai sudah diterapkan (SQL-nya TIDAK dijalankan ulang)"
    else
      warn "dibiarkan tidak tercatat — akan benar-benar dijalankan di stage berikutnya"
    fi
  done
fi

# ── 9 ───────────────────────────────────────────────────────────────────────
stage "Preflight duplikat dan migrasi one-shot"
say "Satu container dari digest kandidat menjalankan check-duplicates lalu"
say "migrate, kemudian berhenti tanpa melayani HTTP (docker-entrypoint.sh:"
say "RUN_MIGRATIONS=1 + MIGRATIONS_ONLY=1). Lock timeout 10 detik sudah"
say "tertanam di src/scripts/migrate.ts."
warn "Duplikat organization.code berarti BERHENTI — Nomor Induk Anggota tidak"
warn "boleh diubah secara mekanis (ADR 0004). Duplikat slug diperbaiki lewat"
warn "pekerjaan koreksi terpisah yang diaudit, bukan di tengah window."
say "Memastikan image kandidat tersedia di host..."
if ! ssh_prod "docker image inspect '$CANDIDATE_IMAGE'" >/dev/null 2>&1; then
  say "Image belum ada di host; menarik dari GHCR..."
  if ! ssh_prod "docker pull '$CANDIDATE_IMAGE'"; then
    warn "docker pull gagal — host mungkin belum login ke ghcr.io."
    warn "Jalankan 'docker login ghcr.io' di $SSH_HOST lalu ulangi wizard."
    exit 1
  fi
fi
if ! confirm "Jalankan preflight + migrasi terhadap database BARU sekarang?"; then
  warn "dibatalkan"; exit 1
fi
if ssh_prod "docker run --rm --network '$DOCKER_NETWORK' \
    -e DATABASE_URL='$NEW_DATABASE_URL' \
    -e RUN_MIGRATIONS=1 -e MIGRATIONS_ONLY=1 -e DB_GUARD_ACK=1 \
    '$CANDIDATE_IMAGE'"; then
  note "✓ preflight lulus dan migrasi selesai; container sudah berhenti"
else
  warn "one-shot container GAGAL. Jangan lanjut."
  warn "Baca keluarannya di atas: duplikat code, lock timeout, atau migrasi"
  warn "yang benar-benar gagal punya penanganan yang berbeda-beda."
  exit 1
fi

# ── 10 ──────────────────────────────────────────────────────────────────────
stage "Pre-copy aset RustFS → volume baru"
say "Production belum migrasi ke volume (ADR 0006), jadi sumbernya masih RustFS."
say "Kunci objek dipertahankan apa adanya — tidak ada baris database maupun URL"
say "legacy yang perlu ditulis ulang."
warn "RustFS tidak terjangkau dari luar; mc dijalankan DI HOST production di"
warn "dalam docker network, menulis LANGSUNG ke volume baru. Karena tidak ada"
warn "singgahan tar di macOS, masalah sidecar AppleDouble tidak berlaku di sini."
ask RUSTFS_BUCKET "Nama bucket RustFS (kemungkinan 'kammiid' — lihat ADR 0006):"
write_env RUSTFS_BUCKET "$RUSTFS_BUCKET"
ask RUSTFS_ENDPOINT "Endpoint RustFS di dalam network (default http://rustfs:9000):"
: "${RUSTFS_ENDPOINT:=http://rustfs:9000}"
write_env RUSTFS_ENDPOINT "$RUSTFS_ENDPOINT"
ask RUSTFS_ACCESS_KEY "Access key RustFS:"
ask_secret RUSTFS_SECRET_KEY "Secret key RustFS:"
RUSTFS_SCHEME="${RUSTFS_ENDPOINT%%://*}"
RUSTFS_HOSTPART="${RUSTFS_ENDPOINT#*://}"
MC_HOST_VALUE="${RUSTFS_SCHEME}://${RUSTFS_ACCESS_KEY}:${RUSTFS_SECRET_KEY}@${RUSTFS_HOSTPART}"
say "Menjalankan mc mirror langsung ke volume '$UPLOAD_VOLUME'..."
if ! ssh_prod "docker run --rm --network '$DOCKER_NETWORK' \
    -v '$UPLOAD_VOLUME':/out \
    -e MC_HOST_src='$MC_HOST_VALUE' \
    minio/mc:latest mirror --overwrite --quiet 'src/$RUSTFS_BUCKET' /out"; then
  warn "mc mirror gagal — periksa nama bucket, kredensial, dan network"
  exit 1
fi
# Container mc jalan sebagai root, sementara aplikasi jalan sebagai uid 1001.
# Tanpa chown ini, /api/images/* jatuh ke placeholder walau datanya benar.
ssh_prod "docker run --rm -v '$UPLOAD_VOLUME':/d alpine chown -R 1001:1001 /d"
note "mirror selesai, ownership dikembalikan ke 1001:1001"

# ── 11 ──────────────────────────────────────────────────────────────────────
stage "Verifikasi aset"
say "Dihitung, bukan dilihat sekilas: /api/images/* mengembalikan HTTP 200 juga"
say "untuk placeholder, jadi status HTTP bukan bukti."
SRC_STATS=$(ssh_prod "docker run --rm --network '$DOCKER_NETWORK' \
  -e MC_HOST_src='$MC_HOST_VALUE' minio/mc:latest ls --recursive --json 'src/$RUSTFS_BUCKET'" \
  | jq -s '{count: length, bytes: (map(.size) | add // 0)}')
SRC_COUNT=$(printf '%s' "$SRC_STATS" | jq -r '.count')
SRC_BYTES=$(printf '%s' "$SRC_STATS" | jq -r '.bytes')
DST_STATS=$(ssh_prod "docker run --rm -v '$UPLOAD_VOLUME':/d alpine sh -c \"find /d -type f | wc -l; find /d -type f -exec cat {} + 2>/dev/null | wc -c\"")
DST_COUNT=$(printf '%s\n' "$DST_STATS" | sed -n '1p' | tr -d ' ')
DST_BYTES=$(printf '%s\n' "$DST_STATS" | sed -n '2p' | tr -d ' ')
printf '  %-28s %8s berkas %14s byte\n' "RustFS (sumber)" "$SRC_COUNT" "$SRC_BYTES"
printf '  %-28s %8s berkas %14s byte\n' "volume baru (tujuan)" "$DST_COUNT" "$DST_BYTES"
if [[ "$SRC_COUNT" == "$DST_COUNT" && "$SRC_BYTES" == "$DST_BYTES" ]]; then
  note "✓ cocok persis"
else
  warn "TIDAK COCOK — jangan lanjut ke cutover tanpa investigasi."
  warn "Angka historis 44 objek / 173,9 MB hanya rujukan, bukan bukti rilis."
fi
OWNER_CHECK=$(ssh_prod "docker run --rm -v '$UPLOAD_VOLUME':/d alpine sh -c \"find /d -type f ! -user 1001 | head -5\"")
if [[ -z "$OWNER_CHECK" ]]; then
  note "✓ seluruh berkas dimiliki uid 1001"
else
  warn "masih ada berkas bukan milik 1001:"; printf '%s\n' "$OWNER_CHECK" | sed 's/^/    /'
fi
say "Catat kedua baris angka di atas untuk catatan rilis."

# ── 12 ──────────────────────────────────────────────────────────────────────
stage "Hidupkan kandidat di hostname validasi"
say "Application baru dipatok ke digest kandidat dan diuji di hostname validasi"
say "— masih TANPA apex, www, atau wildcard production."
open_url "${PROD_URL%/}/dashboard/project"
step "Application baru → pastikan image = $CANDIDATE_IMAGE (digest, bukan tag)."
step "Pastikan RUN_MIGRATIONS dan DB_GUARD_ACK TIDAK ada di environment-nya."
step "Deploy, lalu tunggu status selesai."
pause "Application baru sudah dideploy — tekan Enter."
say "Memeriksa health lewat hostname validasi..."
LIVE=$(curl -sS -o /dev/null -w '%{http_code}' "https://${VALIDATION_HOST}/api/health/live" || echo "000")
READY=$(curl -sS -o /dev/null -w '%{http_code}' "https://${VALIDATION_HOST}/api/health/ready" || echo "000")
printf '  %-12s %s\n' "live" "HTTP $LIVE"
printf '  %-12s %s\n' "ready" "HTTP $READY"
if [[ "$LIVE" == "200" && "$READY" == "200" ]]; then
  note "✓ liveness dan readiness hijau"
else
  warn "health belum hijau — readiness memeriksa Postgres dan volume upload."
  warn "Jangan lanjut ke wizard-09 sampai keduanya 200."
fi
say ""
say "Smoke test manual sebelum cutover (semua di $VALIDATION_HOST):"
step "Login dan logout dengan Akun Kepengurusan smoke test; periksa cookie sesi."
step "Baca dasbor dan pastikan data mengikuti Cakupan akun."
step "Buka foto Kader, logo Struktur, dan satu Artikel bergambar lama."
step "Bandingkan MIME/byte gambarnya, bukan sekadar status HTTP."
step "Unggah gambar sintetis, baca ulang byte-nya, lalu bersihkan lewat aplikasi."
step "Jalankan satu mutasi reversibel; buktikan cache invalidation dan audit benar."
step "Uji satu tenant dari network internal dengan header Host: <slug>.kammi.id."
say ""
warn "Kegagalan apa pun di sini: perbaiki SEBELUM masuk maintenance window."
warn "Sampai titik ini stack lama masih melayani trafik dan belum tersentuh."
note "Berikutnya: wizard-09-cutover-production.sh (maintenance window + flip domain)."

finish
