#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Tiket 03 (.scratch/cd-non-prod/issues/03-lingkungan-non-production-di-dokploy.md):
# mayoritas checklist ini berjalan lewat API Dokploy, bukan klik browser. Nama
# procedure dan skema body di bawah ditarik langsung dari OpenAPI spec resmi
# (github.com/Dokploy/dokploy, canary) + skema Drizzle-nya, bukan ditebak.
#
# Kredensial dibaca dari .env.local: DOKPLOY_NONPROD_URL, DOKPLOY_NONPROD_API_KEY,
# DOKPLOY_NONPROD_GHCR_PAT (lihat tiket 01). ENV_FILE wizard ini adalah
# .env.local yang sama, supaya `ask`/`_existing` bisa memakai nilai yang sudah ada.

ENV_FILE=".env.local"
REPO_SLUG="kammi-id/kammi-id"

# ── Klien HTTP tipis ke API Dokploy ─────────────────────────────────────────
# Base URL & auth: <host>/api/<router>.<procedure>, header x-api-key.
dokploy_get() {
  curl -sS "${DOKPLOY_NONPROD_URL%/}/api/$1" -H "x-api-key: $DOKPLOY_NONPROD_API_KEY"
}
dokploy_post() {
  curl -sS -X POST "${DOKPLOY_NONPROD_URL%/}/api/$1" \
    -H "x-api-key: $DOKPLOY_NONPROD_API_KEY" -H "Content-Type: application/json" \
    -d "$2"
}

# jq_err RESPONSE — print a tRPC error message if the response is one, else empty.
jq_err() { printf '%s' "$1" | jq -r '.message // empty' 2>/dev/null; }

# poll_status GETTER_PROC ID_FIELD ID_VALUE — poll application.one/postgres.one's
# applicationStatus (idle|running|done|error) until it settles or 5 minutes pass.
poll_status() {
  local proc="$1" id_field="$2" id_value="$3" waited=0 status=""
  while (( waited < 300 )); do
    status=$(dokploy_get "$proc?$id_field=$id_value" | jq -r '.applicationStatus // "unknown"')
    case "$status" in
      done) printf '\n'; note "status: done"; return 0 ;;
      error) printf '\n'; warn "status: error"; return 1 ;;
      *) printf '.'; sleep 5; waited=$((waited + 5)) ;;
    esac
  done
  printf '\n'; warn "timeout menunggu status (terakhir: $status)"; return 2
}

TOTAL_STAGES=12

banner "Tiket 03 — Lingkungan non-production di Dokploy"

# ── 1. Prasyarat ────────────────────────────────────────────────────────────
stage "Prasyarat"
say "Wizard ini memanggil API Dokploy langsung — sebagian besar bukan klik browser."
say "Prasyaratnya: tiket 01 selesai (DOKPLOY_NONPROD_URL, DOKPLOY_NONPROD_API_KEY,"
say "DOKPLOY_NONPROD_GHCR_PAT sudah ada di .env.local), dan 'jq' terpasang."
command -v jq >/dev/null 2>&1 || { warn "jq tidak ditemukan — pasang dulu (brew install jq)"; exit 1; }
set -a; source "$ENV_FILE"; set +a
for v in DOKPLOY_NONPROD_URL DOKPLOY_NONPROD_API_KEY DOKPLOY_NONPROD_GHCR_PAT; do
  [[ -n "${!v:-}" ]] || { warn "$v kosong di $ENV_FILE — selesaikan tiket 01 dulu"; exit 1; }
done
health=$(dokploy_get "settings.health")
[[ "$health" == '{"status":"ok"}' ]] || { warn "settings.health tidak sehat: $health"; exit 1; }
note "terhubung ke ${DOKPLOY_NONPROD_URL}"
ask GHCR_USERNAME "Username GitHub pemilik DOKPLOY_NONPROD_GHCR_PAT:"
write_env GHCR_USERNAME "$GHCR_USERNAME"
pause "Siap mulai provisioning?"

# ── 2. Project & environment ────────────────────────────────────────────────
stage "Project & environment"
say "project.create otomatis membuat satu environment 'production' bersamanya —"
say "tidak ada panggilan environment.create terpisah."
PROJECT_ID=$(_existing DOKPLOY_NONPROD_PROJECT_ID || true)
ENVIRONMENT_ID=$(_existing DOKPLOY_NONPROD_ENVIRONMENT_ID || true)
if [[ -n "$PROJECT_ID" && -n "$ENVIRONMENT_ID" ]]; then
  note "sudah ada dari run sebelumnya: project=$PROJECT_ID environment=$ENVIRONMENT_ID"
else
  ask PROJECT_NAME "Nama project di Dokploy:"
  : "${PROJECT_NAME:=kammi-staging}"
  confirm "Buat project '$PROJECT_NAME' lewat project.create?" || { warn "dibatalkan"; exit 1; }
  resp=$(dokploy_post "project.create" "$(jq -n --arg name "$PROJECT_NAME" '{name:$name}')")
  err=$(jq_err "$resp"); [[ -z "$err" ]] || { warn "project.create gagal: $err"; exit 1; }
  PROJECT_ID=$(printf '%s' "$resp" | jq -r '.project.projectId')
  ENVIRONMENT_ID=$(printf '%s' "$resp" | jq -r '.environment.environmentId')
  write_env DOKPLOY_NONPROD_PROJECT_ID "$PROJECT_ID"
  write_env DOKPLOY_NONPROD_ENVIRONMENT_ID "$ENVIRONMENT_ID"
  note "project=$PROJECT_ID environment=$ENVIRONMENT_ID"
fi

# ── 3. Registry credential (GHCR) ───────────────────────────────────────────
stage "Kredensial registry GHCR"
say "registry.create menyimpan PAT sekali; dipakai ulang tiap aplikasi berikutnya."
REGISTRY_ID=$(_existing DOKPLOY_NONPROD_REGISTRY_ID || true)
if [[ -n "$REGISTRY_ID" ]]; then
  note "sudah ada: registry=$REGISTRY_ID"
else
  confirm "Simpan PAT GHCR ($GHCR_USERNAME) sebagai registry credential?" || { warn "dibatalkan"; exit 1; }
  resp=$(dokploy_post "registry.create" "$(jq -n \
    --arg name "ghcr" --arg user "$GHCR_USERNAME" --arg pass "$DOKPLOY_NONPROD_GHCR_PAT" \
    '{registryName:$name, username:$user, password:$pass, registryUrl:"ghcr.io", registryType:"cloud", imagePrefix:null}')")
  err=$(jq_err "$resp"); [[ -z "$err" ]] || { warn "registry.create gagal: $err"; exit 1; }
  REGISTRY_ID=$(printf '%s' "$resp" | jq -r '.registryId')
  write_env DOKPLOY_NONPROD_REGISTRY_ID "$REGISTRY_ID"
  note "registry=$REGISTRY_ID"
fi
step "Verifikasi manual: buka panel Dokploy → Registry, pastikan kredensial GHCR ada."
open_url "${DOKPLOY_NONPROD_URL%/}/dashboard/settings/registry"
pause

# ── 4. Postgres ──────────────────────────────────────────────────────────────
stage "Postgres"
say "Versi disamakan dengan production (18.3) agar pg_dump production bisa direstore."
POSTGRES_ID=$(_existing DOKPLOY_NONPROD_POSTGRES_ID || true)
POSTGRES_APPNAME=$(_existing DOKPLOY_NONPROD_POSTGRES_APPNAME || true)
: "${POSTGRES_APPNAME:=kammi-staging-db}"
DB_NAME=$(_existing DOKPLOY_NONPROD_DB_NAME || true); : "${DB_NAME:=kammi_staging}"
DB_USER=$(_existing DOKPLOY_NONPROD_DB_USER || true); : "${DB_USER:=kammi_staging}"
DB_PASSWORD=$(_existing DOKPLOY_NONPROD_DB_PASSWORD || true)
[[ -n "$DB_PASSWORD" ]] || DB_PASSWORD=$(openssl rand -hex 16)
if [[ -n "$POSTGRES_ID" ]]; then
  note "sudah ada: postgres=$POSTGRES_ID (appName=$POSTGRES_APPNAME)"
else
  confirm "Buat Postgres 18.3 '$POSTGRES_APPNAME' di environment ini?" || { warn "dibatalkan"; exit 1; }
  resp=$(dokploy_post "postgres.create" "$(jq -n \
    --arg name "$POSTGRES_APPNAME" --arg appName "$POSTGRES_APPNAME" \
    --arg db "$DB_NAME" --arg user "$DB_USER" --arg pass "$DB_PASSWORD" --arg env "$ENVIRONMENT_ID" \
    '{name:$name, appName:$appName, databaseName:$db, databaseUser:$user, databasePassword:$pass, dockerImage:"postgres:18.3", environmentId:$env}')")
  err=$(jq_err "$resp"); [[ -z "$err" ]] || { warn "postgres.create gagal: $err"; exit 1; }
  POSTGRES_ID=$(printf '%s' "$resp" | jq -r '.postgresId')
  write_env DOKPLOY_NONPROD_POSTGRES_ID "$POSTGRES_ID"
  write_env DOKPLOY_NONPROD_POSTGRES_APPNAME "$POSTGRES_APPNAME"
  write_env DOKPLOY_NONPROD_DB_NAME "$DB_NAME"
  write_env DOKPLOY_NONPROD_DB_USER "$DB_USER"
  write_env DOKPLOY_NONPROD_DB_PASSWORD "$DB_PASSWORD"
  say "Menyalakan container Postgres (postgres.deploy)..."
  dokploy_post "postgres.deploy" "$(jq -n --arg id "$POSTGRES_ID" '{postgresId:$id}')" >/dev/null
  poll_status "postgres.one" "postgresId" "$POSTGRES_ID" || warn "cek panel Dokploy untuk detail galat"
fi

# ── 5. Application + Docker provider ────────────────────────────────────────
stage "Application — image dev-*"
CURRENT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "")
APPLICATION_ID=$(_existing DOKPLOY_NONPROD_APPLICATION_ID || true)
if [[ -n "$APPLICATION_ID" ]]; then
  note "sudah ada: application=$APPLICATION_ID"
else
  ask APP_NAME "Nama application di Dokploy:"; : "${APP_NAME:=kammi-staging}"
  confirm "Buat application '$APP_NAME' di environment ini?" || { warn "dibatalkan"; exit 1; }
  resp=$(dokploy_post "application.create" "$(jq -n --arg name "$APP_NAME" --arg env "$ENVIRONMENT_ID" \
    '{name:$name, environmentId:$env}')")
  err=$(jq_err "$resp"); [[ -z "$err" ]] || { warn "application.create gagal: $err"; exit 1; }
  APPLICATION_ID=$(printf '%s' "$resp" | jq -r '.applicationId')
  write_env DOKPLOY_NONPROD_APPLICATION_ID "$APPLICATION_ID"
  note "application=$APPLICATION_ID"
fi
say "Image ditandai sha-<commit>, sesuai keputusan spec (tag mengambang ditolak)."
warn "Pastikan commit yang mau di-deploy SUDAH di-push ke origin — CI hanya"
warn "menerbitkan image lewat event push, bukan pull_request."
ask IMAGE_TAG "Hanya bagian TAG-nya saja, tanpa ghcr.io/repo (contoh: sha-$CURRENT_SHA):"
: "${IMAGE_TAG:=sha-$CURRENT_SHA}"
IMAGE_TAG="${IMAGE_TAG#ghcr.io/$REPO_SLUG:}"   # jaga-jaga kalau human paste referensi penuh
FULL_IMAGE="ghcr.io/$REPO_SLUG:$IMAGE_TAG"
resp=$(dokploy_post "application.saveDockerProvider" "$(jq -n \
  --arg img "$FULL_IMAGE" --arg id "$APPLICATION_ID" \
  --arg user "$GHCR_USERNAME" --arg pass "$DOKPLOY_NONPROD_GHCR_PAT" \
  '{dockerImage:$img, applicationId:$id, username:$user, password:$pass, registryUrl:"ghcr.io"}')")
err=$(jq_err "$resp"); [[ -z "$err" ]] || { warn "saveDockerProvider gagal: $err"; exit 1; }
note "docker provider diset ke $FULL_IMAGE"

# ── 6. Volume mount ──────────────────────────────────────────────────────────
stage "Volume kammi-uploads"
say "mounts.create type=volume; volumeName dipakai apa adanya sebagai nama Docker volume di host."
ask UPLOADS_MOUNT_PATH "Path mount di dalam container (WORKDIR /app di Dockerfile):"
: "${UPLOADS_MOUNT_PATH:=/app/.uploads}"
write_env DOKPLOY_NONPROD_UPLOADS_MOUNT_PATH "$UPLOADS_MOUNT_PATH"
existing_mounts=$(dokploy_get "mounts.allNamedByApplicationId?applicationId=$APPLICATION_ID")
if printf '%s' "$existing_mounts" | jq -e '.[] | select(.volumeName == "kammi-uploads")' >/dev/null 2>&1; then
  note "mount kammi-uploads sudah ada"
else
  resp=$(dokploy_post "mounts.create" "$(jq -n --arg path "$UPLOADS_MOUNT_PATH" --arg id "$APPLICATION_ID" \
    '{type:"volume", volumeName:"kammi-uploads", mountPath:$path, serviceType:"application", serviceId:$id}')")
  err=$(jq_err "$resp"); [[ -z "$err" ]] || { warn "mounts.create gagal: $err"; exit 1; }
  note "volume kammi-uploads terpasang di $UPLOADS_MOUNT_PATH"
fi

# ── 7. Variabel lingkungan ──────────────────────────────────────────────────
stage "Variabel lingkungan aplikasi"
say "Disetel SEKALI di sini lewat API. Sesudah ini panel Dokploy jadi sumber"
say "kebenaran — CI tidak pernah memanggil application.saveEnvironment lagi."
DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${POSTGRES_APPNAME}:5432/${DB_NAME}"
ask_secret API_CO_ID_TOKEN "Token API_CO_ID_TOKEN (Enter pakai nilai lokal jika ada):"
ENV_BLOCK=$(printf 'DATABASE_URL=%s\nUPLOADS_DIR=%s\nAPI_CO_ID_TOKEN=%s\nRUN_MIGRATIONS=1\nDB_GUARD_ACK=1\n' \
  "$DATABASE_URL" "$UPLOADS_MOUNT_PATH" "$API_CO_ID_TOKEN")
resp=$(dokploy_post "application.saveEnvironment" "$(jq -n --arg id "$APPLICATION_ID" --arg env "$ENV_BLOCK" \
  '{applicationId:$id, env:$env, buildArgs:null, buildSecrets:null, createEnvFile:false}')")
err=$(jq_err "$resp"); [[ -z "$err" ]] || { warn "saveEnvironment gagal: $err"; exit 1; }
note "5 variabel tersetel (DATABASE_URL, UPLOADS_DIR, API_CO_ID_TOKEN, RUN_MIGRATIONS, DB_GUARD_ACK)"

# ── 8. Domain + TLS ──────────────────────────────────────────────────────────
stage "Domain staging"
ask STAGING_HOST "Subdomain staging (DNS-nya sudah diverifikasi di tiket 01):"
: "${STAGING_HOST:=staging.kammi.id}"
resp=$(dokploy_post "domain.create" "$(jq -n --arg host "$STAGING_HOST" --arg id "$APPLICATION_ID" \
  '{host:$host, port:3000, https:true, certificateType:"letsencrypt", applicationId:$id, domainType:"application"}')")
err=$(jq_err "$resp"); [[ -z "$err" ]] || { warn "domain.create gagal: $err"; exit 1; }
write_env DOKPLOY_NONPROD_STAGING_HOST "$STAGING_HOST"
note "domain $STAGING_HOST terpasang; sertifikat Let's Encrypt butuh waktu untuk terbit"

# ── 9. Deploy pertama & verifikasi skema ────────────────────────────────────
stage "Deploy pertama"
confirm "Deploy application sekarang (menarik ghcr.io/$REPO_SLUG:$IMAGE_TAG)?" || { warn "dibatalkan"; exit 1; }
dokploy_post "application.deploy" "$(jq -n --arg id "$APPLICATION_ID" '{applicationId:$id}')" >/dev/null
say "Menunggu status aplikasi..."
poll_status "application.one" "applicationId" "$APPLICATION_ID" || warn "cek application.readLogs di panel untuk detail"

say "Memeriksa sertifikat TLS (Let's Encrypt butuh waktu terbit, dicoba sampai 2 menit)..."
tls_ok=0
for _ in $(seq 1 24); do
  if issuer=$(openssl s_client -connect "${STAGING_HOST}:443" -servername "$STAGING_HOST" </dev/null 2>/dev/null \
      | openssl x509 -noout -issuer 2>/dev/null); then
    if [[ "$issuer" == *"Let's Encrypt"* ]]; then tls_ok=1; note "sertifikat: $issuer"; break; fi
  fi
  printf '.'; sleep 5
done
(( tls_ok )) || warn "sertifikat belum terbit lewat Let's Encrypt — cek DNS/challenge HTTP-01 di panel"

step "Buka subdomain — halaman harus menjawab. Ini bukti entrypoint tiket 02"
step "berhasil menjalankan migrasi (skema basis data terbentuk saat container menyala)."
open_url "https://${STAGING_HOST}"
confirm "Halaman menjawab dan skema sudah terbentuk?" || warn "tetap lanjut — perbaiki manual lewat panel bila perlu"

# ── 10. Izin volume lewat SSH ───────────────────────────────────────────────
stage "Izin volume (SSH manual)"
warn "Penyimpangan sadar dari ADR 0006: tanpa Compose, tidak ada init container ber-chown."
say "Aplikasi berjalan sebagai uid 1001; volume baru dimiliki root. SSH ke host Dokploy:"
step "1. Cari path asli volume: docker volume inspect kammi-uploads --format '{{.Mountpoint}}'"
step "2. Ubah pemilik:            sudo chown -R 1001:1001 <Mountpoint dari langkah 1>"
pause "Sudah dijalankan lewat SSH?"
step "Buktikan dengan unggahan sungguhan lewat aplikasi (bukan cuma melihat izin direktori)."
open_url "https://${STAGING_HOST}"
confirm "Unggahan gambar berhasil tersimpan dan bertahan setelah reload?" || warn "ulangi chown, lalu coba lagi"

# ── 11. Noindex staging ──────────────────────────────────────────────────────
stage "Staging tidak terindeks"
say "Belum ada mekanisme di kode aplikasi (tiket 02 tidak menambahkannya). Cara"
say "paling aman: Traefik config per-application di tab Advanced — bukan config"
say "Traefik instance-wide, supaya tidak menyentuh aplikasi lain di instance ini."
open_url "${DOKPLOY_NONPROD_URL%/}/dashboard/project/$PROJECT_ID/environment/$ENVIRONMENT_ID/services/application/$APPLICATION_ID"
step "Buka tab Advanced → Traefik Config."
step "Tambahkan middleware header X-Robots-Tag: noindex, nofollow, lalu pasang ke router domain $STAGING_HOST."
pause "Sudah dipasang?"
if command -v curl >/dev/null 2>&1; then
  resp_headers=$(curl -sSI "https://${STAGING_HOST}" | tr -d '\r')
  if grep -qi '^x-robots-tag:' <<<"$resp_headers"; then
    note "terverifikasi: header X-Robots-Tag ada"
  else
    warn "header X-Robots-Tag belum terlihat — cek lagi konfigurasi middleware"
  fi
fi

# ── 12. Rahasia GitHub ketiga ───────────────────────────────────────────────
stage "Rahasia GitHub: applicationId"
say "Melengkapi DOKPLOY_NONPROD_URL dan DOKPLOY_NONPROD_API_KEY dari tiket 01."
set_secret DOKPLOY_NONPROD_APPLICATION_ID "$APPLICATION_ID"

finish
