#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Tiket 05 (.scratch/cd-non-prod/issues/05-data-staging-dan-runbook.md), lihat
# juga ADR 0009. Dua artefak terpisah dipindahkan lewat mesin lokal sebagai
# perantara: basis data (pg_dump → pg_restore) dan gambar unggahan.
#
# Gambar: production BELUM migrasi ke volume Docker (ADR 0006 belum
# dijalankan di sana per sesi ini) — masih di RustFS (S3-compatible). RustFS
# TIDAK reachable dari luar (port publik & IP internal container sama-sama
# timeout dari mesin lokal; hidup hanya terverifikasi dari dalam docker
# network production sendiri). Jadi 'mc' dijalankan DI HOST production lewat
# SSH (docker run --network dokploy-network minio/mc), hasilnya ditarik ke
# lokal lewat tar-over-SSH — sisi push (lokal → staging) juga tar-over-SSH,
# sama seperti pola src/scripts/assets-pull.ts.
#
# Kredensial PRODUCTION sengaja TIDAK PERNAH ditulis ke ENV_FILE (write_env)
# — diketik ulang tiap kali wizard ini dijalankan, sama seperti
# PRODUCTION_ASSETS_HOST di assets-pull.ts. Mengecilkan blast radius kalau
# mesin lokal ini bocor; konsisten dengan ADR 0009: "tidak boleh ada kunci
# SSH permanen dari mesin non-production ke production".
#
# Kredensial NON-PRODUCTION (DOKPLOY_NONPROD_*) sudah ada di .env.local dari
# tiket 03/04 — dipakai apa adanya di sini, plus satu var baru
# (DOKPLOY_NONPROD_SSH_HOST) yang memang boleh disimpan karena bukan akses
# ke production.

ENV_FILE=".env.local"
REPO_SLUG="kammi-id/kammi-id"

# ── Klien HTTP tipis ke API Dokploy — diparameterkan base+key, karena skrip
#    ini bicara ke DUA instance (production dan non-production). ───────────
dokploy_get() { # BASE KEY PROC
  curl -sS "${1%/}/api/$3" -H "x-api-key: $2"
}
dokploy_post() { # BASE KEY PROC BODY
  curl -sS -X POST "${1%/}/api/$3" \
    -H "x-api-key: $2" -H "Content-Type: application/json" -d "$4"
}
jq_err() { printf '%s' "$1" | jq -r '.message // empty' 2>/dev/null; }

TOTAL_STAGES=11

banner "Tiket 05 — Data staging & runbook"

# ── 1. Prasyarat ────────────────────────────────────────────────────────────
stage "Prasyarat"
say "Wizard ini DESTRUKTIF: me-restore (--clean) Postgres staging dan menimpa"
say "volume kammi-uploads staging dengan salinan production. Bukan bagian"
say "pipeline deploy — dijalankan manual sesuai kebutuhan."
for c in jq ssh docker tar gh curl; do
  command -v "$c" >/dev/null 2>&1 || { warn "'$c' tidak ditemukan — pasang dulu"; exit 1; }
done
set -a; source "$ENV_FILE"; set +a
for v in DOKPLOY_NONPROD_URL DOKPLOY_NONPROD_API_KEY DOKPLOY_NONPROD_POSTGRES_ID \
         DOKPLOY_NONPROD_APPLICATION_ID DOKPLOY_NONPROD_DB_NAME DOKPLOY_NONPROD_DB_USER; do
  [[ -n "${!v:-}" ]] || { warn "$v kosong di $ENV_FILE — selesaikan tiket 03 dulu"; exit 1; }
done
note "non-production siap: ${DOKPLOY_NONPROD_URL}"
warn "Akses production TIDAK akan disimpan ke $ENV_FILE — diketik ulang tiap run."
pause "Siap mulai?"

# ── 2. Kredensial production Dokploy (tidak disimpan) ───────────────────────
stage "Kredensial production Dokploy"
say "Dipakai sekali untuk MEMBACA nama container Postgres lewat API — tidak"
say "pernah ditulis ke berkas."
ask PROD_URL "URL panel Dokploy production (mis. https://dokploy.kammi.id):"
ask_secret PROD_API_KEY "API key Dokploy production:"
health=$(dokploy_get "$PROD_URL" "$PROD_API_KEY" "settings.health")
[[ "$health" == '{"status":"ok"}' ]] || { warn "settings.health tidak sehat: $health"; exit 1; }
note "terhubung ke $PROD_URL"

# ── 3. Cari Postgres production ─────────────────────────────────────────────
stage "Cari Postgres production"
say "Buka panel, masuk ke project production, klik service Postgres-nya."
say "URL service biasanya berbentuk .../services/postgres/<ID> — salin <ID>."
open_url "${PROD_URL%/}/dashboard"
ask PROD_POSTGRES_ID "postgresId Postgres production:"
resp=$(dokploy_get "$PROD_URL" "$PROD_API_KEY" "postgres.one?postgresId=$PROD_POSTGRES_ID")
err=$(jq_err "$resp"); [[ -z "$err" ]] || { warn "postgres.one gagal: $err"; exit 1; }
# appName balik dari API adalah hostname/nama container sebenarnya — jangan
# pernah asumsikan sama dengan nama yang mungkin diminta saat provisioning
# (lihat memory "Dokploy appName Auto-Suffix").
PROD_APPNAME=$(printf '%s' "$resp" | jq -r '.appName')
PROD_DB_NAME_API=$(printf '%s' "$resp" | jq -r '.databaseName // empty')
PROD_DB_USER_API=$(printf '%s' "$resp" | jq -r '.databaseUser // empty')
[[ -n "$PROD_APPNAME" && "$PROD_APPNAME" != "null" ]] || { warn "appName kosong dari API"; exit 1; }
note "appName production: $PROD_APPNAME"
if [[ -n "$PROD_DB_NAME_API" ]]; then
  note "databaseName dari API: $PROD_DB_NAME_API · databaseUser: $PROD_DB_USER_API"
  PROD_DB_NAME="$PROD_DB_NAME_API"; PROD_DB_USER="$PROD_DB_USER_API"
else
  warn "API tidak mengembalikan databaseName/databaseUser — isi manual."
  ask PROD_DB_NAME "Nama database production:"
  ask PROD_DB_USER "User database production:"
fi

# ── 4. SSH ke production — ambil pg_dump ────────────────────────────────────
stage "pg_dump production (lewat mesin lokal)"
warn "Field ini belum pernah diverifikasi terhadap tooling host production —"
warn "lihat handoff tiket 05. Kalau perintah di bawah gagal, sesuaikan manual"
warn "lalu lanjutkan wizard (Ctrl-C aman, re-run mengulang dari sini)."
ask PROD_SSH_HOST "SSH target host production (user@host):"
ask PROD_SSH_KEY "Identity file untuk SSH ke production (kosongkan kalau tidak perlu -i, mis. ~/.ssh/kammi-id.pem):"
PROD_SSH_OPTS=(-o ServerAliveInterval=15 -o ServerAliveCountMax=10)
[[ -n "$PROD_SSH_KEY" ]] && PROD_SSH_OPTS+=(-i "${PROD_SSH_KEY/#\~/$HOME}")
say "Mencari nama container docker yang cocok dengan appName '$PROD_APPNAME'..."
CANDIDATES=$(ssh "${PROD_SSH_OPTS[@]}" "$PROD_SSH_HOST" "docker ps --filter name=$PROD_APPNAME --format '{{.Names}}'")
[[ -n "$CANDIDATES" ]] || { warn "tidak ada container docker bernama *$PROD_APPNAME* di $PROD_SSH_HOST"; exit 1; }
note "kandidat container:"
printf '%s\n' "$CANDIDATES" | sed 's/^/    /'
ask PROD_PG_CONTAINER "Nama container Postgres production yang benar (dari daftar di atas):"
DUMP_FILE=$(mktemp -t kammi-staging-refresh.XXXXXX.dump)
say "Menjalankan pg_dump di dalam container, hasil disalin ke $DUMP_FILE..."
ssh "${PROD_SSH_OPTS[@]}" "$PROD_SSH_HOST" \
  "docker exec $PROD_PG_CONTAINER pg_dump -Fc -U '$PROD_DB_USER' -d '$PROD_DB_NAME'" \
  > "$DUMP_FILE"
DUMP_BYTES=$(wc -c < "$DUMP_FILE" | tr -d ' ')
[[ "$DUMP_BYTES" -gt 0 ]] || { warn "dump kosong (0 byte) — cek kredensial/nama database"; exit 1; }
note "dump selesai: $DUMP_BYTES byte di $DUMP_FILE"

# ── 5. Restore ke Postgres staging ──────────────────────────────────────────
stage "Restore ke Postgres staging"
say "Membaca ulang appName Postgres staging dari API (jangan asumsikan dari"
say "$ENV_FILE tanpa verifikasi — appName Dokploy selalu disuffix acak)."
resp=$(dokploy_get "$DOKPLOY_NONPROD_URL" "$DOKPLOY_NONPROD_API_KEY" \
  "postgres.one?postgresId=$DOKPLOY_NONPROD_POSTGRES_ID")
err=$(jq_err "$resp"); [[ -z "$err" ]] || { warn "postgres.one (staging) gagal: $err"; exit 1; }
STAGING_APPNAME=$(printf '%s' "$resp" | jq -r '.appName')
note "appName staging: $STAGING_APPNAME"
ask DOKPLOY_NONPROD_SSH_HOST "SSH target host Dokploy non-production (user@host, dari tiket 03):"
write_env DOKPLOY_NONPROD_SSH_HOST "$DOKPLOY_NONPROD_SSH_HOST"
ask DOKPLOY_NONPROD_SSH_KEY "Identity file untuk SSH ke host staging (kosongkan kalau tidak perlu -i):"
write_env DOKPLOY_NONPROD_SSH_KEY "$DOKPLOY_NONPROD_SSH_KEY"
STAGING_SSH_OPTS=(-o ServerAliveInterval=15 -o ServerAliveCountMax=10)
[[ -n "$DOKPLOY_NONPROD_SSH_KEY" ]] && STAGING_SSH_OPTS+=(-i "${DOKPLOY_NONPROD_SSH_KEY/#\~/$HOME}")
CANDIDATES=$(ssh "${STAGING_SSH_OPTS[@]}" "$DOKPLOY_NONPROD_SSH_HOST" "docker ps --filter name=$STAGING_APPNAME --format '{{.Names}}'")
[[ -n "$CANDIDATES" ]] || { warn "tidak ada container docker bernama *$STAGING_APPNAME* di host staging"; exit 1; }
note "kandidat container:"
printf '%s\n' "$CANDIDATES" | sed 's/^/    /'
ask STAGING_PG_CONTAINER "Nama container Postgres staging yang benar (dari daftar di atas):"
confirm "RESTORE (--clean) $DUMP_BYTES byte ke database '$DOKPLOY_NONPROD_DB_NAME' di staging — lanjut?" \
  || { warn "dibatalkan"; exit 1; }
cat "$DUMP_FILE" | ssh "${STAGING_SSH_OPTS[@]}" "$DOKPLOY_NONPROD_SSH_HOST" \
  "docker exec -i $STAGING_PG_CONTAINER pg_restore --clean --if-exists --no-owner --no-privileges \
   -U '$DOKPLOY_NONPROD_DB_USER' -d '$DOKPLOY_NONPROD_DB_NAME'" \
  || warn "pg_restore melaporkan galat — beberapa objek 'does not exist' saat --if-exists NORMAL, tapi periksa baris lain"
rm -f "$DUMP_FILE"
note "restore selesai"

# ── 5b. Rekonsiliasi ledger migrasi ─────────────────────────────────────────
stage "Rekonsiliasi ledger migrasi drizzle"
say "pg_restore --clean menimpa drizzle.__drizzle_migrations staging dengan"
say "punya production. Kalau ledger production lebih pendek dari folder"
say "migrasi yang dibawa image (production belum rilis semua fitur dev), app"
say "akan CRASH-LOOP saat boot berikutnya (RUN_MIGRATIONS=1 mencoba menerapkan"
say "ulang migrasi yang 'belum tercatat' — padahal mungkin efeknya SUDAH ada"
say "di skema yang baru direstore, atau mungkin BENAR belum ada. Ini beda"
say "kasus, dan HARUS dibedakan satu per satu, bukan diasumsikan sekaligus."
DB_MIGRATIONS=$(cat <<SQLEOF | ssh "${STAGING_SSH_OPTS[@]}" "$DOKPLOY_NONPROD_SSH_HOST" \
  "docker exec -i '$STAGING_PG_CONTAINER' psql -t -A -U '$DOKPLOY_NONPROD_DB_USER' -d '$DOKPLOY_NONPROD_DB_NAME'"
select name from drizzle.__drizzle_migrations order by id;
SQLEOF
)
MISSING=()
for dir in src/db/__migrations/*/; do
  name=$(basename "$dir")
  [[ -f "${dir}migration.sql" ]] || continue
  grep -qxF "$name" <<< "$DB_MIGRATIONS" || MISSING+=("$name")
done
if (( ${#MISSING[@]} == 0 )); then
  note "ledger staging sudah lengkap — tidak ada yang perlu direkonsiliasi"
else
  warn "${#MISSING[@]} migrasi belum tercatat di ledger staging:"
  printf '  - %s\n' "${MISSING[@]}"
  say "Untuk TIAP SATU di bawah: baca SQL-nya, lalu VERIFIKASI LANGSUNG ke DB"
  say "staging (mis. \\d nama_tabel, atau select dari information_schema) apakah"
  say "efeknya SUDAH ada. JANGAN asumsikan dari migrasi lain yang mirip — kasus"
  say "nyata di tiket ini, 3 dari 7 migrasi yang 'terlihat serupa' ternyata BEDA"
  say "status (2 sudah ada, sisanya BENAR belum ada dan bikin app crash saat"
  say "reconcile sembarangan)."
  for name in "${MISSING[@]}"; do
    printf '\n  %s%s%s\n' "$BOLD" "$name" "$RESET"
    cat "src/db/__migrations/${name}/migration.sql" | sed 's/^/    /'
    if confirm "Sudah diverifikasi ke DB staging — efek SQL di atas SUDAH ada di skema?"; then
      HASH=$(shasum -a 256 "src/db/__migrations/${name}/migration.sql" | cut -d' ' -f1)
      DATEPART="${name:0:14}"
      MILLIS=$(date -u -j -f "%Y%m%d%H%M%S" "$DATEPART" "+%s000" 2>/dev/null \
        || date -u -d "${DATEPART:0:4}-${DATEPART:4:2}-${DATEPART:6:2} ${DATEPART:8:2}:${DATEPART:10:2}:${DATEPART:12:2}" "+%s000")
      ssh "${STAGING_SSH_OPTS[@]}" "$DOKPLOY_NONPROD_SSH_HOST" \
        "docker exec -i '$STAGING_PG_CONTAINER' psql -U '$DOKPLOY_NONPROD_DB_USER' -d '$DOKPLOY_NONPROD_DB_NAME' -c \"insert into drizzle.__drizzle_migrations (hash, created_at, name) values ('$HASH', $MILLIS, '$name');\""
      note "dicatat sebagai sudah diterapkan (tanpa menjalankan ulang SQL-nya)"
    else
      warn "dibiarkan TIDAK tercatat — akan benar-benar dijalankan drizzle-kit"
      warn "saat aplikasi redeploy berikutnya (RUN_MIGRATIONS=1). Ini yang benar"
      warn "kalau migrasinya memang belum pernah jalan."
    fi
  done
fi

# ── 6. Salin gambar dari RustFS production → volume staging ────────────────
stage "Salin gambar (RustFS production → volume staging)"
say "Production BELUM migrasi ke volume (ADR 0006 belum dijalankan di sana) —"
say "gambar masih di RustFS, S3-compatible. Kunci objek di bucket = kunci"
say "berkas di volume apa adanya (lihat LEGACY_ASSET_PREFIX di"
say "src/lib/utils/site-image.ts: bagian setelah 'kammiid/' di URL lama PERSIS"
say "kunci yang dipakai /api/images/*)."
warn "RustFS TIDAK reachable langsung dari mesin lokal — port publik"
warn "(assets.kammi.id:443) dan IP internal container sama-sama timeout dari"
warn "luar. Terverifikasi hidup HANYA dari dalam docker network production"
warn "sendiri (HTTP 403 tanpa kredensial). Jadi 'mc' dijalankan DI HOST"
warn "production lewat SSH (docker run --network dokploy-network), hasilnya"
warn "ditarik ke lokal lewat tar-over-SSH biasa — bukan mc lokal."
ask PROD_RUSTFS_BUCKET "Nama bucket (kemungkinan 'kammiid' — lihat ADR 0006, bukan 'kammiidz'):"
ask PROD_RUSTFS_ACCESS_KEY "Access key RustFS:"
ask_secret PROD_RUSTFS_SECRET_KEY "Secret key RustFS:"
ask PROD_DOCKER_NETWORK "Nama docker network tempat RustFS hidup (default dokploy-network):"
: "${PROD_DOCKER_NETWORK:=dokploy-network}"
TMP_UPLOADS=$(mktemp -d -t kammi-staging-uploads.XXXXXX)
REMOTE_PULL_DIR="/tmp/kammi-rustfs-pull-$$"
say "Menjalankan mc di dalam network '$PROD_DOCKER_NETWORK' di host production..."
ssh "${PROD_SSH_OPTS[@]}" "$PROD_SSH_HOST" \
  "mkdir -p '$REMOTE_PULL_DIR' && docker run --rm --network '$PROD_DOCKER_NETWORK' \
   -v '$REMOTE_PULL_DIR':/out \
   -e MC_HOST_prod='http://${PROD_RUSTFS_ACCESS_KEY}:${PROD_RUSTFS_SECRET_KEY}@rustfs:9000' \
   minio/mc:latest mirror --quiet prod/$PROD_RUSTFS_BUCKET /out"
say "Menarik hasilnya ke $TMP_UPLOADS lewat SSH..."
ssh "${PROD_SSH_OPTS[@]}" "$PROD_SSH_HOST" "tar cz -C '$REMOTE_PULL_DIR' ." | tar xz -C "$TMP_UPLOADS"
ssh "${PROD_SSH_OPTS[@]}" "$PROD_SSH_HOST" "rm -rf '$REMOTE_PULL_DIR'"
note "berkas sementara di host production sudah dibersihkan"
LOCAL_COUNT=$(find "$TMP_UPLOADS" -type f | wc -l | tr -d ' ')
LOCAL_BYTES=$(find "$TMP_UPLOADS" -type f -exec cat {} + 2>/dev/null | wc -c | tr -d ' ')
note "tertarik: $LOCAL_COUNT berkas, $LOCAL_BYTES byte"
confirm "Timpa volume kammi-uploads di STAGING dengan $LOCAL_COUNT berkas ini?" \
  || { warn "dibatalkan"; exit 1; }
say "Mengosongkan lalu mengisi ulang volume staging..."
ssh "${STAGING_SSH_OPTS[@]}" "$DOKPLOY_NONPROD_SSH_HOST" "docker run --rm -v kammi-uploads:/d -w /d alpine sh -c 'rm -rf /d/* /d/.[!.]* 2>/dev/null || true'"
# COPYFILE_DISABLE=1: tanpa ini, bsdtar di macOS menyisipkan sidecar
# AppleDouble '._namafile' untuk berkas berxattr — dua kali lipat jumlah
# berkas di tujuan dan bikin verifikasi byte/jumlah di stage berikut gagal
# padahal datanya sendiri utuh. Ditemukan langsung saat menjalankan ini.
COPYFILE_DISABLE=1 tar cz -C "$TMP_UPLOADS" . | ssh "${STAGING_SSH_OPTS[@]}" "$DOKPLOY_NONPROD_SSH_HOST" \
  "docker run --rm -i -v kammi-uploads:/d -w /d alpine tar xz"
# Container alpine di atas jalan sebagai root, jadi isi volume yang baru
# ditulis kembali dimiliki root — sementara aplikasi jalan sebagai uid 1001
# (spec.md, "Izin volume"). Tanpa baris ini app dapat Permission denied
# membaca foldernya sendiri dan /api/images/* jatuh ke placeholder walau
# datanya benar. Ditemukan langsung: kejadian nyata di sesi yang menulis ini.
ssh "${STAGING_SSH_OPTS[@]}" "$DOKPLOY_NONPROD_SSH_HOST" "docker run --rm -v kammi-uploads:/d alpine chown -R 1001:1001 /d"
note "volume staging disegarkan, ownership dikembalikan ke uid 1001"

# ── 7. Verifikasi kunci gambar (jumlah objek & byte) ────────────────────────
stage "Verifikasi salinan volume"
say "Bukan sekilas — dihitung berkas dan total byte di kedua sisi."
REMOTE_STATS=$(ssh "${STAGING_SSH_OPTS[@]}" "$DOKPLOY_NONPROD_SSH_HOST" \
  "docker run --rm -v kammi-uploads:/d alpine sh -c \"find /d -type f | wc -l; find /d -type f -exec cat {} + 2>/dev/null | wc -c\"")
REMOTE_COUNT=$(printf '%s\n' "$REMOTE_STATS" | sed -n '1p' | tr -d ' ')
REMOTE_BYTES=$(printf '%s\n' "$REMOTE_STATS" | sed -n '2p' | tr -d ' ')
printf '  %-22s %10s berkas %14s byte\n' "lokal (dari production)" "$LOCAL_COUNT" "$LOCAL_BYTES"
printf '  %-22s %10s berkas %14s byte\n' "staging (setelah push)" "$REMOTE_COUNT" "$REMOTE_BYTES"
if [[ "$LOCAL_COUNT" == "$REMOTE_COUNT" && "$LOCAL_BYTES" == "$REMOTE_BYTES" ]]; then
  note "✓ cocok persis"
else
  warn "TIDAK COCOK — penyalinan mungkin gagal sebagian. Jangan lanjut tanpa investigasi."
fi
rm -rf "$TMP_UPLOADS"

# ── 8. Verifikasi dengan mata ───────────────────────────────────────────────
stage "Verifikasi dengan mata"
say "Tiga halaman, buka satu-satu dan periksa gambarnya benar-benar muncul."
step "Foto Kader di halaman publik:"
open_url "https://${DOKPLOY_NONPROD_STAGING_HOST}/tentang/pengurus"
confirm "Foto Kader muncul (bukan placeholder)?" || warn "dicatat sebagai belum terverifikasi"
step "Logo Struktur di dasbor:"
open_url "https://${DOKPLOY_NONPROD_STAGING_HOST}/dashboard/organization"
confirm "Logo Struktur muncul?" || warn "dicatat sebagai belum terverifikasi"
step "Artikel bergambar:"
open_url "https://${DOKPLOY_NONPROD_STAGING_HOST}/berita"
confirm "Ada Artikel dengan gambar utuh?" || warn "dicatat sebagai belum terverifikasi"

# ── 9. Rollback — tulis & buktikan ──────────────────────────────────────────
stage "Rollback — buktikan bekerja"
say "Rollback = jalankan skrip deploy CI yang sama, dari lokal, dengan sha lama."
say "Mencari dua commit dengan image ghcr.io yang sudah TERBUKTI ter-build,"
say "lewat riwayat run CI — bukan menebak dari git log lokal (dua commit"
say "terbaru di branch ini belum di-push, jadi belum punya image)."
RUNS=$(gh run list --workflow=ci.yml --json headSha,conclusion,event,headBranch -L 30)
SHAS=$(printf '%s' "$RUNS" | jq -r '.[] | select(.conclusion=="success" and .event=="push" and (.headBranch|test("^dev-"))) | .headSha' | awk '!seen[$0]++')
CURRENT_SHA=$(printf '%s\n' "$SHAS" | sed -n '1p')
ROLLBACK_SHA=$(printf '%s\n' "$SHAS" | sed -n '2p')
if [[ -z "$CURRENT_SHA" || -z "$ROLLBACK_SHA" ]]; then
  warn "kurang dari dua run CI sukses ditemukan — isi manual (harus commit yang sudah di-push & lolos CI):"
  ask CURRENT_SHA "sha 'saat ini' (lengkap atau pendek):"
  ask ROLLBACK_SHA "sha 'sebelumnya' untuk rollback:"
fi
note "current=${CURRENT_SHA:0:7} rollback=${ROLLBACK_SHA:0:7}"
confirm "Deploy ${CURRENT_SHA:0:7} ke staging dulu (baseline)?" || { warn "dibatalkan"; exit 1; }
GITHUB_SHA="$CURRENT_SHA" GITHUB_REPOSITORY="$REPO_SLUG" bun run deploy:nonprod
note "✓ baseline ${CURRENT_SHA:0:7} hidup di staging"
confirm "Sekarang ROLLBACK ke ${ROLLBACK_SHA:0:7} untuk membuktikan prosedurnya — lanjut?" \
  || { warn "dibatalkan — rollback TIDAK terbukti, checklist tiket tetap kosong di item ini"; exit 1; }
GITHUB_SHA="$ROLLBACK_SHA" GITHUB_REPOSITORY="$REPO_SLUG" bun run deploy:nonprod
note "✓ rollback ke ${ROLLBACK_SHA:0:7} berhasil — prosedur terbukti bekerja"
if confirm "Kembalikan staging ke ${CURRENT_SHA:0:7} (disarankan)?"; then
  GITHUB_SHA="$CURRENT_SHA" GITHUB_REPOSITORY="$REPO_SLUG" bun run deploy:nonprod
  note "staging dikembalikan ke ${CURRENT_SHA:0:7}"
fi
ROLLBACK_PROVEN_DATE=$(date +%Y-%m-%d)

# ── 10. Tidak ada kunci SSH tertinggal + tulis README ───────────────────────
stage "Kunci SSH & tulis README"
warn "Cek sadar, bukan otomatis (memeriksa authorized_keys production dari sini"
warn "berarti SSH ke production lagi tanpa perlu — bertentangan dengan tujuannya)."
step "Pastikan tidak ada 'ssh-copy-id' atau kunci baru yang ditambahkan ke"
step "production selama sesi ini — hanya kunci pribadi Anda yang sudah ada"
step "sebelumnya yang dipakai, dan itu tidak pernah disalin ke host staging."
confirm "Dikonfirmasi: tidak ada kunci SSH baru non-production → production?" \
  || warn "PERIKSA ULANG sebelum menganggap tiket ini selesai"

README_SECTION=$(cat <<EOF

## Data staging & rollback

Staging (\`https://${DOKPLOY_NONPROD_STAGING_HOST}\`) diisi salinan data
production, bukan seed — lihat
[ADR 0009](docs/adr/0009-staging-membawa-data-production.md). Penyegarannya
manual dan sesuai kebutuhan, **bukan** bagian pipeline deploy (deploy tetap
berdurasi detik dan tidak pernah menjalankan operasi destruktif otomatis).

### Menyegarkan data staging

\`\`\`bash
bash .scratch/cd-non-prod/wizard-05-data-staging-dan-runbook.sh
\`\`\`

Me-restore \`pg_dump\` production ke Postgres staging (\`--clean --if-exists\`)
dan menimpa volume \`kammi-uploads\` staging dengan gambar production, keduanya
lewat mesin lokal sebagai perantara — tidak ada kunci SSH permanen
non-production → production. Gambar masih di RustFS (production belum
migrasi ke volume, ADR 0006), dan RustFS tidak reachable langsung dari luar —
\`mc\` dijalankan DI HOST production lewat SSH (\`docker run --network
dokploy-network minio/mc\`), hasilnya ditarik ke lokal lewat tar-over-SSH,
persis pola \`assets-pull.ts\`. Begitu production migrasi ke volume, seluruh
langkah \`mc\` ini bisa diganti tar-over-SSH langsung seperti sisi staging.
Verifikasi objek/byte dan verifikasi mata (foto Kader, logo Struktur, Artikel
bergambar) berjalan di dalam wizard yang sama.

**Dua gotcha nyata yang wizard ini sudah tangani, tapi baca dulu kalau nulis
ulang skripnya:**

1. **Ledger migrasi drizzle ikut ketimpa restore.** \`pg_restore --clean\`
   menimpa \`drizzle.__drizzle_migrations\` staging dengan punya production —
   kalau production belum rilis migrasi tertentu (atau ledgernya sendiri
   bolong dari awal), redeploy berikutnya (\`RUN_MIGRATIONS=1\`) bisa
   crash-loop. Wizard mem-verifikasi TIAP migrasi yang "hilang" satu per satu
   sebelum mencatatnya sebagai sudah diterapkan — jangan pernah
   generalisasi dari sampel, lihat memory \`adr0009-migration-ledger-gotcha\`
   untuk insiden nyatanya (3 dari 7 migrasi ternyata BENAR belum diterapkan
   di production, bukan cuma belum tercatat).
2. **Container yang menulis volume (alpine tar/mc) jalan sebagai root**,
   sementara aplikasi jalan sebagai uid 1001 — tiap kali volume ditulis
   ulang, ownership harus dikembalikan (\`chown -R 1001:1001\`) atau
   \`/api/images/*\` jatuh ke placeholder walau datanya benar.

### Rollback staging ke sha sebelumnya

Sama seperti CI, tapi dijalankan dari mesin lokal dengan sha lama:

\`\`\`bash
GITHUB_SHA=<sha> GITHUB_REPOSITORY=${REPO_SLUG} bun run deploy:nonprod
\`\`\`

Image \`ghcr.io/${REPO_SLUG}:sha-<7char>\` harus sudah pernah dibangun CI
(commit-nya sudah di-push sebelumnya) — sha yang belum pernah di-push tidak
punya image untuk ditarik. Terverifikasi bekerja: ${ROLLBACK_PROVEN_DATE},
${CURRENT_SHA:0:7} → ${ROLLBACK_SHA:0:7} → ${CURRENT_SHA:0:7}.
EOF
)
if grep -q '^## Data staging & rollback$' README.md 2>/dev/null; then
  note "README.md sudah punya bagian ini dari run sebelumnya — tidak ditulis ulang otomatis."
  warn "Perbarui manual bagian '## Data staging & rollback' di README.md bila perlu."
else
  printf '%s\n' "$README_SECTION" >> README.md
  note "✓ ditambahkan bagian '## Data staging & rollback' ke README.md"
fi
say "Tinjau diff-nya sebelum commit:"
step "git diff -- README.md"

finish
