#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# Issue 04 (form artikel dua kolom dan Galeri): satu kolom baru,
# `article.gallery_images text[] not null default '{}'`. ADR 0008: production
# tetap manual, dan `db-guard` (src/lib/db-guard/) menolak DATABASE_URL yang
# bukan localhost kecuali operator manusia mengetik ulang nama basis data di
# prompt interaktifnya. Wizard ini TIDAK menyetel DB_GUARD_ACK atau bentuk
# bypass lain — migrasi dijalankan lewat SSH dengan TTY sungguhan supaya
# prompt db-guard itu benar-benar menggerbangi eksekusinya, persis kebijakan
# yang dicatat ADR itu.
#
# Container yang dieksekusi adalah container APLIKASI production yang sudah
# jalan (bukan container Postgres) — image stage `runner`-nya sudah membawa
# `drizzle-kit` dan `src/db/__migrations` (ADR 0008), jadi tidak perlu image
# atau container baru sama sekali.

TOTAL_STAGES=5

MIGRATION_DIR="20260829210747_huge_lockjaw"
MIGRATION_SQL_PATH="src/db/__migrations/${MIGRATION_DIR}/migration.sql"

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/../.." && pwd)
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.env.migrasi-galeri}"

cd "$REPO_ROOT"
banner "Migrasi production — gallery_images pada article"

# ── 1 ───────────────────────────────────────────────────────────────────────
stage "Prasyarat"
for c in ssh; do
  command -v "$c" >/dev/null 2>&1 || { warn "'$c' tidak ditemukan"; exit 1; }
done
if [[ ! -f "$MIGRATION_SQL_PATH" ]]; then
  warn "$MIGRATION_SQL_PATH tidak ditemukan — jalankan wizard ini dari checkout"
  warn "yang sudah membawa commit skema tiket 04 (berita-polish)."
  exit 1
fi
say "SQL yang akan dijalankan drizzle-kit di production:"
sed 's/^/    /' "$MIGRATION_SQL_PATH"
note "Satu baris ALTER TABLE, menambah kolom baru dengan DEFAULT — tidak"
note "mengunci baca/tulis lama pada tabel article dan tidak mengubah kolom apa pun yang sudah ada."
umask 077
if ! confirm "Sudah ada backup production yang cukup baru (lihat wizard-04-provision-project-production-baru.sh untuk jadwal backup terpasang)?"; then
  warn "Ambil backup dulu sebelum lanjut — jangan improvisasi di sini."
  exit 1
fi

# ── 2 ───────────────────────────────────────────────────────────────────────
stage "Sambungan ke host production"
ask SSH_HOST "SSH target host production (user@host):"
ask SSH_KEY "Identity file SSH (mis. ~/.ssh/kammi-id.pem):"
SSH_OPTS=(-o ServerAliveInterval=15 -o ServerAliveCountMax=10)
if [[ -n "$SSH_KEY" ]]; then
  SSH_OPTS+=(-i "${SSH_KEY/#\~/$HOME}")
fi
ssh_prod() { ssh "${SSH_OPTS[@]}" "$SSH_HOST" "$@"; }
if ! ssh_prod "echo ok" >/dev/null 2>&1; then
  warn "tidak bisa SSH ke $SSH_HOST"; exit 1
fi
note "SSH ke $SSH_HOST — ok"
ask PROD_APP_CONTAINER "Nama container APLIKASI production (docker ps di host, bukan Postgres):"
if ! ssh_prod "docker exec '$PROD_APP_CONTAINER' true" >/dev/null 2>&1; then
  warn "container '$PROD_APP_CONTAINER' tidak ditemukan/tidak jalan di $SSH_HOST"
  exit 1
fi
note "container $PROD_APP_CONTAINER — ok"

# ── 3 ───────────────────────────────────────────────────────────────────────
stage "Jalankan migrasi — interaktif, db-guard yang menggerbangi"
warn "Langkah ini membuka sesi interaktif SUNGGUHAN di terminal antum."
say "db-guard akan meminta antum mengetik ULANG nama basis data production"
say "sebagai konfirmasi (src/lib/db-guard/consent.ts) — bukan wizard ini yang"
say "memutuskan, TTY antum sendiri yang menjawabnya."
pause "Siap? Enter untuk membuka sesi."
if ssh -t "${SSH_OPTS[@]}" "$SSH_HOST" \
    "docker exec -it '$PROD_APP_CONTAINER' sh -c 'bun src/scripts/db-guard.ts && drizzle-kit migrate'"; then
  note "drizzle-kit migrate selesai tanpa error"
else
  warn "migrasi GAGAL atau dibatalkan (db-guard menolak / drizzle-kit error)."
  warn "Baca pesan di atas sebelum mengulang — jangan langsung retry membabi buta."
  exit 1
fi

# ── 4 ───────────────────────────────────────────────────────────────────────
stage "Verifikasi kolom baru benar-benar ada"
say "Jalankan drizzle-kit migrate SEKALI LAGI, non-interaktif — idempoten"
say "(jurnal drizzle), jadi kalau kolomnya sudah ada ia hanya melapor nihil."
if ssh_prod "docker exec '$PROD_APP_CONTAINER' sh -c 'bun src/scripts/db-guard.ts && drizzle-kit migrate'" \
    < /dev/null > /tmp/migrasi-galeri-verify.log 2>&1; then
  note "re-run bersih — lihat /tmp/migrasi-galeri-verify.log kalau perlu detail"
else
  warn "re-run non-interaktif gagal — db-guard menolak tanpa TTY, ini WAJAR."
  warn "Itu sendiri bukan tanda migrasi stage 3 gagal. Verifikasi manual:"
  say "  docker exec $PROD_APP_CONTAINER sh -c \\"
  say "    \"bun -e \\\"import{db}from './src/db/db';console.log(await db.execute(\`select column_name from information_schema.columns where table_name='article' and column_name='gallery_images'\`))\\\"\""
  confirm "Kolom gallery_images terkonfirmasi ada lewat query manual di atas?" \
    || { warn "belum terverifikasi — jangan tutup wizard sebagai selesai"; exit 1; }
fi

# ── 5 ───────────────────────────────────────────────────────────────────────
stage "Selesai"
write_env MIGRATION_APPLIED_AT "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
finish
say "Deploy kode yang memakai gallery_images (form artikel dua kolom + Galeri)"
say "boleh menyusul kapan pun setelah ini — kolomnya sudah siap dibaca/ditulis."
