server {
  listen 8080 default_server;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /healthz {
    access_log off;
    default_type text/plain;
    try_files /healthz =500;
  }

  location / {
    try_files /index.html =404;
  }
}
