#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

SITE_URL="https://www.kammi.id"
APEX_DOMAIN="kammi.id"
ROBOTS_URL="${SITE_URL}/robots.txt"

# name|user-agent pairs — bash 3.2 (macOS default) has no associative arrays.
BOT_CHECKS=(
  "OAI-SearchBot|OAI-SearchBot/1.0; +https://openai.com/searchbot"
  "PerplexityBot|PerplexityBot/1.0; +https://docs.perplexity.ai/guides/bots"
  "ClaudeBot|Mozilla/5.0 (compatible; ClaudeBot/1.0; +claudebot@anthropic.com)"
  "Googlebot|Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
  "facebookexternalhit|facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
)
# these three must NOT be 403 — ADR 0023 opens both training and retrieval
# bots, so it doesn't matter that ClaudeBot (training) sits next to
# OAI-SearchBot/PerplexityBot (retrieval) here: none of the three may 403.
AI_BOTS_MUST_OPEN=("OAI-SearchBot" "PerplexityBot" "ClaudeBot")

# bot_ua NAME — look up the UA string for NAME in BOT_CHECKS.
bot_ua() {
  local name="$1" pair
  for pair in "${BOT_CHECKS[@]}"; do
    if [[ "${pair%%|*}" == "$name" ]]; then
      printf '%s' "${pair#*|}"
      return 0
    fi
  done
  return 1
}

# bot_status NAME — HTTP status code SITE_URL/ returns for that bot's UA.
# Prints 000 on any curl failure (timeout, DNS, etc).
bot_status() {
  local name="$1" ua code
  ua=$(bot_ua "$name") || { printf '000'; return; }
  code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 20 -A "$ua" "${SITE_URL}/" 2>/dev/null) || code="000"
  printf '%s' "$code"
}

# print_bot_table — the verification table the ticket asks for, plus a
# pass/fail verdict. Returns 1 if any AI retrieval bot is 403 or if
# facebookexternalhit isn't 200.
print_bot_table() {
  local name code fail=0 mark pair
  printf '\n  %-22s %-4s %s\n' "User-Agent" "HTTP" "OK?"
  printf '  %-22s %-4s %s\n' "----------------------" "----" "---"
  for pair in "${BOT_CHECKS[@]}"; do
    name="${pair%%|*}"
    code=$(bot_status "$name")
    mark="${GREEN}✓${RESET}"
    if [[ "$name" == "facebookexternalhit" ]]; then
      [[ "$code" == "200" ]] || { mark="${RED}✗${RESET}"; fail=1; }
    else
      for ai in "${AI_BOTS_MUST_OPEN[@]}"; do
        [[ "$name" == "$ai" && "$code" == "403" ]] && { mark="${RED}✗${RESET}"; fail=1; }
      done
    fi
    printf '  %-22s %-4s %s\n' "$name" "$code" "$mark"
  done
  printf '\n'
  return "$fail"
}

for c in curl dig; do
  command -v "$c" >/dev/null 2>&1 || { echo "'$c' tidak ditemukan — wajib untuk wizard ini." >&2; exit 1; }
done

banner "Buka crawler AI, daftarkan alat ukur"

# ── 1 ───────────────────────────────────────────────────────────────────────
stage "Prasyarat dan konteks"
say "Empat langkah di bawah cuma bisa dikerjakan manusia — semuanya di"
say "dashboard pihak ketiga (Cloudflare, Google Search Console, Bing). Wizard"
say "ini memandu tiap langkah lalu membuktikan sendiri hasilnya lewat curl."
note "Domain uji: $SITE_URL"
say ""
warn "Selama OAI-SearchBot dijawab 403, seluruh polesan SEO di repo ini"
warn "memoles halaman yang tidak sampai ke penanyanya (lihat ADR 0023)."
say ""
say "Bot pengambil (OAI-SearchBot, PerplexityBot, Claude-SearchBot/-User)"
say "mengambil konten SAAT seseorang bertanya ke ChatGPT/Perplexity/Claude —"
say "menolaknya berarti KAMMI tidak pernah dikutip. Bot pelatih (GPTBot,"
say "ClaudeBot, Google-Extended, dst.) mengumpulkan data latih model. ADR 0023"
say "membuka KEDUANYA secara sadar — Struktur adalah gerakan dakwah, isinya"
say "diterbitkan untuk tersebar, bukan ditahan."
pause "Paham bedanya? Enter untuk mulai."

# ── 2 ───────────────────────────────────────────────────────────────────────
stage "Cloudflare — matikan blokir AI Crawl Control"
CF_OAI=$(bot_status "OAI-SearchBot")
CF_PPX=$(bot_status "PerplexityBot")
CF_CLAUDE=$(bot_status "ClaudeBot")
if [[ "$CF_OAI" != "403" && "$CF_PPX" != "403" && "$CF_CLAUDE" != "403" ]]; then
  note "OAI-SearchBot=$CF_OAI PerplexityBot=$CF_PPX ClaudeBot=$CF_CLAUDE — sudah tidak diblokir. Lewati."
else
  say "Setidaknya satu bot AI masih 403 (OAI-SearchBot=$CF_OAI PerplexityBot=$CF_PPX ClaudeBot=$CF_CLAUDE)."
  open_url "https://dash.cloudflare.com/"
  step "Pilih akun, lalu domain $APEX_DOMAIN."
  step "Buka Security → Bots → AI Crawl Control."
  step "Matikan blokir untuk KEDUA kategori: bot pelatih (training) dan bot"
  step "  pengambil/asisten (retrieval). ADR 0023: keduanya dibuka sengaja."
  pause "Sudah dimatikan? Enter untuk cek ulang."
  CF_OAI=$(bot_status "OAI-SearchBot")
  CF_PPX=$(bot_status "PerplexityBot")
  CF_CLAUDE=$(bot_status "ClaudeBot")
  if [[ "$CF_OAI" != "403" && "$CF_PPX" != "403" && "$CF_CLAUDE" != "403" ]]; then
    note "OAI-SearchBot=$CF_OAI PerplexityBot=$CF_PPX ClaudeBot=$CF_CLAUDE — lolos sekarang."
  else
    warn "Masih 403 untuk sebagian bot. Cloudflare kadang butuh waktu untuk"
    warn "menerapkan perubahan, atau ada rule WAF terpisah yang menahannya."
    warn "Stage 6 akan memverifikasi ulang secara menyeluruh sebelum wizard ini selesai."
  fi
fi

# ── 3 ───────────────────────────────────────────────────────────────────────
stage "Cloudflare — selaraskan Content Signals ke ai-train=yes"
ROBOTS_NOW=$(curl -sS --max-time 20 "$ROBOTS_URL" 2>/dev/null || true)
if grep -qi "ai-train=yes" <<<"$ROBOTS_NOW"; then
  note "robots.txt sudah menyatakan ai-train=yes. Lewati."
else
  say "robots.txt saat ini menyatakan Content-Signal dengan ai-train=no —"
  say "bertentangan dengan langkah 2 di atas kalau dibiarkan."
  open_url "https://dash.cloudflare.com/"
  step "Domain $APEX_DOMAIN → Security → Bots (bagian Content Signals, satu"
  step "  panel dengan AI Crawl Control)."
  step "Ubah sinyal ai-train dari 'no' menjadi 'yes'."
  pause "Sudah diubah? Enter untuk cek ulang."
  ROBOTS_NOW=$(curl -sS --max-time 20 "$ROBOTS_URL" 2>/dev/null || true)
  if grep -qi "ai-train=yes" <<<"$ROBOTS_NOW"; then
    note "robots.txt sekarang menyatakan ai-train=yes."
  else
    warn "robots.txt masih belum menyatakan ai-train=yes — mungkin cache"
    warn "propagasi Cloudflare. Stage 6 memverifikasi ulang di akhir."
  fi
fi

# ── 4 ───────────────────────────────────────────────────────────────────────
stage "Google Search Console — properti Domain ($APEX_DOMAIN)"
EXISTING_TXT=$(dig +short TXT "$APEX_DOMAIN" 2>/dev/null | grep -i "google-site-verification" || true)
if [[ -n "$EXISTING_TXT" ]]; then
  note "Sudah ada TXT google-site-verification di DNS $APEX_DOMAIN:"
  note "  $EXISTING_TXT"
  if confirm "GSC sudah menampilkan properti ini sebagai terverifikasi — lewati langkah ini?"; then
    :
  else
    say "Lanjutkan langkah di bawah untuk menuntaskan verifikasinya."
    EXISTING_TXT=""
  fi
fi
if [[ -z "$EXISTING_TXT" ]]; then
  say "Properti Domain (bukan Prefiks URL) mencakup SELURUH subdomain"
  say "sekaligus — tidak ada Struktur yang perlu didaftarkan satu per satu,"
  say "dan ini prasyarat sitemap index lintas subdomain (tiket 05)."
  open_url "https://search.google.com/search-console"
  step "Add property → tab 'Domain' (bukan 'URL prefix')."
  step "Masukkan: $APEX_DOMAIN (tanpa https://, tanpa www)."
  step "GSC menampilkan satu TXT record (diawali google-site-verification=)."
  step "  Salin nilainya."
  ask GSC_TXT_VALUE "Tempel nilai TXT record dari GSC di sini (tidak disimpan ke berkas):"
  open_url "https://dash.cloudflare.com/"
  step "Domain $APEX_DOMAIN → DNS → Records → Add record."
  step "Type: TXT · Name: @ · Content: nilai yang ditempel di atas · Proxy status: DNS only."
  pause "Sudah disimpan di Cloudflare? Enter untuk cek propagasi DNS."
  if dig +short TXT "$APEX_DOMAIN" 2>/dev/null | grep -qF "${GSC_TXT_VALUE#google-site-verification=}"; then
    note "TXT record sudah terlihat di DNS publik."
  else
    warn "TXT record belum terlihat lewat dig — propagasi DNS bisa makan"
    warn "beberapa menit. Tunggu sebentar sebelum klik Verify di GSC."
  fi
  step "Kembali ke tab GSC, klik Verify."
  confirm "GSC menampilkan properti $APEX_DOMAIN sebagai terverifikasi?" \
    || warn "Belum terverifikasi — ulangi wizard ini nanti, stage ini akan mendeteksi TXT record yang sudah ada."
fi

# ── 5 ───────────────────────────────────────────────────────────────────────
stage "Bing Webmaster Tools — impor dari GSC, nyalakan IndexNow"
if confirm "$APEX_DOMAIN sudah muncul di Bing Webmaster Tools DAN IndexNow sudah aktif — lewati langkah ini?"; then
  :
else
  say "Bing bukan opsional: ia mesin di balik pencarian ChatGPT, dan panel"
  say "AI Performance-nya satu-satunya alat first-party GRATIS yang menghitung"
  say "sitasi AI per halaman."
  open_url "https://www.bing.com/webmasters"
  step "Import dari Google Search Console (jalur tercepat) — pilih properti"
  step "  $APEX_DOMAIN, setujui izin akun Google, lalu Import."
  step "Setelah situs muncul di daftar, cek panel 'AI Performance' di sidebar."
  open_url "https://dash.cloudflare.com/"
  step "Domain $APEX_DOMAIN → cari toggle IndexNow (di bagian Speed atau"
  step "  Crawler Hints) dan nyalakan. Satu klik — jangan tulis kode ping sendiri."
  confirm "$APEX_DOMAIN sekarang muncul di Bing Webmaster Tools dan IndexNow aktif?" \
    || warn "Belum tuntas — bisa diulang nanti, stage ini akan menanyakan ulang."
fi

# ── 6 ───────────────────────────────────────────────────────────────────────
stage "Verifikasi otomatis"
say "curl ke $SITE_URL/ dengan lima User-Agent berbeda:"
while :; do
  if print_bot_table; then
    note "✓ Semua bot AI lolos (bukan 403), facebookexternalhit tetap 200."
    break
  fi
  warn "Ada bot AI yang masih 403, atau facebookexternalhit berhenti 200."
  warn "Perhatikan asimetrinya: kalau Googlebot di atas lolos 200 dari IP yang"
  warn "sama sementara bot AI 403, itu bukti kuat aturan yang menyasar AI"
  warn "secara spesifik — bukan penolakan bot tak-dikenal secara umum."
  note "curl dari IP mana pun bukan bukti sempurna (Cloudflare memverifikasi"
  note "bot lewat rDNS/IP), tapi Firewall Events di dashboard adalah buktinya:"
  open_url "https://dash.cloudflare.com/"
  step "Domain $APEX_DOMAIN → Security → Events, filter Action = Block, lihat"
  step "  apakah UA AI di atas muncul dan aturan mana yang menahannya."
  if confirm "Sudah diperbaiki di Cloudflare — coba verifikasi lagi sekarang?"; then
    continue
  fi
  warn "GAGAL: crawler AI masih diblokir atau facebookexternalhit tidak lagi 200."
  warn "Perbaiki di Cloudflare (Security → Bots dan/atau Security → WAF), lalu jalankan ulang wizard ini."
  exit 1
done

ROBOTS_FINAL=$(curl -sS --max-time 20 "$ROBOTS_URL" 2>/dev/null || true)
if grep -q "BEGIN Cloudflare Managed content" <<<"$ROBOTS_FINAL"; then
  warn "robots.txt masih memuat blok '# BEGIN Cloudflare Managed content'."
  warn "Itu diharapkan untuk saat ini (ADR 0023: sumber kebenaran tetap panel"
  warn "Cloudflare) — tapi ingat blok ini perlu dicabut nanti agar"
  warn "src/app/robots.ts jadi satu-satunya penulis robots.txt."
else
  note "robots.txt sudah bersih dari blok Managed Content Cloudflare."
fi

# ── 7 ───────────────────────────────────────────────────────────────────────
stage "Selesai"
finish
say "Crawler AI terbuka dan alat ukur terdaftar. Tujuh tiket sesudahnya"
say "sekarang bisa dinilai — jalur reguler sudah sampai ke penanyanya."
